"""Build bilingual supplementary additions from audited new results."""
import json
from pathlib import Path
import pandas as pd
import edit_text as e
HERE=Path(__file__).resolve().parent;ROOT=HERE.parents[2];SOURCE=ROOT/'manuscript/source_data/nature_commitment_validation_v1'
def main():
    changes={};after={}
    def U(i,en,zh):changes[i]=dict(en=en,zh=zh)
    def A(i,key,en,zh):after.setdefault(i,[]).append(dict(id=key,en=en,zh=zh))
    U('M010','The workload mix sets which computing may participate. Online inference must respond to user requests, whereas some training and offline-inference work can wait within an agreed deadline. Production traces distinguish these classes and their scheduling priorities,<sup>20</sup> while operators must separately grant permission to defer them. At fixed eligible work, hourly demand depends on task sizes as well as job counts. Each job must fit between release and deadline, and postponement creates additional processing relative to operation without response, or compute debt.<sup>6,13,21,22</sup> Low-supply hours and recovery requirements can therefore invalidate a request despite sufficient average workload and installed hardware.','工作负载构成决定哪些计算能够参与。在线推理必须响应用户请求，而部分训练和离线推理可以在约定期限内等待。生产轨迹区分这些类别及调度优先级，<sup>20</sup> 运营者还需另行授予延期许可。在参与工作量固定时，每小时需求取决于任务规模和作业数量。每项工作都必须在释放至期限之间完成；延期会相对无响应运行产生额外处理义务，即计算债务。<sup>6,13,21,22</sup> 因此，即使平均工作量和已安装硬件充足，低供给小时与恢复要求仍可能使请求失效。')
    U('M015','We first examined what fraction of computing could plausibly enter the deferrable pool. Across 40.52 million execution spans in the released Alibaba summary,<sup>20</sup> online inference accounted for 54.5% of requested GPU-hours, offline inference for 21.5% and training for 19.4% (Fig. 1a). Low-priority training and offline inference together accounted for 22.0%. These descriptive resource-time shares identify a candidate pool from which an operator might authorise a smaller amount of work to wait.','我们首先考察可能进入可延期工作池的计算比例。Alibaba 发布汇总中的 4,052 万个执行片段显示，<sup>20</sup> 在线推理占请求 GPU-h 的 54.5%，离线推理占 21.5%，训练占 19.4%（图 1a）。低优先级训练与离线推理合计占 22.0%。这些描述性的资源时间份额确定了候选池，运营者可从中授权较小部分工作等待。')
    U('M025_decision','These checks define different decisions (Fig. 1c): revise requests that exceed supply or strict-window feasibility, investigate control where a feasible PI schedule exists, and qualify the causal policy independently before comparing prices. Qualification uses the complete success and failure sample. In the matched same-clock control, removing preceding calls left final-call electrical outcomes unchanged (Supplementary Table 15).','这些检查对应不同决策（图 1c）：请求超过供给或严格时间窗可行性时应调整请求；存在 PI 可行调度时应研究控制；比较价格前应独立检验因果策略资格。资格评估采用完整成功和失败样本。在匹配相同时刻的对照中，去掉前序调用后，末次调用的电气结果保持不变（补充表 15）。')
    U('M057','The reliability target was 0.95. Each offer was conditional on the controller, workload distribution and call schedule. We selected the largest qualifying candidate on a finite development grid and tested it independently, using a pointwise probability lower bound.','可靠性目标为 0.95。每个报价均以控制器、工作负载分布和调用安排为条件。我们在有限开发网格上选取通过标准的最大候选值，再使用逐项概率下界开展独立检验。')
    U('M061','Job shapes came from the Alibaba Serverless Infrastructure execution summary,<sup>20</sup> complementing an earlier public GPU trace.<sup>28</sup> The source mix used all 40,522,321 released spans, weighted by requested GPU-equivalents times uncapped duration and retaining every workload category. A reproducible, class-balanced 100,000-record subset supplied low-priority training and offline-inference job shapes only. This summary lacked production deadlines and the original temporal correlations.','作业形状来自 Alibaba Serverless Infrastructure 执行汇总，<sup>20</sup> 并以较早的公开 GPU 轨迹补充。<sup>28</sup> 源工作组合使用全部 40,522,321 个执行片段，以请求 GPU 当量乘未截断时长加权，保留所有工作类别。可复现、类别平衡的 100,000 条记录子集仅用于低优先级训练和离线推理的作业形状。该汇总缺少生产期限及原始时间相关性。')
    U('M070','The model used PUE 1.2 and 300 W/node fixed overhead. Online, development, other and unknown rigid work used a 300.02-W active-GPU engineering proxy, with separate 150- and 225-W controls. Rigid demand remained at its class-weighted mean. Board measurements calibrated the batch-work conversion; request latency and burst-level rigid power require application-level evidence.','模型采用 PUE 1.2 和每节点 300 W 固定开销。在线推理、开发、其他和未知刚性工作采用 300.02 W/活动 GPU 的工程代理，并设置 150 和 225 W 独立对照。刚性需求保持在按类别加权的均值。板卡测量校准批工作功率换算；请求延迟及突发刚性功率需要应用层证据。')
    U('M093','The reference fixed site charge was US$25,000 per year and the variable enablement charge was zero. Accounting multiplied offered power and physical ledger quantities by 1000 divided by each configuration’s operating peak, then applied the site charge once. Annual draws sampled 50 independent single events or 12 independent complete four-call series, retaining failures. The external-source register<sup>37–42</sup> contextualises the financial sensitivity ranges; Scope and interpretation defines the limits of this proportional accounting.','参考固定场站费用为每年 25,000 美元，可变接入费用为零。核算将报价功率和物理账本量乘以 1000 除以各配置运行峰值，再计入一次场站费用。年度抽样采用 50 个独立单次事件或 12 个独立完整四调用序列，并保留失败。外部来源登记<sup>37–42</sup> 为财务敏感性范围提供背景；“范围与解释”界定这种按比例核算的适用边界。')
    U('M023_stats','Structural contrasts resampled 300 complete paired scenario seeds 5,000 times. Exact McNemar tests were Holm-adjusted over 36 binary structural contrasts; the 16 additional matched-target electrical contrasts formed a separate family. Both service endpoints used the pointwise one-sided 95% Wilson lower-bound criterion of 0.95. External workload summaries retained the observed week as their sampling unit; conditional empirical-mixture qualification is defined separately below.','结构比较对 300 个完整配对情景种子重采样 5,000 次。36 项二元结构比较采用精确 McNemar 检验和 Holm 校正；另外 16 项匹配末次调用的电气比较组成单独检验族。两种服务标准均采用逐项单侧 95% Wilson 下界达到 0.95 的标准。外部工作负载汇总以观测周为抽样单位；条件性经验混合分布资格检验在下文单独定义。')
    U('M036',
      'The same allocation could matter more for a different service. At 10% eligibility, raising flexible GPU allocation from 10% to 20% increased the no-BESS PV hosting gain from 5.40 to 24.99 kW (Supplementary Fig. 4d). Strict repeat solves retained these gains. Utilisation of a fixed 500-kW PV system improved by only 0.0057 percentage points without BESS (95% paired interval, 0.0019–0.0106). This small LP result was unchanged by tighter feasibility tolerances, whereas the corresponding BESS gain was numerically zero (Supplementary Fig. 10c,d; Supplementary Table 24). Hosting and utilisation therefore measure different benefits; absolute hosting and energy outcomes appear in Supplementary Fig. 7.',
      '同样的配置对另一种服务可能更有价值。在 10% 参与比例下，将灵活 GPU 分配从 10% 提高至 20%，使无储能 PV 接纳增益由 5.40 增至 24.99 kW（补充图 4d），严格重算保留了这些增益。固定 500 kW PV 系统的利用率在无储能时只提高 0.0057 个百分点，95% 配对区间为 0.0019–0.0106。收紧可行性容差后，这一微小的线性规划结果保持不变；相应储能情景的增益则在数值上为零（补充图 10c,d；补充表 24）。因此，接纳和利用率衡量不同收益；绝对接纳与电量结果见补充图 7。')
    U('M043',
      'The price comparison applies to the qualified reference-distribution products. The lower resource-time offer requires its own operating ledger before those prices can be used for that workload. Waiting and missed-work valuations are varied explicitly, with single-event hardware and monetary sensitivity in Supplementary Fig. 8. Contract penalties, application checkpoint costs and hardware ageing remain unpriced, and annual accounting combines independent series.',
      '价格比较针对参考分布中的合格产品。较低的资源时间报价，需要用自身运行账本核算后才能为该工作负载采用相应价格。等待与漏期估值均有明确敏感性分析，单次事件的硬件和货币假设见补充图 8。合同罚款、应用检查点成本及硬件老化仍未定价，年度核算采用独立序列组合。')
    pv_method='The fixed-capacity programme used 500 kW of PV and lexicographically maximised local PV use, minimised grid import and then minimised battery throughput, retaining a 10<sup>−5</sup>-kWh lock at each preceding optimum. Rigid and flexible schedules were paired on 100 inputs; mean utilisation gains used 10,000 paired bootstrap resamples (seed 20260911). No-BESS models are continuous linear programmes, so a relative MIP gap does not set their precision. We repeated all 800 primary 10% PV optimisations and 200 no-BESS GPU20 hosting optimisations with HiGHS<sup>36</sup> relative and absolute MIP gaps 10<sup>−7</sup> and primal, dual and MIP feasibility tolerances 10<sup>−8</sup>. Each solve used one thread and a 120-s limit. All fixed-PV programmes resolved; 34 flexible BESS hosting problems reached the time limit. Their feasible and dual bounds, retained in full, did not affect the minimum hosting boundary over 100 scenarios. Primary-objective bounds separate numerical uncertainty from paired sampling intervals (Supplementary Table 24).'
    pv_zh='固定容量程序采用 500 kW PV，按字典序最大化本地 PV 利用、最小化电网购电、再最小化储能吞吐，对此前各级最优值保留 10<sup>−5</sup> kWh 锁定容差。刚性和灵活调度在 100 个输入上配对；平均利用率增益采用 10,000 次配对自助抽样，种子为 20260911。无储能模型是连续线性规划，因此其精度不由相对 MIP gap 决定。我们重算了主 10% 情景的全部 800 项 PV 优化，以及 GPU20 无储能接纳的 200 项优化；HiGHS<sup>36</sup> 的相对、绝对 MIP gap 均为 10<sup>−7</sup>，原始、对偶及 MIP 可行性容差均为 10<sup>−8</sup>。每次求解使用一个线程，时限为 120 s。所有固定 PV 程序均求解完成；34 项灵活储能接纳问题达到时限，其完整保留的可行解与对偶界不影响 100 个情景中的最小接纳边界。主目标界用于区分数值不确定性与配对抽样区间（补充表 24）。'
    U('M086',pv_method,pv_zh)
    U('S20_005','Read the commitment evidence in sequence: workload-specific offer selection and confirmation (Table 22), paired weights and hourly order (Table 20), strict-window diagnosis (Table 19), and reference-product costs (Table 21). Tables 23–24 document power accounting and numerical precision. Historical studies are labelled separately in Note 7.','承诺证据建议依次阅读：工作负载特定的报价选择与确认（表 22）、配对权重与小时顺序（表 20）、严格时间窗诊断（表 19）以及参考产品成本（表 21）。表 23–24 记录功率核算和数值精度。历史研究在说明 7 中单独标注。')
    U('S20_006',
      '| Question | Methods | Displays |\n|---|---|---|\n| Work composition and power | 1–3, 8 | Fig. 1; Supplementary Figs. 2, 10; Tables 1–3, 23 |\n| Single-event offers and notice | 4–5 | Fig. 2; Table 4 |\n| Reference repeated offers | 6 | Fig. 4c,d; Supplementary Fig. 9a; Table 18 |\n| Workload-specific offers | 6 | Fig. 3a; Supplementary Fig. 9b,c; Table 22 |\n| Workload weights and hourly order | 6 | Fig. 3c,d; Fig. 4a,b; Table 20 |\n| Supply and strict-window diagnosis | 6 | Fig. 3b; Fig. 4; Table 19 |\n| Structural and call-history controls | 6 | Supplementary Figs. 3, 6; Tables 5, 10–16 |\n| PV and allocation controls | 7–8 | Fig. 5; Supplementary Figs. 4, 7, 10; Tables 6, 8, 24 |\n| Operating exposure and participation | 9 | Fig. 6; Supplementary Figs. 5, 8; Tables 7, 9, 12, 17, 21 |',
      '| 问题 | 方法 | 图表 |\n|---|---|---|\n| 工作构成与功率 | 1–3、8 | 图 1；补充图 2、10；表 1–3、23 |\n| 单次报价与通知 | 4–5 | 图 2；表 4 |\n| 参考重复报价 | 6 | 图 4c,d；补充图 9a；表 18 |\n| 工作负载特定报价 | 6 | 图 3a；补充图 9b,c；表 22 |\n| 权重与小时顺序 | 6 | 图 3c,d；图 4a,b；表 20 |\n| 供给与严格时间窗 | 6 | 图 3b；图 4；表 19 |\n| 结构与调用历史 | 6 | 补充图 3、6；表 5、10–16 |\n| PV 与分配对照 | 7–8 | 图 5；补充图 4、7、10；表 6、8、24 |\n| 运行暴露与参与 | 9 | 图 6；补充图 5、8；表 7、9、12、17、21 |')
    # Exact formula and definitions shared with the main text.
    U('S20_030',e.UPDATES['M068']['en'],e.UPDATES['M068']['zh'])
    terms=e.AFTER['M068'][0];U('S20_031',terms['en'],terms['zh'])
    cap=e.AFTER['M024_workload_methods'][0];A('S024_workload_methods','S27_capacity_methods',cap['en'],cap['zh'])
    U('S20_046',pv_method,pv_zh)
    power=e.AFTER['M070'][0];A('S20_048','S27_overhead_methods',power['en'],power['zh'])
    # Remove a vacuous testing family without altering the genuine structural tests.
    old=json.loads((HERE/'before/chinese_v20/supplement_aligned_blocks.json').read_text())['blocks'];by={b['id']:b for b in old}
    for key in ['S20_038','S20_080']:
        en=by[key]['en'];zh=by[key]['zh']
        en=en.replace('Notice comparisons used exact paired McNemar tests with Holm correction across 20 contrasts.','All 20 notice comparisons had zero discordant success pairs; their outcomes are reported as identical.').replace('These intervals and qualifications are pointwise, apart from the declared notice-test correction.','These intervals and qualifications are pointwise.').replace('together with all paired binary outcomes and Holm-adjusted exact McNemar tests','together with all paired binary outcomes, which coincide across notice settings')
        import re
        zh=re.sub(r'[^。]*Holm[^。]*。','20 项通知比较的成功标记均无不一致配对，直接报告逐一相同。',zh)
        zh=zh.replace('除声明的通知检验校正外','')
        U(key,en,zh)
    en=by['S20_085']['en'].replace('| 10 | Yes | 672.39 | 677.61 | 5.22 | 0.0000 [-0.0000, 0.0001] |','| 10 | Yes | 672.39 | 677.61 | 5.22 | 0 (numerical; Table 24) |')
    zh=by['S20_085']['zh'];zh=zh.replace('0.0000 [-0.0000, 0.0001]','0（数值零；表 24）')
    U('S20_085',en,zh)
    A('S20_086','S27_pv_note','The 10% entries use the strict precision audit in Table 24; other eligibility cases retain their original solver settings. The no-BESS utilisation gain is an LP result, unchanged to 2.9 × 10<sup>−14</sup> percentage points in the paired contrast after tightening tolerances. In the primary BESS case, the optimal PV-use contrasts are zero to numerical precision; tiny final signed differences arise within the lexicographic lock.','10% 行采用表 24 的严格精度核查；其他参与情景保留原求解设置。无储能利用率增益来自线性规划，收紧容差后配对差异的最大变化为 2.9 × 10<sup>−14</sup> 个百分点。主储能情景的最优 PV 利用对比在数值精度内为零；最终微小的有符号差异位于字典序锁定容差范围内。')
    U('S20_065',by['S20_065']['en']+' The 10% primary points and no-BESS GPU20 hosting point use the strict repeat audit; other points retain the original settings (Table 24).',by['S20_065']['zh']+' 主 10% 数据点和 GPU20 无储能接纳点采用严格重算；其他点保留原设置（表 24）。')
    A('S26_8_caption','S27_F9_title','### Supplementary Figure 9 | Independent qualification under reference and observed-week inputs','### 补充图 9 | 参考输入与观测周输入的独立资格检验')
    A('S26_8_caption','S27_F9_image','![Supplementary Figure 9](../docs/figures/commitment_validation_v1/artwork/AIDRBench_Supplementary_Figure_9.png)','![补充图 9](../docs/figures/commitment_validation_v1/artwork/AIDRBench_Supplementary_Figure_9.png)')
    A('S26_8_caption','S27_F9_caption',
      '**a,** Independently confirmed four- and eight-hour reference-distribution offers of 5.60 and 4.42 kW (300 scenarios each), retained from the preceding figure set. **b,** Development lower bounds across every candidate for count and resource-time weighting (100 new draws each); solid circles show the 1% standard and dashed squares the zero-miss standard; both select the same offer within each weight. **c,** Independent confirmation for the two selected offers and the fixed 2.95-kW resource-time comparator (300 new draws each). Points show success fractions and lower whiskers one-sided 95% Wilson bounds. Dashed lines mark the 0.95 qualification criterion. b,c condition on an equal empirical mixture of eight fixed observed weeks, paired synthetic tasks and call phases; they do not expand the number of observed weeks. All calls last eight hours with 16-h start spacing in b,c. a uses a different reference workload distribution.',
      '**a，** 参考分布四小时与八小时报价 5.60、4.42 kW 的独立确认，各 300 个情景，保留自上一版图组。**b，** 次数和资源时间加权的所有候选报价开发下界，各 100 次新抽样。实线圆点为 1% 标准，虚线方点为零漏期标准；每种权重的两种标准选中相同报价。**c，** 两个选定报价及资源时间固定 2.95 kW 比较请求的独立确认，各 300 次新抽样。点为成功比例，下须为单侧 95% Wilson 下界，虚线为 0.95 资格标准。b,c 以八个固定观测周的等权经验混合分布、配对合成任务及调用相位为条件，并未增加观测周数量；调用时长均为八小时、开始间隔 16 h。a 使用另一种参考工作负载分布。')
    A('S26_8_caption','S27_F10_title','### Supplementary Figure 10 | Power accounting and solver-precision checks','### 补充图 10 | 功率核算与求解精度检查')
    A('S26_8_caption','S27_F10_image','![Supplementary Figure 10](../docs/figures/commitment_validation_v1/artwork/AIDRBench_Supplementary_Figure_10.png)','![补充图 10](../docs/figures/commitment_validation_v1/artwork/AIDRBench_Supplementary_Figure_10.png)')
    A('S26_8_caption','S27_F10_caption',
      '**a,** Exact components of the 193.438980-kW primary operating peak; PUE applies to all components. **b,** The unchanged 5.898243-kW single-event offer as a share of peak as node overhead varies. Points are deterministic accounting values, not replicate estimates. Re-scoring all 600 reference repeated schedules preserves their success flags at each overhead; Table 23 gives PCC headroom. **c,d,** Each point compares the original and strictly solved flexible-minus-rigid utilisation contrast for one of 100 paired primary scenarios, without and with BESS. The dashed diagonal marks equality, not a fitted model. c is a continuous LP and its tiny gain is unchanged; d resolves to numerical zero after tightening MIP and feasibility tolerances. The final lexicographic difference and primary objective bounds are reported separately in Table 24. No statistical inference is assigned to pointwise solver agreement.',
      '**a，** 主情景 193.438980 kW 运行峰值的精确分项，全部分项均计入 PUE。**b，** 节点开销变化时，保持 5.898243 kW 单次报价的峰值占比。点为确定性核算值，不是重复估计。对全部 600 条参考重复调度重新评分后，各档开销均保留原成功标记；表 23 给出接入余量。**c,d，** 每个点比较一个主情景的原始与严格求解“灵活减刚性”利用率差异，无储能和有储能各 100 个配对情景。虚线表示相等，而非拟合模型。c 是连续线性规划，其微小增益保持不变；d 在收紧 MIP 和可行性容差后归于数值零。最终字典序差异与主目标界在表 24 分别报告。逐点求解一致性不赋予统计推断。')
    # Tables retain all selected endpoints and the failed comparator.
    A('S24_T21_note','S27_T22','### Supplementary Table 22 | Workload-specific offers on new independent model draws','### 补充表 22 | 新独立模型抽样下的工作负载特定报价')
    tab='| Weight | Role | Request (kW) | Development | Confirmation (both rules) | Lower (both rules) |\n|---|---|---|---|---|---|\n| Submission counts | Selected | 2.9491 | 100/100 | 300/300 | 0.991062 |\n| Task resource-time | Selected | 1.4746 | 100/100 | 300/300 | 0.991062 |\n| Task resource-time | Fixed comparator | 2.9491 | 53/100 | 120/300 | 0.354570 |'
    zh=tab.replace('Weight','权重').replace('Role','用途').replace('Request (kW)','请求（kW）').replace('Development','开发').replace('Confirmation (both rules)','确认（两种标准）').replace('Lower (both rules)','下界（两种标准）').replace('Submission counts','提交次数').replace('Task resource-time','任务资源时间').replace('Selected','选定').replace('Fixed comparator','固定比较')
    A('S24_T21_note','S27_T22_data',tab,zh)
    A('S24_T21_note','S27_T22_note','Four eight-hour calls, 16-h start spacing, zero notice, 10% eligible work and 58 flexible GPUs. All 800 count/resource-time input baselines pass zero-miss service. Development and confirmation seeds are disjoint; the latter never reselects an offer. Each model draw independently samples one of eight fixed weeks with equal probability. The ratio 2.0 compares independently confirmed finite-grid offers; the 180 failed comparator draws all encounter instantaneous shortage. All nine candidate values and outcomes are in Source Data.','四次八小时调用，开始间隔 16 h，通知为零，10% 工作参与，58 块灵活 GPU。800 个次数/资源时间输入基线全部通过零漏期服务。开发与确认种子分离，确认集不重新选报价。每次模型抽样独立、等概率选择八个固定周之一。2.0 是独立确认的有限网格报价之比；比较请求的 180 次失败全部遇到即时供给不足。源数据包含全部九个候选值和结果。')
    A('S24_T21_note','S27_T23','### Supplementary Table 23 | Fixed node overhead and unchanged-schedule feasibility','### 补充表 23 | 固定节点开销与原调度可行性')
    s=pd.read_csv(SOURCE/'fixed_overhead_summary.csv');lines=['| W/node | Peak (kW) | 5.90 kW / peak (%) | 4 h zero successes | 8 h zero successes | Minimum PCC headroom (kW) |','|---|---|---|---|---|---|']
    for overhead,g in s.groupby('node_overhead_w'):
        a=g[g.program=='H4P16'].iloc[0];b=g[g.program=='H8P16'].iloc[0];lines.append(f'| {overhead:.0f} | {a.operating_peak_kw:.2f} | {a.single_offer_pct_peak:.2f} | {a.successes_zero}/300 | {b.successes_zero}/300 | {g.minimum_pcc_margin_kw.min():.2f} |')
    tab='\n'.join(lines);zh=tab.replace('Peak (kW)','峰值（kW）').replace('5.90 kW / peak (%)','5.90 kW / 峰值（%）').replace('4 h zero successes','4 h 零漏期成功').replace('8 h zero successes','8 h 零漏期成功').replace('Minimum PCC headroom (kW)','最小接入余量（kW）');A('S24_T21_note','S27_T23_data',tab,zh)
    A('S24_T21_note','S27_T23_note','The four- and eight-hour repeated schedules retain requests of 5.603331 and 4.423682 kW; the 5.898243-kW column is a single-event accounting comparison. Each row re-scores the same 600 frozen schedules after adding a constant to both controlled and baseline power. It establishes feasible operating witnesses at those requests, without a new controller selection or independent trial. All original success flags are preserved, including failures. The PCC rating remains 1,100 kW.','四小时与八小时重复调度分别保持 5.603331 和 4.423682 kW 请求；5.898243 kW 一列是单次事件的核算比较。每行对相同 600 条冻结调度的响应与基线功率同时加常数后重新评分，得到这些请求下的运行可行见证，没有新的控制器选择或独立试验。全部原成功标记均保留，包括失败。接入额定限额仍为 1,100 kW。')
    A('S24_T21_note','S27_T24','### Supplementary Table 24 | Strict PV repetition and optimisation bounds','### 补充表 24 | 严格 PV 重算与优化界')
    tab='| Quantity | Strict result | Numerical evidence |\n|---|---|---|\n| 10%, no BESS, hosting gain | 5.395897 kW | LP; all 200 solves optimal |\n| 10%, BESS, hosting gain | 5.222051 kW | Minimum-bound interval width <0.000001 kW |\n| GPU20, no BESS, hosting gain | 24.987573 kW | LP; all 200 solves optimal |\n| 10%, no BESS, mean utilisation gain | 0.005716203 pp; 95% paired interval [0.001893867, 0.010571870] | Maximum paired change 2.84 × 10⁻¹⁴ pp |\n| 10%, BESS, mean utilisation gain | Numerical zero; final signed mean −7.09 × 10⁻¹⁰ pp | Mean primary-objective contrast bounds [−8.53 × 10⁻¹⁶, 8.53 × 10⁻¹⁶] pp |'
    zh=tab.replace('Quantity','指标').replace('Strict result','严格结果').replace('Numerical evidence','数值证据').replace('no BESS','无储能').replace('BESS','储能').replace('hosting gain','接纳增益').replace('LP; all 200 solves optimal','线性规划，200 次均最优').replace('Minimum-bound interval width','最小边界区间宽度').replace('mean utilisation gain','平均利用率增益').replace('95% paired interval','95% 配对区间').replace('Maximum paired change','最大配对变化').replace('Numerical zero; final signed mean','数值零；最终有符号均值').replace('Mean primary-objective contrast bounds','平均主目标差异界');A('S24_T21_note','S27_T24_data',tab,zh)
    A('S24_T21_note','S27_T24_note','Strict options: relative/absolute MIP gaps 1e−7, primal/dual/MIP feasibility tolerances 1e−8, one thread and 120 s per solve. All 400 fixed-PV programmes and 400 no-BESS hosting problems resolved. Of 200 BESS hosting problems, 166 resolved and 34 flexible cases reached the limit. For a maximisation problem, feasible values bound the optimum from below and dual values from above. Taking minima of each bound across all 100 cases bounds the all-scenario hosting boundary; all unresolved cases had feasible capacities above the resolved limiting case. Thus all cases remain included. Mean PV-use contrasts use primary-objective bounds, whereas final utilisation includes the 1e−5-kWh lexicographic lock. Sampling intervals exclude numerical error.','严格选项为相对/绝对 MIP gap 1e−7、原始/对偶/MIP 可行性容差 1e−8、一个线程及每次 120 s。400 项固定 PV 程序与 400 项无储能接纳问题全部完成。200 项储能接纳问题中，166 项完成，34 项灵活情景达到时限。最大化问题的可行值给出最优值下界，对偶值给出上界；分别对全部 100 个情景的上下界取最小，即得到全情景接纳边界的上下界。所有未完成情景的可行容量均高于已求解的限制情景，因此全部情景均保留。平均 PV 利用差异采用主目标界，最终利用率还包含 1e−5 kWh 字典序锁定容差。抽样区间不含数值误差。')
    for block in list(changes.values())+[b for group in after.values() for b in group]:
        for lang in ['en','zh']:
            for old,new in [('10⁻¹⁴','10<sup>−14</sup>'),('10⁻¹⁰','10<sup>−10</sup>'),('10⁻¹⁶','10<sup>−16</sup>')]:block[lang]=block[lang].replace(old,new)
    (HERE/'supplement_edits.json').write_text(json.dumps(dict(replace=changes,after=after),ensure_ascii=False,indent=2)+'\n')
    print('Prepared bilingual numerical additions')
if __name__=='__main__':main()
