"""Evidence-centred v0.25 revision with paragraph-aligned Chinese text."""
import hashlib
import importlib.util
import json
import re
from pathlib import Path

HERE=Path(__file__).resolve().parent;ROOT=HERE.parents[2]
READER=ROOT/'docs/chinese_reader/v19'
spec=importlib.util.spec_from_file_location('reader_helpers',HERE.parent/'workload_composition_2026-09-09/integrate_content.py')
h=importlib.util.module_from_spec(spec);spec.loader.exec_module(h)
MAIN={};SI={};INSERT_MAIN={};INSERT_SI={}
REMOVE={'M019','M023_limits','M048'}
def m(i,en,zh):MAIN[i]=(en,zh)
def s(i,en,zh):SI[i]=(en,zh)
def add(dest,after,i,en,zh):dest.setdefault(after,[]).append(dict(id=i,en=en,zh=zh))

m('M006',
'Artificial-intelligence data centres could help electricity grids accommodate growing demand by postponing computing, but a response commitment must remain deliverable as workloads change. Here we test how workload representation affects this commitment in a trace-informed scheduling and electricity model. At 10% work eligibility, independent tests support four- and eight-hour offers of 5.60 and 4.42 kW at a 95% success-probability target, with zero missed work required for a successful series. Yet a fixed 2.95-kW request succeeds in 80/80 submission-count-weighted realisations and only 31/80 task-resource-time-weighted realisations across eight observed weeks with matched weekly work totals. Permuting hourly blocks raises resource-time success to 55/80 with a 1% missed-work allowance and 54/80 with zero missed work. Workload weighting and hourly order with call alignment therefore expose distinct limits. Immediate supply checks and strict task-window feasibility tests separate impossible delivery from failures with a feasible full-information schedule. Operating ledgers then compare compensation only for independently qualified products. This assessment identifies when a workload change invalidates a model-supported commitment, when controller improvement remains possible and when a price comparison is meaningful.',
'人工智能数据中心可以通过推迟计算，帮助电网应对不断增长的需求，但响应承诺必须在工作负载变化后仍然可交付。本文在受生产轨迹约束的调度与电力模型中，检验工作负载的表征方式如何影响这种承诺。当 10% 工作允许参与时，独立测试支持四小时 5.60 kW 和八小时 4.42 kW 的报价，整体成功概率目标为 95%，且一次序列只有零漏期工作才能被判为成功。然而，在八个实际观察周中保持每周工作总量一致，固定 2.95 kW 请求按提交次数加权时成功 80/80，按任务资源时间加权时仅成功 31/80。置乱完整小时块后，资源时间测试在允许 1% 漏期工作时成功 55/80，在要求零漏期时成功 54/80。因此，工作量权重以及小时顺序与调用的对齐关系，揭示了不同层面的限制。即时供给检查与严格任务时间窗检验进一步区分无法交付的情形，以及完整未来信息下存在可行调度的控制失败。随后，运行账本只对通过独立资格检验的产品比较补偿。这一评估帮助识别工作负载变化何时使模型支持的承诺失效、何时仍有改进控制器的空间，以及何时才有意义开展价格比较。')

m('M009',
'A field demonstration on 256 graphics processing units (GPUs) reduced power by 25% for three hours while meeting the tested quality-of-service requirements.<sup>3</sup> Batch scheduling, server power management and workload migration have been used to reduce peaks and participate in demand response.<sup>4–8</sup> Carbon-aware scheduling extends these controls to hours and locations with lower emissions or greater renewable availability.<sup>9–12</sup> Other studies address pause-and-resume decisions and GPU power capping.<sup>13,14</sup> Trace-based and planning studies connect workload flexibility to demand-response programmes, advance notice and grid interconnection.<sup>15–18</sup> A recent preprint distinguishes eligible workload power from dependable relief through duration, reliability, portfolio structure and delivery and recovery requirements.<sup>19</sup> These advances motivate a more specific commitment question: can a request that passes a simplified workload test still fail when task-size variation and hourly order are represented more faithfully?',
'一项在 256 块图形处理器（GPU）上的现场演示，在满足所测试服务质量要求的同时，将功率降低了 25%，持续三小时。<sup>3</sup> 批处理调度、服务器功率管理与工作负载迁移已被用于降低峰值和参与需求响应。<sup>4–8</sup> 碳感知调度进一步将这些控制扩展到排放更低或可再生能源更充足的时段和地点。<sup>9–12</sup> 另一些研究讨论暂停与恢复决策以及 GPU 功率上限。<sup>13,14</sup> 基于轨迹和规划的研究也将工作负载灵活性与需求响应计划、提前通知和电网接入联系起来。<sup>15–18</sup> 一篇近期预印本通过持续时间、可靠性、组合结构以及交付和恢复要求，区分了可参与工作功率与可靠减负。<sup>19</sup> 这些进展引出一个更具体的承诺问题：当任务规模差异与小时顺序得到更充分的表征时，一个通过简化工作负载测试的请求是否仍会失败？')
m('M010',
'The workload mix sets which computing may participate. Online inference must respond to user requests, whereas some training and offline-inference work can wait within an agreed deadline. Production traces distinguish these classes and their scheduling priorities,<sup>20</sup> but priority is not permission to defer work for grid services. Even at fixed eligible work, job counts do not specify how much work arrives in each hour. Each job must fit between release and deadline, and postponement creates an additional processing obligation relative to operation without response, or compute debt.<sup>6,13,21,22</sup> Thus, low-supply hours and recovery requirements can invalidate a request even when average workload and installed hardware appear sufficient.',
'工作负载构成决定哪些计算可以参与。在线推理必须及时响应用户请求，而部分训练和离线推理可以在约定期限内等待。生产轨迹区分了这些类别及其调度优先级，<sup>20</sup> 但优先级不等于允许为了电网服务而推迟工作。即使可参与工作总量相同，作业次数也不能确定每个小时到达的工作量。每项作业仍必须在释放与期限之间完成；推迟执行会产生相对于无响应运行的额外处理义务，即计算债务。<sup>6,13,21,22</sup> 因此，即便平均工作量和已安装硬件看似充足，供给低谷与恢复要求仍可能使请求无法履行。')
m('M011',
'Delivery and value also require different evidence. At a community point of common coupling (PCC), data-centre demand interacts with photovoltaic (PV) generation and battery energy storage systems (BESS).<sup>23–27</sup> A hardware allocation that benefits PV hosting need not increase an independently tested response offer. For an operator, postponement creates waiting and service-loss exposure, while access charges affect whether participation is worthwhile. Valuing those quantities cannot make an undeliverable commitment feasible. A useful assessment must therefore establish what can be offered before comparing service products at stated prices.',
'交付能力与参与价值还需要不同的证据。在社区公共耦合点（PCC），数据中心需求与光伏（PV）发电和电池储能系统（BESS）相互作用。<sup>23–27</sup> 有利于光伏接纳的硬件分配，不一定提高通过独立检验的响应报价。对运营者而言，推迟执行产生等待与服务损失暴露，而接入费用影响参与是否值得。给这些数量定价，不能使无法交付的承诺变得可行。因此，有用的评估必须先明确能够提供什么，再在指定价格下比较服务产品。')
m('M012',
'Here we identify how a simplified workload representation can support the wrong commitment decision. AIDRBench combines trace-informed jobs, four-GPU board-power measurements and a modelled community electricity system. Production execution data inform plausible work-permission scenarios. We independently test causal-controller offers and compare matched submission-count and task-resource-time profiles in their observed and permuted hourly orders.<sup>28</sup> An instantaneous supply condition and same-scenario perfect-information feasibility checks then distinguish why requests fail. Finally, complete operating ledgers compare qualified duration products with non-participation. Together, the tests connect workload characterisation to decisions about the request, controller and compensation.',
'本文识别简化的工作负载表征如何支持错误的承诺决策。AIDRBench 结合受轨迹约束的作业、四块 GPU 的板卡功率测量与社区电力系统模型。生产执行数据为合理的工作参与许可情景提供依据。我们独立检验因果控制器的报价，并对提交次数和任务资源时间曲线开展配对比较，分别保留实际小时顺序或置乱该顺序。<sup>28</sup> 随后，即时供给条件与同场景完美信息可行性检验区分请求失败的原因。最后，完整运行账本将合格时长产品与不参与进行比较。这些测试共同将工作负载表征与请求、控制器和补偿决策联系起来。')
m('M016',
'The primary scenarios allowed 5%, 10% or 20% of total offered work to wait, preserving the observed class mix and varying permission within low-priority batch work. The 40% comparison required almost all training and offline inference to opt in. The 60% case additionally reassigned 19.1 percentage points of total work from online to offline inference (Fig. 1b). Online jobs remained ineligible; these larger fractions therefore describe additional business assumptions.',
'主要情景允许总供给工作量的 5%、10% 或 20% 等待，在保留观测类别构成的同时，改变低优先级批处理工作的许可比例。40% 对照要求几乎全部训练和离线推理参与。60% 情景还将总工作量的 19.1 个百分点从在线推理重新分配到离线推理（图 1b）。在线作业始终不允许参与，因此更高比例代表额外的业务假设。')
m('M017',
'Each configuration retained 576 GPUs and 374.4 GPU-h of offered work per hour. Assigning approximately the same fraction of GPUs as eligible work kept mean utilisation near 65% in both pools. The primary comparison therefore changes permission together with supporting allocation; controls at 10% eligibility isolate allocation (Fig. 5). Four-GPU board-power calibration constrained the batch-work conversion, whereas rigid workloads used an engineering power proxy (Supplementary Fig. 2; Supplementary Tables 1–3).',
'各配置均保留 576 块 GPU，每小时供给 374.4 GPU-h 工作。向灵活池分配与可参与工作比例大致相同的 GPU，使两个池的平均利用率均接近 65%。因此，主要比较同时改变参与许可及其配套分配；10% 参与比例下的对照则单独考察分配（图 5）。四块 GPU 的板卡功率校准约束批处理工作的功率转换，刚性工作负载采用工程功率代理（补充图 2；补充表 1–3）。')
m('M022',
'Development-selected single-event offers of 2.95, 5.90 and 11.80 kW qualified on 300 independent scenarios at 5%, 10% and 20% eligibility, respectively, corresponding to 1.6–5.9% of operating peak demand (Fig. 2a; Supplementary Table 4). The 40% and 60% comparisons qualified at 22.19 and 34.00 kW under their additional assumptions. The proportional low-share response follows the shared job-template scaling and allocation policy. Relaxed perfect-information (PI) tolerance statistics provide a planning comparison but do not guarantee individual work-group feasibility (Methods).',
'当参与比例分别为 5%、10% 和 20% 时，开发阶段选出的单次报价 2.95、5.90 和 11.80 kW 在 300 个独立情景上通过资格检验，对应运行峰值需求的 1.6%–5.9%（图 2a；补充表 4）。在额外业务假设下，40% 和 60% 对照的合格报价为 22.19 和 34.00 kW。低比例情景的比例关系来自共享作业模板的缩放和分配规则。放松的完美信息（PI）容忍统计量提供规划比较，但不保证各工作组可行（见方法）。')
m('M023',
'The same selected power qualified at four and eight hours on the tested grid, with success decreasing from 295/300 to 292/300 in every configuration; one-sided 95% probability lower bounds were 0.9662 and 0.9533. Zero-, two- and six-hour notice gave identical paired outcomes (Fig. 2b). Because jobs cannot execute before release and the baseline already processes available work eagerly, advance information created no extra pre-executable work in this setting.',
'在所测试网格中，相同选定功率均通过四小时与八小时资格检验，但各配置成功数均由 295/300 降至 292/300；单侧 95% 概率下界分别为 0.9662 和 0.9533。提前零、两和六小时通知得到相同的配对结果（图 2b）。由于作业不能在释放前执行，且基线已尽早处理可用工作，在这一设定下，提前信息并未增加可提前执行的工作。')
m('M027',
'At 10% work eligibility, we tested four calls using a controller that enforces every overlapping recovery obligation. In the reference configuration—65% offered utilisation, reference deadlines and a 10% GPU pool—the four- and eight-hour offers were 5.60 and 4.42 kW, both with 16-h start spacing. When successful series required zero missed work, independent confirmation gave 297/300 and 296/300 successes, with one-sided 95% probability lower bounds of 0.9752 and 0.9706 (Fig. 3a). Both the 1% and zero-miss standards selected these capacities on the local grid (Supplementary Table 18). Their agreement provides no basis for applying a uniform capacity discount solely because the success criterion becomes stricter.',
'在 10% 工作允许参与时，我们使用落实每项重叠恢复义务的控制器测试四次调用。在参考配置下，即工作供给利用率 65%、参考期限和 10% GPU 池，四小时与八小时报价分别为 5.60 和 4.42 kW，调用开始间隔均为 16 h。当一次序列必须零漏期才能判为成功时，独立确认成功数分别为 297/300 和 296/300，单侧 95% 概率下界为 0.9752 和 0.9706（图 3a）。1% 与零漏期标准在局部网格上均选择这些容量（补充表 18）。两者一致的结果不支持仅因成功标准变严格，就施加统一的容量折减。')
m('M023_timing',
'These reference offers did not establish transfer to a different workload representation. In eight observed weeks, the fixed 2.95-kW request passed 80/80 chronological submission-count-weighted realisations but only 31/80 matched task-resource-time-weighted realisations (Fig. 3c,d). Weekly class totals, synthetic service rules, community profiles and event clocks were held fixed. All no-response baselines met zero-miss service. The 49 resource-time failures therefore arose under response commitments in otherwise service-feasible scenarios, rather than from more total eligible work or an infeasible baseline.',
'这些参考报价并不确立其对另一种工作负载表征的适用性。在八个实际观察周中，固定 2.95 kW 请求在原序提交次数加权下成功 80/80，在配对任务资源时间加权下仅成功 31/80（图 3c,d）。各类别周总工作量、合成服务规则、社区曲线与事件时刻均保持一致。全部无响应基线满足零漏期服务。因此，49 次资源时间失败发生于本来能够满足服务的情景加入响应承诺后，不能归因于总可参与工作量增加或基线本身不可行。')
add(INSERT_MAIN,'M023_timing','M025_order',
'Permuting whole hourly blocks separated workload weighting from the effect of hourly order and alignment. Count-weighted success remained 80/80, whereas resource-time success rose to 55/80 at the 1% standard and 54/80 at zero misses (Fig. 3c). Hourly rearrangement improved this comparison but did not restore count-weighted performance. It changes alignment with both calls and community demand, so the improvement cannot be assigned to autocorrelation alone. At the larger 4.42-kW request, all 80 chronological resource-time realisations failed; full cross-scores are retained in Supplementary Table 20.',
'置乱完整小时块进一步区分了工作量权重与小时顺序及对齐的影响。次数加权仍成功 80/80，而资源时间加权在 1% 标准下提高至 55/80，在零漏期标准下提高至 54/80（图 3c）。小时重排改善了这一对照的结果，却未恢复到次数加权的表现。重排同时改变与调用和社区需求的对齐，因此不能将改善全部归因于自相关。在更大的 4.42 kW 请求下，80 个原序资源时间实现全部失败；完整交叉评分保留在补充表 20。')

m('M029','### Supply and feasibility checks identify what a failed request requires','### 供给与可行性检查识别失败请求需要怎样调整')
m('M030',
'An instantaneous supply screen explained the electrical failures. For each event hour, we compared the matched baseline power available above community and idle-plus-rigid demand with 95% of the request. A deficit makes successful delivery impossible in that hour, even if all flexible execution stops. All 49 chronological resource-time failures at 2.95 kW met this condition; after permutation, it affected 25 realisations (Fig. 4a,b). A non-negative margin is necessary but insufficient: one of the 55 permuted resource-time realisations without shortage still failed the zero-miss endpoint.',
'即时供给检查解释了电力交付失败。对每个事件小时，我们将匹配基线中高于社区需求、空闲及刚性功耗的可削功率，与请求的 95% 比较。若存在缺口，即便停止全部灵活执行，该小时仍不可能成功交付。2.95 kW 原序资源时间测试的全部 49 次失败均满足这一条件；置乱后，该条件涉及 25 个实现（图 4a,b）。非负余量只是必要条件，并不足以保证成功：在置乱后没有即时不足的 55 个资源时间实现中，仍有一个未通过零漏期终点。')
m('M031',
'Strict task-window feasibility then distinguished failures beyond that supply condition. At a fixed 5.90-kW request, a reference scenario that passed the supply screen failed under causal control but admitted a full-information schedule meeting all electrical obligations with zero missed work (Fig. 3b; Supplementary Table 19). Halving its deadline slack made the request infeasible under the same delivery and recovery criteria; doubling GPU allocation did not restore feasibility. Each variant used its own matched baseline. The feasible reference case leaves room for controller improvement, whereas proven infeasibility calls for changing the request or operating terms. Neither finding follows from the causal failure alone.',
'随后，严格任务时间窗可行性区分了即时供给条件之外的失败。在固定 5.90 kW 请求下，一个通过供给检查的参考情景在因果控制下失败，却存在满足全部电气义务且零漏期的完整信息调度（图 3b；补充表 19）。将其期限余量减半后，在相同交付和恢复判据下，请求变为不可行；将 GPU 分配加倍也没有恢复可行性。各变体采用各自匹配的基线。参考情景的可行解说明仍有改进控制器的空间，而已证明的不可行则要求改变请求或运行条款。这两种判断都不能仅从因果控制失败得出。')
add(INSERT_MAIN,'M031','M025_decision',
'These checks define different decisions (Fig. 4c). Supply deficits identify series that cannot succeed; strict-window tests diagnose whether the remaining constraints admit a schedule. A feasible PI schedule is a diagnostic opportunity, not a deployable controller. A fixed causal policy must still pass independent qualification for its declared scenario distribution before its operating ledger enters price comparison. A single failed series is not automatically a rejection of a probabilistic contract: qualification retains the complete success and failure sample. In the matched same-clock control, removing preceding calls left final-call electrical outcomes unchanged (Supplementary Table 15), further limiting explanations based only on accumulated call history.',
'这些检查对应不同决策（图 4c）。供给缺口识别不可能成功的序列；严格时间窗检验诊断其余约束下是否存在调度。PI 可行解提供诊断与改进机会，但不是可部署的控制器。固定因果策略仍须在声明的情景分布上通过独立资格检验，其运行账本才能进入价格比较。一次序列失败并不自动否定概率性合同：资格检验保留完整成功与失败样本。在配对同一时刻的对照中，移除先前调用并未改变末次调用的电力结果（补充表 15），这也限制了仅用累计调用历史解释失败的说法。')

m('M034','### Allocation changes system value without necessarily increasing the offer','### 分配可以改变系统价值，而不一定提高报价')
m('M035',
'At fixed 10% work eligibility, increasing flexible GPU allocation from 10% to 20% or 30% left the tested 5.90-kW single-event offer at 295/300 four-hour and 292/300 eight-hour successes. The corresponding relaxed-PI tolerance statistics were also unchanged (Fig. 5a; Supplementary Fig. 4c). Reducing the rigid-class active-power proxy from 300 to 225 or 150 W per GPU preserved these baseline-relative responses but changed operating peak demand from 193.44 to 173.53 or 153.63 kW (Fig. 5b). Thus, eligible arrivals constrained this response, while rigid power remained relevant to facility demand and proportional cost accounting (Fig. 5c,d).',
'在固定 10% 工作允许参与时，将灵活 GPU 分配由 10% 提高至 20% 或 30%，所测试的 5.90 kW 单次报价仍保持四小时 295/300、八小时 292/300 成功。相应的放松 PI 容忍统计量也未改变（图 5a；补充图 4c）。将刚性类别活动功率代理从每 GPU 300 W 降至 225 或 150 W，未改变这些相对基线的响应，却使运行峰值需求从 193.44 kW 变为 173.53 或 153.63 kW（图 5b）。因此，可参与工作的到达约束了这一响应，而刚性功率仍影响设施需求与比例成本核算（图 5c,d）。')
m('M036',
'The same allocation could matter more for a different service. At 10% eligibility, raising the flexible GPU share from 10% to 20% increased the no-BESS PV hosting gain from 5.40 to 24.99 kW (Supplementary Fig. 4d). The primary 10% case nevertheless improved utilisation of a fixed 500-kW PV installation by only 0.0057 percentage points (95% paired interval, 0.0019–0.0106; Supplementary Fig. 4a,b). Hosting and utilisation therefore measure different benefits. All PV comparisons used separate full-information schedules; small storage contrasts remained limited by solver precision (Supplementary Table 6).',
'相同分配对另一种服务可能更重要。在 10% 工作参与比例下，将灵活 GPU 比例由 10% 提高至 20%，使无储能光伏接纳增量由 5.40 kW 增至 24.99 kW（补充图 4d）。然而，主要 10% 情景对固定 500 kW 光伏设施利用率的提高仅为 0.0057 个百分点（95% 配对区间 0.0019–0.0106；补充图 4a,b）。因此，接纳容量与利用率衡量不同收益。全部光伏比较采用独立的完整信息调度；微小储能差异仍受求解精度限制（补充表 6）。')
REMOVE.add('M037')
m('M040',
'Once a duration product qualified, its operating exposure and access charges could be valued separately. In the 10% eligibility single-event case, the assumed US$25,000 annual site fee accounted for about 95% of the US$863.26 per offered kW-year threshold (Supplementary Table 17). To distinguish fee allocation from operating consequences, we compared complete response-and-recovery ledgers for the qualified repeated products. All amounts use proportional 1-MW accounting and retain failed confirmation trajectories.',
'时长产品通过资格检验后，其运行暴露与接入费用可以分别估值。在 10% 工作参与比例的单次事件情景中，假定每年 25,000 美元的场站费解释了每报价 kW·年 863.26 美元门槛的约 95%（补充表 17）。为区分费用分摊和实际运行后果，我们比较了合格重复产品完整的响应与恢复账本。全部金额按比例折算至 1 MW，并保留确认中的失败轨迹。')
m('M041',
'For the four- and eight-hour products qualified with a zero-miss success criterion, mean additional waiting exposure per four-call series was 16,491 and 24,509 GPU-h×h, respectively (Fig. 6a; Supplementary Table 21). At the illustrative waiting price of US$0.005/GPU-h/h and twelve independent series per year, the no-fixed-fee thresholds were US$183.30 and 330.11 per offered accounting kW-year (Fig. 6b,c). Their capacity difference and waiting exposure explain this conditional comparison; the valuations have not been measured as an operator’s willingness to accept.',
'对于采用零漏期成功判据通过资格检验的四小时与八小时产品，每组四次调用的平均额外等待暴露分别为 16,491 和 24,509 GPU-h×h（图 6a；补充表 21）。采用每 GPU-h 每小时 0.005 美元的示例等待价格，并假设每年十二组独立序列，无固定费用门槛分别为每报价核算 kW·年 183.30 和 330.11 美元（图 6b,c）。容量差异与等待暴露解释了这一条件性比较；这些估值尚不是运营者接受意愿的实测结果。')
m('M042',
'At equal illustrative capacity prices of US$250 per kW-year and zero site fee, the four-hour product’s fifth-percentile annual net value was US$1,932, compared with −US$1,832 for eight hours. Conditional on participation, equal value requires an eight-hour price of 1.267 times the four-hour price plus US$97.93 per kW-year; the full boundary also requires non-negative net value (Fig. 6d). The coefficient is the ratio of the selected capacities. When waiting has no incremental price, the equal-price ranking reverses below approximately US$25.57 per kW-year (Supplementary Fig. 5). A shared fee can change whether either option beats non-participation, but a common fee cancels between participating products.',
'在两种产品容量价格同为每 kW·年 250 美元、且场站费为零的示例下，四小时产品年度净值的第五百分位为 1,932 美元，八小时为 −1,832 美元。以参与为条件，两者价值相等要求八小时价格等于四小时价格的 1.267 倍，再加每 kW·年 97.93 美元；完整边界还要求净值非负（图 6d）。该系数等于所选容量之比。当等待没有增量价格时，相同价格下的排序在约每 kW·年 25.57 美元以下反转（补充图 5）。共享费用可以改变任一选择是否优于不参与，但共同费用在参与产品之间比较时抵消。')
m('M046',
'The main finding is a failure of commitment transfer that a submission-count test did not reveal. Matching weekly work totals was insufficient when task resource-time exposed low-supply hours. Permuting hourly blocks improved delivery but left a substantial gap to count-weighted profiles. The comparison therefore separates the choice of workload weights from hourly order and alignment, while leaving their joint effect explicit. It identifies a concrete decision error: accepting a request on the basis of a simplified workload replay whose reducible-power supply does not represent the workload to which the commitment will apply. This connects production workload characterisation<sup>20,28</sup> to the operational commitment question raised by field demonstrations<sup>3</sup> and scheduling studies.<sup>5–19</sup>',
'主要发现是提交次数测试未能揭示的承诺迁移失败。当任务资源时间暴露出供给低谷时，每周工作总量匹配仍不足以确保交付。置乱小时块改善了交付，但与次数加权曲线相比仍存在明显差距。因此，这一比较区分了工作量权重选择与小时顺序及对齐，同时明确保留两者的共同影响。它识别一种具体决策错误：依据简化工作负载重放接受请求，而该重放中的可削功率供给并不能代表承诺实际适用的工作负载。这将生产工作负载表征<sup>20,28</sup>与现场演示<sup>3</sup>及调度研究<sup>5–19</sup>提出的运行承诺问题联系起来。')
m('M047',
'The diagnosis also determines what can usefully change. An instantaneous deficit rules out successful delivery in the affected hour. If that condition passes, strict task-window infeasibility and a feasible PI schedule with causal failure require different responses: revise operating terms in the first case, investigate control and information limits in the second. These scenario-level findings must then be assessed through the declared probabilistic qualification rule. More GPUs, a stricter service label or a low estimated price cannot substitute for that sequence of evidence.',
'诊断还决定哪些调整有意义。即时缺口排除了受影响小时成功交付的可能。若通过这一条件，严格任务时间窗不可行与 PI 可行但因果控制失败需要不同处理：前者需要修改运行条款，后者值得调查控制与信息限制。随后，这些情景层面的发现仍须通过声明的概率性资格规则进行评估。更多 GPU、更严格的服务标签或较低的估计价格，都不能替代这一证据顺序。')
m('M049',
'Economic assessment follows qualification and exposes quantities before assigning prices. Waiting and missed-work exposure remain inspectable independently of their valuations. The preferred duration can change when waiting is free, whereas a common access fee affects entry rather than the ranking of participating products. Comparing annual net values with non-participation avoids confusing a low unit-cost threshold with the most valuable contract. The capacity ratio and stated valuations determine the price boundary, whose use remains conditional on the workload for which delivery was qualified.',
'经济评估在资格检验之后开展，并先展示数量再赋予价格。等待与漏期工作暴露可以独立于估值检查。当等待免费时，偏好的时长可以改变；共同接入费则影响是否进入，而不改变参与产品间的排序。将年度净值与不参与比较，可以避免把较低单位成本门槛误当成最有价值的合同。容量比和指定估值决定价格边界，而这一边界仍只适用于已取得交付资格的工作负载。')
m('M051',
'The evidence is conditional on hourly divisible work, synthetic deadlines and permissions, a fixed rigid-load proxy and a small board-power calibration. Observed task resource-time preserves submitted workload-size heterogeneity but is not sensor-measured GPU activity or application pause–checkpoint–restart validation. Hour permutation changes temporal dependence and alignment with calls and community demand together. Eight observed weeks with ten synthetic realisations each are not 80 independent production weeks. Relaxed-PI tolerance statistics do not guarantee work-group feasibility; exact-window diagnostics establish scenario-level possibilities and impossibilities, not causal capacity. Qualification bounds are pointwise, candidate grids are finite and annual accounts combine independent series. These conditions delimit the commitment and price comparisons.',
'这些证据以小时级可分割工作、合成期限与许可、固定刚性负荷代理和小规模板卡功率校准为条件。观测任务资源时间保留了提交工作规模的异质性，但不等于传感器实测 GPU 活动，也不是应用暂停—检查点—恢复验证。小时置乱同时改变时间依赖及其与调用和社区需求的对齐。八个观察周各十次合成实现不等于八十个独立生产周。放松 PI 容忍统计量不保证工作组可行；严格时间窗诊断确立的是情景层面的可能与不可能，而非因果容量。资格概率界为逐项结果，候选网格有限，年度账本组合独立序列。这些条件界定了承诺与价格比较的适用范围。')

m('M155',
'**a,** Independently confirmed offers at 10% eligibility, 65% offered utilisation, reference deadlines, 10% GPU allocation and four calls at 16-h start spacing. Points and lower whiskers are success fractions and one-sided 95% Wilson lower bounds (300 scenarios); capacity labels apply to both service standards. Zero missed work defines a successful series under the zero-miss criterion; qualification targets a 95% success probability. **b,** Zero-miss diagnoses at 5.90 kW for three prespecified seeds per configuration. Categories separate instantaneous shortage, other strict-window infeasibility, PI feasibility with causal failure and feasibility with causal success; these are mechanism cases, not population frequencies. **c,** Matched submission-count and task-resource-time tests at 2.95 kW in chronological and permuted hourly order, scored at both service standards. **d,** Chronological zero-miss success by observed week for both weights. Panels c,d include eight observed weeks and ten synthetic realisations per week; pooled counts are descriptive and have no binomial confidence bars. Each comparison preserves weekly class totals and uses matched service rules, community and event clocks. Permutation changes hourly order and alignment together. All no-response baselines pass zero-miss service; all 49 chronological resource-time failures encounter instantaneous shortage.',
'**a，** 在 10% 工作允许参与、65% 工作供给利用率、参考期限、10% GPU 分配及四次调用开始间隔 16 h 条件下，独立确认的报价。点和下须为成功比例与单侧 95% Wilson 下界（300 个情景）；容量标签适用于两种服务标准。零漏期判据规定一次成功序列不得有漏期工作；资格检验的整体成功概率目标为 95%。**b，** 每个配置三个预先指定种子在 5.90 kW 下的零漏期诊断。类别区分即时不足、其他严格时间窗不可行、PI 可行但因果控制失败，以及 PI 可行且因果控制成功；这些是机制案例，不是总体频率。**c，** 固定 2.95 kW 的配对次数和任务资源时间测试，分别采用原序与置乱小时顺序，并按两种服务标准评分。**d，** 两种权重在原序下逐观察周的零漏期成功数。c,d 包括八个观察周、每周十次合成实现；合并计数为描述性结果，不绘制二项置信条。各比较保留类别周工作总量并匹配服务规则、社区及事件时刻。置乱同时改变小时顺序和对齐。全部无响应基线通过零漏期服务；原序资源时间的全部 49 次失败均遇到即时不足。')
m('M156','### Figure 4 | Supply margins and the decisions behind a commitment','### 图 4 | 供给余量与承诺背后的决策')
m('M157',
'**a,** Paired minimum event-hour supply margins for all 80 task-resource-time realisations at 2.95 kW, comparing chronological and permuted orders. Margin is baseline PCC power minus community and fixed data-centre power minus 95% of the request, minimised over all four calls. Dashed zero lines separate scenarios with and without an instantaneous shortage; counts are descriptive, with no population-frequency inference. **b,** Available baseline reduction under chronological count and resource-time weighting for the lowest protocol seed (990000). The horizontal line is the 95% delivery requirement and shading marks the four calls. The displayed arrival horizon is 168 h; all 216 h remain in the data. Selection is by seed, not outcome. **c,** Evidence-to-decision sequence. A deficit identifies an impossible series, not automatic rejection of a probabilistic contract. Strict-window PI diagnoses distinguish infeasibility from a causal-control gap; an unresolved solve supplies no feasibility conclusion. Only a fixed causal offer that passes independent qualification enters the operating-price comparison. No supply screen or PI witness alone certifies causal reliability.',
'**a，** 固定 2.95 kW，全部 80 个任务资源时间实现的配对事件小时最小供给余量，比较原序与置乱。余量定义为基线 PCC 功率减去社区功率、固定数据中心功率及请求的 95%，再对全部四次调用取最小值。零虚线区分是否出现即时不足；计数为描述性结果，不推断总体频率。**b，** 最低协议种子 990000 在原序次数和资源时间权重下的基线可削功率。横线为 95% 交付要求，阴影表示四次调用。图示为 168 h 到达时域，全部 216 h 仍在数据中。按种子编号而非结果选取。**c，** 从证据到决策的顺序。缺口识别不可能成功的序列，并不自动拒绝概率性合同。严格时间窗 PI 诊断区分不可行与因果控制差距；未解决的求解不提供可行性结论。只有固定因果报价通过独立资格检验后，才进入运行价格比较。供给检查或 PI 见证本身均不能认证因果可靠性。')
m('M159',
'**a,b,** Four- and eight-hour relaxed-PI tolerance statistics across flexible GPU allocations or unmeasured rigid-class active-power proxies, retaining 10% eligibility, the same 576-GPU installation and paired jobs. Each statistic uses 100 confirmation scenarios and aggregate release/deadline constraints; it does not guarantee work-group-feasible capacity. Lines join evaluated settings. **c,d,** Conditional four-hour single-event participation costs at the unchanged primary offer, using all 300 confirmation ledgers, 50 independent calls per annual draw and proportional 1-MW accounting. Crosses would indicate an unqualified offer. Costs are 95th-percentile annual-net-cost thresholds, not confidence limits. Fixed-request success and PV allocation controls appear in Supplementary Fig. 4c,d. Rigid power proxies are not measurements of online inference.',
'**a,b，** 四小时和八小时放松 PI 容忍统计量随灵活 GPU 分配或未测刚性类别活动功率代理的变化，保留 10% 工作允许参与、相同 576 块 GPU 与配对作业。每项统计量采用 100 个确认情景和累计释放／期限约束，不保证工作组可行容量。线连接已测试设定。**c,d，** 不变主要报价下的四小时单次事件条件参与成本，使用全部 300 条确认账本、每次年度抽样 50 个独立调用，并按比例折算至 1 MW。叉号表示未合格报价。成本是年度净成本第 95 百分位门槛，不是置信界。固定请求成功与光伏分配对照见补充图 4c,d。刚性功率代理不是在线推理测量值。')

s('S20_002','## Workload timing limits reliable demand response from AI data centres','## 工作量的时间分布限制人工智能数据中心的可靠需求响应')
s('S20_005',
'Read the commitment evidence in sequence: independent duration qualification (Table 18), matched workload weights and hourly order (Table 20), strict task-window diagnosis (Table 19), and physical operating exposure and conditional prices (Table 21). The remaining tables provide workload assumptions, structural controls and complete design provenance. Source Data retain frozen inputs, every successful and failed trajectory, direct plotting tables and replay code. Supplementary Note 7 distinguishes the historical designs from the reference products used in the main text.',
'按以下顺序阅读承诺证据：独立时长资格检验（表 18）、配对工作量权重与小时顺序（表 20）、严格任务时间窗诊断（表 19），以及物理运行暴露和条件价格（表 21）。其余表提供工作负载假设、结构对照与完整设计溯源。源数据保留冻结输入、每条成功和失败轨迹、直接绘图表与重放代码。补充说明 7 区分历史设计与正文采用的参考产品。')
s('S20_006',
'| Question | Methods | Displays |\n|---|---|---|\n| Work composition and power | 1–3 | Fig. 1; Supplementary Fig. 2; Tables 1–3 |\n| Single-event offers | 4–5 | Fig. 2; Table 4 |\n| Reference repeated offers | 6 | Fig. 3a; Supplementary Fig. 3a,b; Table 18 |\n| Workload weights and hourly order | 6 | Fig. 3c,d; Fig. 4a,b; Table 20 |\n| Supply and strict-window diagnosis | 6 | Fig. 3b; Fig. 4; Table 19 |\n| Structural and call-history controls | 6 | Supplementary Fig. 3c; Tables 5, 10–16 |\n| PV, allocation and power controls | 7–8 | Fig. 5; Supplementary Fig. 4; Tables 6, 8 |\n| Physical exposure and participation | 9 | Fig. 6; Supplementary Fig. 5; Table 21 |\n| Price assumptions and design provenance | 9; Note 7 | Tables 7, 9, 12, 17; Supplementary Fig. 3d |',
'| 问题 | 方法 | 图表 |\n|---|---|---|\n| 工作构成与功率 | 1–3 | 图 1；补充图 2；表 1–3 |\n| 单次事件报价 | 4–5 | 图 2；表 4 |\n| 参考重复报价 | 6 | 图 3a；补充图 3a,b；表 18 |\n| 工作量权重与小时顺序 | 6 | 图 3c,d；图 4a,b；表 20 |\n| 供给与严格时间窗诊断 | 6 | 图 3b；图 4；表 19 |\n| 结构与调用历史对照 | 6 | 补充图 3c；表 5、10–16 |\n| 光伏、分配与功率对照 | 7–8 | 图 5；补充图 4；表 6、8 |\n| 物理暴露与参与 | 9 | 图 6；补充图 5；表 21 |\n| 价格假设与设计溯源 | 9；说明 7 | 表 7、9、12、17；补充图 3d |')
add(INSERT_SI,'S20_020','S25_note7_heading','### 7. Design provenance and interpretation of superseded comparisons','### 7. 设计溯源与被替代比较的解释')
add(INSERT_SI,'S20_020','S25_note7_text',
'Tables 14 and 17 retain the structural study’s coarse-grid selections and prices; Tables 18 and 21 report the locally refined reference products on new development and confirmation seeds. At 4.423682 kW, the zero-miss development count was 98/100 in the former study and 99/100 in the latter, crossing the fixed Wilson selection threshold. The resulting historical 4.42-to-2.95-kW selection change is not evidence of a stable physical capacity penalty. Both standards select 5.603331 and 4.423682 kW for the reference four- and eight-hour products in Table 18; their capacity ratio is 19/15, rather than the coarse-grid ratio of 1.5. The eight-hour selection is at the tested grid ceiling and does not bracket a continuous maximum.',
'表 14、17 保留结构研究的粗网格选择及价格；表 18、21 报告采用新开发与确认种子的局部加密参考产品。在 4.423682 kW 下，前一研究的零漏期开发计数为 98/100，后一研究为 99/100，跨过了固定 Wilson 选择门槛。因此，历史上从 4.42 降至 2.95 kW 的选择变化，不是稳定物理容量惩罚的证据。表 18 中，两种标准均为参考四小时与八小时产品选择 5.603331 和 4.423682 kW，容量比为 19/15，而非粗网格的 1.5。八小时选择位于测试网格上端，并未夹定连续最大值。')
add(INSERT_SI,'S20_020','S25_note7_scores',
'The 986000-series chronological submission-count test is distinct from the 990000-series matched weight/order test. In the former, 4.423682 kW succeeds in 63/80 realisations under either service score, and all 17 failures encounter immediate shortage; 2.949122 kW succeeds in 80/80 under both (Supplementary Fig. 3d; Table 16). Thus, changing the score at a fixed request does not explain the difference between those requests. The matched 990000-series results in Table 20 compare weights and hourly order without pooling either series or selecting an external offer. The cumulative PI model retained in Figs. 2 and 5 and Tables 4 and 8 is a relaxation for crossing job windows (Note 2), whereas the strict-window diagnoses in Table 19 use work-group execution edges. This distinction does not alter the independent causal queue trajectories or the separate edge-based PV optimiser.',
'986000 系列的原序提交次数测试，与 990000 系列的配对权重／顺序测试不同。前者在 4.423682 kW 下按任一服务评分均成功 63/80，全部 17 次失败遇到即时不足；2.949122 kW 按两种评分均成功 80/80（补充图 3d；表 16）。因此，固定请求后改变评分，不能解释两个请求之间的差异。表 20 的 990000 配对结果比较权重和小时顺序，既不合并两个系列，也不选择外部报价。图 2、5 和表 4、8 保留的累计 PI 模型，在作业时间窗交叉时属于放松（说明 2）；表 19 的严格时间窗诊断则采用工作组执行边。这一区别不改变独立因果队列轨迹，也不改变采用独立执行边的光伏优化器。')

s('S20_062',
'**a,b,** Development one-sided 95% Wilson lower bounds for every four- and eight-hour local candidate (100 scenarios each, both service standards). The dashed line is the selection threshold of 0.95; the selected eight-hour grid ceiling is not a bracketed maximum. **c,** Full-request structural controls show instantaneous shortages and >1% deadline failures as potentially overlapping categories (300 scenarios). **d,** Chronological submission-count cross-scoring from the 986000-series study: stacked segments show successes and immediate shortages at 4.42 kW, and markers show 2.95-kW successes. Both service scores coincide at each request. Eight observed weeks have ten synthetic realisations each; counts are descriptive. Historical design interpretation is in Note 7; matched last-call outcomes, all of which coincide, remain in Table 15 and Source Data.',
'**a,b，** 每个四小时与八小时局部候选的开发单侧 95% Wilson 下界（各 100 个情景，两种服务标准）。虚线为 0.95 选择门槛；选中的八小时网格上端不代表夹定最大值。**c，** 全额请求结构对照中的即时不足与超过 1% 的期限违约，为可能重叠的类别（300 个情景）。**d，** 986000 系列研究的原序提交次数交叉评分：堆叠部分为 4.42 kW 的成功与即时不足，标记为 2.95 kW 成功数。每个请求的两种服务评分重合。八个观察周各有十次合成实现，计数为描述性结果。历史设计解释见说明 7；全部重合的末次调用配对结果保留在表 15 与源数据。')
s('S20_063','### Supplementary Figure 4 | PV benefits and fixed-request controls','### 补充图 4 | 光伏收益与固定请求对照')
s('S20_065',
'**a,** Flexible minus rigid all-scenario PV hosting capacity across the five eligibility scenarios, with and without BESS; each capacity is the minimum over 100 scenarios. **b,** Paired gain in utilisation of a fixed 500-kW PV system; points are means and whiskers are 95% paired bootstrap intervals. The intervals cover sampling, not optimisation error; small storage contrasts remain unresolved at solver precision. **c,** Four- and eight-hour success at unchanged primary single-event requests across allocation and rigid-power controls, with one-sided 95% Wilson lower bounds from 300 scenarios. **d,** Corresponding gains in all-scenario PV hosting over 100 paired scenarios. Panels c,d retain 10% eligibility and vary only GPU allocation or the stated rigid-power proxy. PV schedules use full information and zero missed work; hosting differences are differences of minima, not mean effects or confidence intervals.',
'**a，** 五档工作参与比例下，有无储能时灵活运行减刚性运行的全情景光伏接纳容量；各容量为 100 个情景中的最小值。**b，** 固定 500 kW 光伏系统利用率的配对增益；点为均值，须为 95% 配对自助法区间。区间涵盖抽样而非优化误差；微小储能差异在求解精度下仍未分辨。**c，** 分配与刚性功率对照在不变主要单次报价下的四小时与八小时成功情况，附 300 个情景的单侧 95% Wilson 下界。**d，** 相应的全情景光伏接纳增益，采用 100 个配对情景。c,d 保持 10% 工作参与，仅改变 GPU 分配或声明的刚性功率代理。光伏调度使用完整信息且零漏期；接纳差异是两个最小值之差，不是均值效应或置信区间。')

m('M077','### Relaxed planning and independent qualification','### 放松规划与独立资格检验')
s('S20_078','### Supplementary Table 4 | Relaxed planning statistics and independent single-event qualification','### 补充表 4 | 放松规划统计量与独立单次事件资格检验')
previous_note=next(b for b in json.loads((HERE/'before/supplement_aligned_blocks.json').read_text())['blocks'] if b['id']=='S23_T16_note')
s('S23_T16_note',previous_note['en'].replace('Fig. 3c displays the primary pair','Supplementary Fig. 3d displays the chronological primary requests'),previous_note['zh'].replace('图 3c 展示主要配对','补充图 3d 展示原序主要请求的对照'))
MAIN['M030']=(MAIN['M030'][0].replace('A non-negative margin is necessary but insufficient:', 'The paired changes included both removal and creation of shortages. A non-negative margin is necessary but insufficient:'), MAIN['M030'][1].replace('非负余量只是必要条件', '配对变化既包括消除缺口，也包括产生新的缺口。非负余量只是必要条件'))
MAIN['M155']=(MAIN['M155'][0].replace('scored at both service standards.', 'scored at both service standards. GPU-h labels denote task-resource-time weights.'), MAIN['M155'][1].replace('并按两种服务标准评分。','并按两种服务标准评分。GPU-h 标签表示任务资源时间权重。'))

def main():
    changes=[];report={};(READER/'sources').mkdir(parents=True,exist_ok=True)
    for stem,name,replacements,inserts in [('main','nature_communications_article.md',MAIN,INSERT_MAIN),('supplement','supplementary_information.md',SI,INSERT_SI)]:
        original=json.loads((HERE/'before'/f'{stem}_aligned_blocks.json').read_text())
        assert original['source_sha256']==h.sha(HERE/'before'/name)
        rows=[]
        for old in original['blocks']:
            if stem=='main' and old['id'] in REMOVE:
                changes.append(dict(id=old['id'],action='compressed_or_relocated',before=old));continue
            row=dict(old)
            if row['id'] in replacements:row['en'],row['zh']=replacements[row['id']]
            for lang in ['en','zh']:row[lang]=row[lang].replace('docs/figures/commitment_mechanisms_v1/artwork/','docs/figures/commitment_narrative_v1/artwork/')
            # Notes 7 must precede the Methods section, rather than nest inside it.
            if stem=='supplement' and row['id']=='S20_020':rows.extend(inserts.get(row['id'],[]))
            if row['id']=='M161':
                row['en']=row['en'].replace('All panels use zero-loss-qualified products of','All panels use products qualified at a 95% success-probability target with zero missed work required for success:').replace('reference deadlines and 16-h start spacing.','reference deadlines and 16-h start spacing. Failed series remain in the ledgers.')
                row['zh']=row['zh'].replace('全部面板采用零损失资格产品','全部面板采用以 95% 成功概率为目标、且成功序列要求零漏期的合格产品').replace('使用参考期限及 16 h 开始间隔。','使用参考期限及 16 h 开始间隔。失败序列仍保留在账本内。')
            if row['id'] in ['M078','S20_011']:
                row['en']=row['en'].replace('The earlier PI programme','The aggregate PI programme').replace('The new feasibility diagnostics below','The strict-window feasibility diagnostics')
                row['zh']=row['zh'].replace('早期 PI','累计 PI').replace('下文新增可行性诊断','严格时间窗可行性诊断')
            if row!=old:changes.append(dict(id=row['id'],before=old,after=row))
            rows.append(row)
            if not(stem=='supplement' and row['id']=='S20_020'):rows.extend(inserts.get(row['id'],[]))
        assert len(rows)==len({r['id'] for r in rows})
        head=f'<!--\nWorking {stem}, version 0.25, 2026-09-10.\nWorkload weighting, hourly order and commitment decisions. Existing frozen experiments.\nAuthor metadata remain pending.\n-->\n\n'
        doc=head+'\n\n'.join(r['en'] for r in rows)+'\n';target=ROOT/'manuscript'/name;target.write_text(doc)
        (READER/'sources'/f'{stem}_original.md').write_text(doc)
        note='本稿逐段对应英文正文与补充材料 v0.25（2026-09-10）。现有证据按工作量权重、小时顺序与承诺决策重新组织；未新增模拟或重新选择报价。\n\n'
        cn=[];both=[]
        for row in rows:
            en,zh=h.reader_format(row['en']),h.reader_format(row['zh']);cn.append(zh)
            both.extend([zh] if en.startswith(('![','$$')) else [f'<!-- {row["id"]} -->\n{en}',zh])
        for suffix,parts in [('zh',cn),('bilingual',both)]:(READER/f'{stem}_{suffix}.md').write_text(note+'\n\n'.join(parts)+'\n')
        (READER/f'{stem}_aligned_blocks.json').write_text(json.dumps(dict(source_sha256=h.sha(target),blocks=rows),ensure_ascii=False,indent=2)+'\n')
        wc=lambda t:len(re.findall(r"\b[\w]+(?:[-’'][\w]+)*\b",t))
        info=dict(blocks=len(rows),source_sha256=h.sha(target),words=wc(doc))
        if stem=='main':
            old=(HERE/'before'/name).read_text();info['abstract_words']=wc(MAIN['M006'][0]);info['results_words']=wc(doc.split('## Results\n')[1].split('## Discussion\n')[0]);info['previous_results_words']=wc(old.split('## Results\n')[1].split('## Discussion\n')[0])
            info['subsection_words']=[dict(title=x.splitlines()[0],words=wc(x)) for x in re.split(r'(?m)(?=^### )',doc.split('## Results\n')[1].split('## Discussion\n')[0]) if x.strip()]
        report[stem]=info
    (READER/'README.md').write_text('# 中文阅读稿 v19\n\n对应英文正文与补充材料 v0.25。\n\n- [正文中文](main_zh.md)\n- [补充材料中文](supplement_zh.md)\n- [正文中英对照](main_bilingual.md)\n- [补充中英对照](supplement_bilingual.md)\n')
    (HERE/'text_changes.json').write_text(json.dumps(changes,ensure_ascii=False,indent=2)+'\n')
    (HERE/'revision_validation.json').write_text(json.dumps(report,indent=2)+'\n');print(json.dumps(report,indent=2))

if __name__=='__main__':main()
