algorithm: dqn
environment_config: configs/env/hourly_discrete_train.yaml
total_timesteps: 50000
n_envs: 1
policy: MlpPolicy
hyperparameters:
  learning_rate: 0.0001
  buffer_size: 50000
  learning_starts: 1000
  batch_size: 128
  gamma: 0.995
  train_freq: 4
