algorithm: ppo
environment_config: configs/env/hourly_continuous_train.yaml
total_timesteps: 100000
n_envs: 4
policy: MlpPolicy
hyperparameters:
  learning_rate: 0.0003
  n_steps: 192
  batch_size: 256
  n_epochs: 10
  gamma: 0.995
  gae_lambda: 0.95
