"""Replace the argument from frozen v0.23 blocks, retaining English/Chinese alignment."""
import importlib.util,json,re
from pathlib import Path
import pandas as pd
HERE=Path(__file__).resolve().parent;ROOT=HERE.parents[2];SOURCE=ROOT/'manuscript/source_data/nature_commitment_mechanisms_v1';READER=ROOT/'docs/chinese_reader/v18'
spec=importlib.util.spec_from_file_location('text_helpers',HERE.parent/'workload_composition_2026-09-09/integrate_content.py');h=importlib.util.module_from_spec(spec);spec.loader.exec_module(h)
MAIN={};SI={};IM={};IS={};REMOVE={'M026'}
def m(i,en,zh):MAIN[i]=(en,zh)
def s(i,en,zh):SI[i]=(en,zh)
def add(dest,after,i,en,zh):dest.setdefault(after,[]).append(dict(id=i,en=en,zh=zh))

m('M001','# Workload timing limits reliable demand response from AI data centres','# 工作量的时间分布限制人工智能数据中心的可靠需求响应')

m('M006',
'Artificial-intelligence data centres could help electricity grids accommodate growing demand by postponing computing, provided that response commitments preserve service. Here we connect workload permissions to independently tested offers, workload-timing limits and participation costs. A production resource-time audit informs scenarios with 5–20% of work eligible, supporting single-event offers of 2.95–11.80 kW at modelled operating peaks of 190–200 kW. At 10% eligibility, locally refined four- and eight-hour repeated offers of 5.60 and 4.42 kW qualify under a zero-deadline-loss standard. Same-scenario feasibility tests distinguish immediate power shortage, deadline constraints and a gap between causal control and perfect-information scheduling. Crucially, an offer that transfers under submission-count profiles can fail when observed task resource-time weights are restored: a fixed 2.95-kW request succeeds in 80/80 count-weighted but only 31/80 resource-time-weighted realisations across eight production weeks, despite service-feasible no-response baselines. Operating ledgers then identify conditional compensation boundaries between qualified duration products. These findings show why operators must validate the temporal supply of reducible power, alongside task service and recovery obligations, before transferring a model-qualified commitment to another workload.',
'人工智能数据中心可以通过推迟计算，帮助电网应对不断增长的需求，前提是响应承诺能够维持计算服务。本文将工作参与许可与独立检验的报价、工作时序限制和参与成本联系起来。生产资源时间审计为 5%–20% 工作可参与的情景提供依据；在约 190–200 kW 的模型运行峰值下，单次事件合格报价为 2.95–11.80 kW。当工作参与比例为 10% 时，局部加密后的四小时和八小时重复报价分别为 5.60 和 4.42 kW，均通过零期限违约标准的资格检验。同场景可行性对照区分了即时功率不足、期限约束，以及因果控制与完美信息调度之间的差距。关键在于，能够适用于提交次数曲线的报价，在恢复真实任务资源时间权重后可能失败：对八个生产周，固定 2.95 kW 请求在次数加权下成功 80/80，而在资源时间加权下仅为 31/80，尽管无响应基线全部满足服务要求。随后，运行账本给出合格时长产品之间的条件性补偿边界。这些发现说明，将模型内合格的承诺用于另一种工作负载前，运营者需要同时核验可削功率的时间分布、任务服务与恢复义务。')
m('M012',
'Here we examine how an operator should choose a response commitment when eligible work, task timing and recovery obligations impose different limits. A production execution audit informs 5%, 10% and 20% work-permission scenarios; larger comparisons make the additional business assumptions explicit. AIDRBench combines trace-informed jobs, four-GPU board-power measurements and a modelled community electricity system. We independently test causal-controller offers, refine the reference duration products and use same-scenario perfect-information feasibility checks to interpret failures. Matched tests across eight observed production weeks then separate submission counts from submitted task resource-time.<sup>28</sup> Complete operating ledgers expose the waiting and service-loss quantities behind conditional compensation. Together, these comparisons identify when to revise the controller, reconsider task permissions or withhold a commitment from a changed workload.',
'本文研究：当可参与工作、任务时序和恢复义务施加不同限制时，运营者应如何选择响应承诺。生产执行数据审计为 5%、10% 和 20% 工作许可情景提供依据，更高比例的对照则明确其额外业务假设。AIDRBench 结合受轨迹约束的作业、四块 GPU 的板卡功率测量与社区电力系统模型。我们独立检验因果控制器的报价，加密参考时长产品，并通过同场景完美信息可行性对照解释失败。随后，八个实际生产周的配对测试区分提交次数与提交任务的资源时间。<sup>28</sup> 完整运行账本展示条件性补偿背后的等待与服务损失量。共同来看，这些对照帮助区分何时应改进控制器、重新考虑任务许可，或暂缓将承诺用于改变后的工作负载。')
m('M025','### Workload timing determines whether a repeated commitment transfers','### 工作量的时间分布决定重复承诺能否适用')
m('M027',
'We held work eligibility at 10% and tested four calls with a controller that enforces every overlapping recovery obligation. In the reference configuration—65% offered utilisation, reference deadlines and a 10% GPU pool—local refinement at 0.295-kW steps selected 5.60 kW for four-hour calls and 4.42 kW for eight-hour calls, both with 16-h start spacing. Under zero missed work, independent confirmation gave 297/300 and 296/300 successes, with one-sided 95% probability lower bounds of 0.9752 and 0.9706 (Fig. 3a). The 1% and zero-loss endpoints selected the same capacities. The earlier coarse-grid difference between those standards was therefore not a stable reference-capacity penalty (Supplementary Tables 14 and 18).',
'我们固定 10% 工作可参与，使用落实每项重叠恢复义务的控制器测试四次调用。在参考配置下，即工作供给利用率 65%、参考期限与 10% GPU 池，按约 0.295 kW 的步长局部加密后，四小时和八小时调用分别选择 5.60 和 4.42 kW，开始间隔均为 16 h。按零漏期工作标准，独立确认分别成功 297/300 和 296/300，单侧 95% 概率下界为 0.9752 和 0.9706（图 3a）。1% 与零损失终点选择了相同容量。因此，早期粗网格中两种标准的差别不能作为稳定的参考容量惩罚（补充表 14、18）。')
m('M023_limits',
'Failure diagnosis required a separate feasibility test. At the unchanged 5.90-kW request, selected same-scenario comparisons revealed three distinct limits (Fig. 3b; Supplementary Table 19). Some baseline hours contained too little flexible power to supply 95% of the request even with all flexible execution stopped. In a reference scenario that passed this necessary condition, the causal controller failed but a full-information schedule met every electrical obligation with zero missed work. Halving that scenario’s deadline slack made the request infeasible under the same delivery and recovery criteria; doubling GPU allocation did not restore feasibility. The broader structural tests also retained an unchanged electrical outcome for the last call when earlier calls were removed at a matched clock time (Supplementary Fig. 3; Supplementary Table 15). Thus, neither a controller failure nor a repeated-call failure alone identifies the underlying capacity limit.',
'解释失败需要单独检验可行性。在保持 5.90 kW 请求不变的同场景对照中，我们辨明三种不同限制（图 3b；补充表 19）。一些基线小时中的灵活功率过少，即使全部停止灵活执行，也无法交付请求的 95%。在通过这一必要条件的一个参考场景中，因果控制器失败，但完整未来信息下存在满足全部电力义务且零漏期的调度。将同一场景的期限余量减半后，在相同交付与恢复判据下请求变为不可行；GPU 分配加倍也未恢复可行性。更广泛的结构检验还保留了一个结果：在对齐时刻后，去掉先前调用并不改变末次调用的电力结果（补充图 3；补充表 15）。因此，仅凭控制器失败或重复调用失败，都不能判定其背后的容量限制。')
m('M023_timing',
'The timing tests locate a further transfer limit. In the earlier eight-week submission-count test, the 4.42-kW request succeeded in 63/80 chronological realisations under either the 1% or zero-loss score; every one of its 17 failures triggered immediate supply shortage. At 2.95 kW, both scores gave 80/80 (Fig. 3c). In a new matched test, replacing hourly job counts with observed task resource-time weights reduced success at the unchanged 2.95-kW request from 80/80 to 31/80; the remaining 49 realisations all encountered immediate shortage. At 4.42 kW, every resource-time-weighted chronological realisation encountered shortage and failed, whereas count weighting gave 61/80 successes at 1% and 60/80 at zero loss (Fig. 3d). All no-response baselines met the zero-loss service criterion. These comparisons held weekly work totals fixed: temporal concentration and low-supply hours, rather than total eligible work or an infeasible baseline, prevented transfer (Supplementary Table 20).',
'时序测试揭示了进一步的适用边界。在早期八周提交次数测试中，4.42 kW 请求在原序下按 1% 或零损失评分均成功 63/80，其余 17 次失败全部触及即时供给不足；2.95 kW 在两种评分下均为 80/80（图 3c）。在新的配对测试中，将逐小时任务次数替换为实际任务资源时间权重后，同一个 2.95 kW 请求的成功数从 80/80 降至 31/80，其余 49 次全部出现即时不足。4.42 kW 在资源时间加权的全部原序实现中均触及不足并失败，而次数加权下按 1% 和零损失分别成功 61/80、60/80（图 3d）。所有无响应基线均满足零损失服务标准。这些比较保持各周工作总量不变：阻止结果适用的是时间上的集中与供给低谷，而非总可参与工作量或本身不可行的基线（补充表 20）。')
m('M041',
'For the locally refined zero-loss products, mean additional waiting exposure per four-call series was 16,491 GPU-h×h for four-hour calls and 24,509 GPU-h×h for eight-hour calls (Fig. 6a; Supplementary Table 21). These are quantities to be valued by the operator. At the illustrative waiting price of US$0.005/GPU-h/h and twelve independent series per year, the no-fixed-fee thresholds were US$183.30 and 330.11 per offered accounting kW-year, respectively (Fig. 6b,c). Their capacity difference and waiting exposure explain the conditional cost comparison; neither has been measured as an operator’s willingness to accept.',
'对局部加密后的零损失产品，每组四次调用的平均额外等待暴露，四小时产品为 16,491 GPU-h×h，八小时产品为 24,509 GPU-h×h（图 6a；补充表 21）。这些是需要运营者定价的运行量。在示例等待价格每 GPU-h 每小时 0.005 美元、每年十二组独立序列下，无固定费补偿门槛分别为每报价核算 kW 每年 183.30 和 330.11 美元（图 6b,c）。所选容量的差别与等待暴露解释了这一条件性成本比较；两者均未被测量为运营者的实际接受意愿。')
m('M040',
'Access and operating costs answer different participation questions. In the original 10% eligibility, four-hour single-event case, US$819.90 of the US$863.26 per offered kW-year threshold came from the assumed US$25,000 annual site fee—about 95% (Supplementary Table 17). That low-eligibility unit-cost penalty was primarily fee allocation. We therefore compared the complete response-and-recovery ledgers of the newly qualified duration products separately from access charges. All amounts use a proportional 1-MW accounting scale and retain failed confirmation trajectories.',
'接入成本与运行成本回答不同的参与问题。在原有 10% 工作可参与、四小时单次事件情景中，每报价 kW 每年 863.26 美元的门槛，有 819.90 美元来自假定的每年 25,000 美元场站费用，约占 95%（补充表 17）。这一低参与比例下的单位成本惩罚主要由费用分摊造成。因此，我们将新合格时长产品的完整响应与恢复账本同接入费用分开比较。全部金额按比例折算至 1 MW 核算规模，且保留确认中的失败轨迹。')
m('M042',
'At equal illustrative capacity prices of US$250 per kW-year and zero site fee, the four-hour product’s fifth-percentile annual net value was US$1,932, compared with −US$1,832 for eight hours. For the eight-hour product to match the four-hour product conditional on participation, its price must exceed 1.267 times the four-hour price plus US$97.93 per kW-year; the full boundary also requires non-negative net value (Fig. 6d). The coefficient follows the refined capacity ratio, replacing the coarse-grid value of 1.5. When waiting has no incremental price, the equal-price ranking reverses below approximately US$25.57 per kW-year (Supplementary Fig. 5). A shared fee can change whether either option beats non-participation, but a common fee cancels between participating products.',
'在两种产品容量价格均为每 kW 每年 250 美元、且没有场站费的示例下，四小时产品的年度净值第五百分位为 1,932 美元，八小时为 −1,832 美元。若比较两种参与方案，八小时产品价格须超过四小时价格的 1.267 倍再加每 kW 每年 97.93 美元，才能优于四小时；完整边界还要求净值非负（图 6d）。该系数来自加密后的所选容量比，替代粗网格中的 1.5。当等待没有增量价格时，等价支付下的产品排序在约每 kW 每年 25.57 美元以下反转（补充图 5）。共享费用可以改变某种产品是否优于不参与，但两个参与产品承担的共同费用在相互比较时抵消。')
m('M043',
'The economic result is a price-dependent choice among services qualified for the reference scenario distribution. The failed resource-time transfer prevents treating those prices as offers for the observed-week workload. Waiting and missed-work valuations are varied explicitly; contract penalties, application checkpoint costs and actual hardware ageing remain unpriced. Independent annual series provide a conditional accounting screen, rather than a continuous-year operating forecast.',
'经济性结果是在参考情景分布中合格的服务之间，随价格变化而改变的选择。资源时间测试中的适用失败，使这些价格不能直接作为所观察周工作负载的参与报价。等待和漏期估值均被明确改变；合同违约罚款、应用检查点成本与实际硬件老化仍未定价。独立年度序列提供条件性核算筛选，并非全年连续运行预测。')
m('M046',
'The main operational finding is that preserving how often jobs arrive can still overstate the transferability of a grid commitment. At unchanged weekly eligible work, a 2.95-kW request passed every chronological submission-count realisation but failed in 49 of 80 matched resource-time-weighted realisations. Each failed realisation contained an hour in which the baseline itself offered too little reducible power. This identifies a concrete decision error: accepting a contract because it passed a count-based workload test, despite inadequate power in the workload’s low-supply hours. The result connects production workload characterisation<sup>20,28</sup> to the commitment question raised by field demonstrations<sup>3</sup> and scheduling studies.<sup>5–19</sup>',
'最主要的运行发现是：即便保留作业到达次数，仍可能高估电网承诺的适用性。保持各周可参与工作总量不变时，2.95 kW 请求在所有原序提交次数实现中通过，却在 80 个配对的资源时间加权实现中失败 49 次。每个失败实现都存在一个基线本身无法提供足够可削功率的小时。这识别出一种具体决策错误：仅因合同通过次数驱动的工作负载测试便接受它，尽管实际工作量的供给低谷不足以履约。该结果将生产工作负载描述<sup>20,28</sup>与现场展示<sup>3</sup>及调度研究<sup>5–19</sup>提出的承诺问题联系起来。')
m('M047',
'A failed controller test also requires care in deciding what to change. The same-scenario checks distinguish a necessary instantaneous shortage from a deadline-constrained infeasible programme and from a failure for which a feasible full-information schedule exists. Only the last points directly to unused scheduling or information opportunities; it does not by itself establish a realizable causal policy. Conversely, adding GPU capacity cannot repair a shortage of reducible baseline power and did not restore the tight-deadline diagnostic. Local grid refinement further showed that the earlier reference derating under zero loss was not stable. Commitment choices must therefore rest on independently tested requests and explicit failure mechanisms, rather than a universal penalty assigned to stricter service.',
'面对控制器测试失败，决定改变什么也需要谨慎。同场景核查区分了必要的即时不足、受期限限制而不可行的方案，以及存在完整未来信息可行调度的控制失败。只有最后一种直接指向尚未利用的调度或信息机会；它本身仍不证明存在可实现的因果策略。相反，新增 GPU 容量无法修补基线可削功率不足，也没有恢复紧期限诊断中的可行性。局部网格加密还说明，早期参考情景中零损失导致的降档并不稳定。因此，承诺选择必须依据独立测试的请求与明确的失败机制，而非给更严格服务附加一个普遍容量惩罚。')
m('M048',
'Other system effects remain service-specific. Authorising 5–20% of work supported single-event offers of 2.95–11.80 kW in the reference model, while broader permissions required additional business assumptions. At fixed permission, a larger flexible GPU pool increased PV hosting without increasing the tested demand-response offer. Additional PV capacity and improved use of an existing installation are separate planning benefits,<sup>23–27</sup> just as constant rigid power can cancel in a baseline-relative response while remaining relevant to facility demand and cost scaling.',
'其他系统影响仍取决于具体服务。在参考模型中，授权 5%–20% 工作参与支持 2.95–11.80 kW 的单次事件报价，更宽参与许可需要额外业务假设。在固定工作许可下，更大的灵活 GPU 池提高了光伏接纳量，却没有提高所测需求响应报价。增加光伏装机与改善现有装机利用程度是不同的规划收益；<sup>23–27</sup> 同样，恒定刚性功率虽然在相对基线的响应中抵消，却仍影响设施需求与成本折算。')
m('M049',
'Economic assessment should expose the operating quantities before assigning prices. Waiting and missed-work exposure can be inspected independently of their valuations. The preferred duration can change when waiting is free, while a common access fee affects entry rather than the ranking of two participating services. Comparing annual net values, including non-participation, avoids confusing a small unit-cost threshold with the most valuable contract. The refined capacity ratio changes the tariff boundary as well, so an economic coefficient should not be reported more precisely than the operating choice on which it depends.',
'经济评估应先展示运行量，再赋予价格。等待与漏期暴露可以独立于估值进行检查。当等待免费时，优选时长可能改变；共同接入费用则影响是否进入市场，而非两个参与服务的相对排序。比较包括不参与在内的年度净值，可以避免把较低单位成本门槛误认为最有价值的合同。加密后的容量比也改变了补偿边界，因此经济系数的解释不能比它所依赖的运行选择更精确。')
m('M050',
'For planners and operators, the useful output is a conditional commitment with a declared workload, baseline, service standard, capacity and call arrangement. Its delivery evidence and operating ledger must be re-evaluated when the timing structure changes. This is consistent with capacity assessment for other resources whose decisions are coupled over time.<sup>29,30</sup> A larger nominal flexible share, more recovery hardware or cheaper access cannot substitute for that assessment.',
'对规划者和运营者，有用的输出是明确工作负载、基线、服务标准、容量与调用安排的条件性承诺。当时间结构变化时，交付证据与运行账本需要重新评估。这与其他决策在时间上相互耦合的资源容量评估相一致。<sup>29,30</sup> 更高名义柔性比例、更多恢复硬件或更便宜的接入都不能代替这项评估。')
m('M051',
'The evidence is conditional on hourly divisible work, synthetic deadlines and permissions, a fixed rigid-load proxy and a small board-power calibration. Observed task resource-time preserves submission-weight heterogeneity but is not sensor-measured GPU activity, production deadlines or application pause–checkpoint–restart validation. Eight observed weeks with ten synthetic realisations each are not 80 independent production weeks. The earlier PI statistics are relaxed planning envelopes; the new exact-window feasibility checks establish scenario-level possibilities and impossibilities, not a causal capacity certificate. Qualification bounds are pointwise, candidate grids are finite and annual accounts combine independent series. These limits define where the reported commitment and price comparisons can be used.',
'证据以小时级可分割工作、合成期限与许可、固定刚性负荷代理和小规模板卡功率标定为条件。实际任务资源时间保留提交权重的异质性，但不等于传感器测得的 GPU 忙碌活动、生产期限或应用暂停—检查点—重启验证。八个观察周各十次合成实现，不等于八十个独立生产周。早期 PI 统计量属于放松模型的规划界限；新增严格作业时间窗可行性检验建立的是情景内的可能与不可能，而非因果容量资格。资格概率界为逐项保证，候选网格有限，年度核算组合独立序列。这些限制界定了承诺与价格比较的适用范围。')

m('M078',
'The earlier PI programme maximised R under cumulative class-release and class-deadline constraints. These are necessary aggregate conditions, but are a relaxation when job windows cross: work executed for an earlier, later-deadline job can satisfy a cumulative due-work inequality for a different job. Its retained optima therefore define relaxed planning envelopes, not generally job-feasible capacities. Their second order statistic among 100 scenarios is a 95%/95% tolerance statistic of that relaxed quantity, with achieved confidence 0.96292.<sup>33</sup> It does not guarantee feasible work scheduling. Controller offers instead use completed queue simulations on independent seeds; their joint delivery-and-service probability is assessed by a one-sided 95% Wilson lower bound, required to reach 0.95.<sup>34,35</sup> The new feasibility diagnostics below use each work group’s own release and deadline.',
'早期 PI 程序在累计类别释放量与累计类别到期量约束下最大化 R。这些是必要的汇总条件，但当作业时间窗交叉时构成放松：为一个较早释放、较晚到期的作业完成的工作，可能满足另一个作业的累计到期不等式。因此，保留的最优值给出放松模型的规划界限，并非一般都能满足实际作业时间窗的容量。100 个情景中的第二顺序统计量，是该放松量在 95%/95% 条件下的容忍统计量，实际达到的置信度为 0.96292。<sup>33</sup> 它不保证存在可行作业调度。控制器报价则来自独立种子上的完整队列模拟；交付与服务联合概率用单侧 95% Wilson 下界评价，要求达到 0.95。<sup>34,35</sup> 以下新增可行性诊断使用每个工作组自身的释放时间与期限。')
add(IM,'M023_stats','M024_refinement',
'Local refinement fixed the reference workload and controller and tested fractions 0.50–0.75 for H8P16 and 0.75–1.00 for H4P16, in steps of 0.05 of the unchanged 5.898243186-kW request. H denotes duration and P start spacing. Seeds 988000–988099 supplied development; endpoint-specific selections were frozen before seeds 989000–989299 supplied confirmation. Only selected candidates and prespecified coarse comparators entered confirmation, with no reselection. The grid ceiling for eight hours was selected under both standards, so the test did not bracket a continuous maximum. Earlier seeds were not pooled with these data.',
'局部加密固定参考工作负载与控制器，在原有 5.898243186 kW 请求基础上，H8P16 测试 0.50–0.75，H4P16 测试 0.75–1.00，步长均为 0.05。H 表示时长，P 表示开始间隔。开发使用种子 988000–988099；分终点的选择在确认种子 989000–989299 运行前冻结。确认只检验选中候选与预先指定的粗网格对照，之后不重新选值。两种标准均选中八小时网格上端，因此测试没有夹定连续最大值。早期种子未与本次数据合并。')
add(IM,'M024_refinement','M024_pi_methods',
'Perfect-information diagnostics fixed each request and its four event clocks, baseline and 24-h recovery windows. Non-negative execution variables existed only between each class/release/deadline work group’s own release and deadline; execution, misses and terminal work conserved every group. Constraints retained GPU and PCC limits, 95% hourly and capped-mean delivery, 25% rebound relative to actual peak event reduction, 50% full-window peak relief and the original terminal allowance. Binary peak selectors represented the rebound denominator exactly. HiGHS solved the resulting mixed-integer feasibility problem. Thirty-three prespecified structural cases comprised five configurations, three previously used seeds and two service standards, plus three reference 4.42-kW checks; five affected external weeks supplied an additional first-shortage diagnostic each. These mechanism-selected cases were not prevalence samples. All 11 feasible witnesses passed independent work-group and electrical checks. A 90-s unresolved solve was retained and resolved as infeasible after extending only its time limit to 600 s. Full-information feasibility was not treated as causal realizability.',
'完美信息诊断固定每个请求及其四个事件时刻、基线和 24 h 恢复窗。只有在每个类别—释放时间—期限工作组自身的允许时段内，才建立非负执行变量；执行、漏期及期末工作对每组守恒。约束保留 GPU 与 PCC 限制、95% 逐时及截顶平均交付、相对事件实际峰值减负的 25% 反弹、完整窗口 50% 峰值削减，以及原期末积压容忍度。二进制峰值选择变量精确表示反弹分母，由 HiGHS 求解相应混合整数可行性问题。预先指定的 33 个结构条件包括五种配置、三个已用种子、两个服务标准，以及三个参考 4.42 kW 检查；另从五个受影响的外部周各取首个短缺实现作诊断。这些按机制选择的条件不用于估计发生率。全部 11 个可行见证通过独立工作组与电力约束检查。一次 90 s 未解决的求解保留原记录，仅将时限延长至 600 s 后判为不可行。完美信息可行未被当作因果可实现。')
add(IM,'M024_pi_methods','M024_workload_methods',
'The resource-time transfer test reconstructed each processed job’s GPU-seconds as the sum of requested GPU-equivalents × task launch-to-completion duration across its terminated positive-resource tasks.<sup>28</sup> All 714,903 processed jobs matched the raw task reconstruction; multiplying total requested GPUs by job submission-to-completion time instead differed for 131,379 jobs. The test retained trace hours 168–1511, whose processed time origin is 542,323 s after the raw origin. Within each week, either job counts or submitted task resource-time set hourly weights; each class’s weekly work total was normalised to the reference total. Identical synthetic job classes, deadlines, community traces, event clocks and paired whole-hour permutations were used at each seed (990000 + 100w + r; eight weeks × ten realisations). Fixed 2.95- and 4.42-kW requests gave 640 complete replays. All 320 no-response input variants passed zero-loss service; no failed variant was excluded. Aggregate counts are descriptive. Allocated resource-time is not a sensor measurement of busy GPU time, and the test retains divisible work and synthetic service rules.',
'资源时间适用测试将每个处理后作业的 GPU 秒数，重建为其已完成且资源量为正的各任务之“请求 GPU 当量 × 任务启动至完成时长”之和。<sup>28</sup> 全部 714,903 个处理后作业均与原始任务重建一致；若改用总请求 GPU 数乘以作业提交至完成时长，则有 131,379 个作业不一致。测试保留轨迹小时 168–1511；处理后的时间原点相对原始原点偏移 542,323 s。各周分别采用任务次数或提交任务资源时间作为逐时权重，每个类别的周工作总量归一到参考总量。每个种子使用相同的合成任务类别、期限、社区轨迹、事件时刻及配对完整小时置乱（种子 990000 + 100w + r；八周各十次实现）。固定 2.95 与 4.42 kW 请求共形成 640 次完整重放。全部 320 个无响应输入变体通过零损失服务，无失败变体被排除。合计数为描述性结果。已分配资源时间不等于传感器测得的 GPU 忙碌时间，测试仍保留可分割工作与合成服务规则。')

m('M154','### Figure 3 | Separate qualification, feasibility and workload transfer','### 图 3 | 区分资格检验、可行性与工作负载适用性')
m('M152','### Figure 2 | Relaxed planning statistics and independently tested single offers','### 图 2 | 放松规划统计量与独立检验的单次报价')
m('M155',
'**a,** Locally refined offers at 10% eligibility, 65% offered utilisation, reference deadlines, 10% GPU allocation and four calls at 16-h start spacing. Points and lower whiskers are confirmation success fractions and one-sided 95% Wilson lower bounds (300 new seeds); labels give model capacity. Both service standards selected the same request for each duration. **b,** Zero-loss fixed-request diagnoses for the first three prespecified structural seeds at 5.90 kW. Counts distinguish instantaneous shortage, infeasibility after that necessary condition passes, a feasible PI schedule with causal failure, and feasibility with causal success; these are diagnostic cases, not frequencies in a population. **c,** Earlier eight-week chronological count test, cross-scored under both standards. Stacked segments show successes and instantaneous-shortage failures at 4.42 kW; the 2.95-kW request has 10/10 successes in every week under either score. **d,** New paired chronological count versus resource-time tests at 2.95 kW, with eight observed weeks and ten synthetic realisations per week. Every failure shown for resource-time weighting triggers instantaneous shortage; all baselines are zero-loss feasible. Work totals, synthetic deadline rules, community and event clocks are matched within each comparison. Source Data retain every trial and the prespecified candidate grid.',
'**a，** 在 10% 工作可参与、65% 工作供给利用率、参考期限、10% GPU 分配及四次调用开始间隔 16 h 条件下，局部加密后的报价。点与下须分别为确认成功率及单侧 95% Wilson 下界（300 个新种子）；标签给出模型容量。两种服务标准对每个时长选择相同请求。**b，** 对预先指定的前三个结构种子，在 5.90 kW 固定请求下进行零损失诊断。计数区分即时不足、通过该必要条件后的不可行、PI 可行而因果控制失败，以及 PI 可行且因果控制成功；这些是诊断条件，不是总体发生率。**c，** 早期八周原序次数测试在两种标准下交叉评分。堆叠部分显示 4.42 kW 的成功与即时不足失败；2.95 kW 在两种评分下每周均成功 10/10。**d，** 新配对原序次数与资源时间测试，固定 2.95 kW，八个实际观察周各十次合成实现。资源时间加权下所示每次失败均触发即时不足；所有基线均满足零损失。各对照内部匹配工作总量、合成期限规则、社区及事件时刻。源数据保留所有试验与事先指定的候选网格。')
m('M160','### Figure 6 | Price the operating exposure of qualified commitments','### 图 6 | 为合格承诺的运行暴露定价')
m('M161',
'**a,** Additional waiting exposure per complete four-call series for the refined four- and eight-hour products (300 confirmation scenarios each); points are means and whiskers are scenario 5th–95th percentiles, not confidence intervals. **b,** Net operating cost components at the total annual 95th-percentile rank, with no site fee and US$0.005/GPU-h/h waiting. **c,** Participation thresholds as waiting price varies. **d,** Minimum eight-hour capacity price that matches both the four-hour product and opting out, at three waiting prices. All panels use zero-loss-qualified products of 5.60 and 4.42 model kW, reference deadlines and 16-h start spacing. Monetary panels use proportional 1-MW accounting, twelve independent four-call series per year, US$0.10/kWh electricity, US$50/MWh capped delivered-energy revenue, zero missed-work price and 2,000 annual draws including failures. Price curves are conditional on the reference workload; they are not transferable offers for the failed resource-time tests.',
'**a，** 加密后的四小时与八小时产品每组完整四次调用的额外等待暴露（各 300 个确认情景）；点为均值，须为情景第 5–95 百分位，并非置信区间。**b，** 无场站费、等待价格每 GPU-h 每小时 0.005 美元时，总年度第 95 百分位排序位置对应的净运行成本组成。**c，** 随等待价格变化的参与门槛。**d，** 三种等待价格下，同时达到四小时产品与不参与价值的最低八小时容量价格。全部面板采用零损失资格产品，模型报价分别为 5.60 和 4.42 kW，使用参考期限及 16 h 开始间隔。金额面板按比例折算至 1 MW，每年十二组独立四次调用，电价每 kWh 0.10 美元，截顶交付电量收入每 MWh 50 美元，漏期工作价格为零；2,000 次年度抽样包括失败。价格曲线以参考工作负载为条件，不能作为资源时间测试失败后的可转用报价。')

s('S20_005','The notes and tables distinguish the original five-workload comparison, controller repair, structural study and focused commitment diagnostics. Tables 18–21 report local refinement, exact-window feasibility, matched count/resource-time transfer and the physical exposures and costs of the refined products. Earlier tables retain their original designs; their selected requests do not replace the newer reference choices. Source Data include frozen inputs, all successes and failures, direct plotting tables and replay code.',
'说明与表格区分原五档工作负载比较、控制器修复、结构研究及集中的承诺诊断。表 18–21 报告局部加密、严格时间窗可行性、次数与资源时间配对适用检验，以及新产品的物理暴露与费用。早期表保留原设计，其所选请求不替代较新的参考选择。源数据包括冻结输入、全部成功与失败、直接绘图表和重放代码。')
s('S20_011',MAIN['M078'][0],MAIN['M078'][1])
s('S20_060','### Supplementary Figure 3 | Candidate resolution and structural context','### 补充图 3 | 候选分辨率与结构背景')
s('S20_062',
'**a,b,** Development one-sided 95% Wilson lower bounds for every refined four- and eight-hour candidate (100 new seeds each; 1% and zero-loss endpoints). The dashed line marks the selection criterion of 0.95; the 8-h grid ceiling is selected, not a bracketed maximum. **c,** Earlier 300-scenario full-request structural tests show instantaneous shortages and >1% deadline failures as overlapping categories. **d,** Earlier same-clock final-call electrical success counts with or without three preceding calls; all pairs coincide. The earlier controller repair and complete structural selections remain in Tables 10–15; new PI diagnoses use separate exact work-group constraints (Table 19).',
'**a,b，** 加密后每个四小时与八小时候选的开发单侧 95% Wilson 下界（每项 100 个新种子；1% 和零损失终点）。虚线为 0.95 选择标准；八小时选中了网格上端，并非夹定了最大值。**c，** 早期 300 情景全额请求结构检验，以可重叠类别显示即时不足与超过 1% 的期限违约。**d，** 早期对齐时刻的末次调用电力成功数，有无先前三次调用的全部配对结果重合。早期控制器修复与完整结构选择仍在表 10–15；新增 PI 诊断采用独立的严格工作组约束（表 19）。')
s('S20_066','### Supplementary Figure 5 | Waiting valuation and access fees change product choice','### 补充图 5 | 等待估值与接入费用改变产品选择')
s('S20_068',
'**a,** Difference between product-specific fifth-percentile annual net values, eight minus four hours, at equal capacity prices with zero waiting price and zero access fee; zero marks indifference between participating products. **b,** Refined zero-loss product thresholds with zero or US$1/GPU-h missed-work valuation at reference waiting price and zero fee. The zero-loss qualification permits occasional failed scenarios, whose ledgers remain priced. **c,** Fifth-percentile annual net values at US$250 per kW-year, reference waiting price and zero, shared or full access fees. **d,** Eight-hour price required to match both four-hour participation and opting out at those access fees. All products use the new 300-seed confirmation ledgers, 10% eligibility, 65% offered utilisation, reference deadlines and 16-h start spacing. Annual accounting and energy prices match Fig. 6; fees are common across duration products and do not imply reliability pooling.',
'**a，** 在相同容量价格、零等待价格和零接入费下，八小时减四小时各自年度净值第五百分位之差；零表示两个参与产品价值相同。**b，** 参考等待价格、零场站费下，漏期工作估值为零或每 GPU-h 1 美元时，加密零损失产品的补偿门槛。零损失资格仍允许少量失败情景，其账本保留定价。**c，** 容量价格每 kW 每年 250 美元、参考等待价格以及零、共享或全额接入费下的年度净值第五百分位。**d，** 在上述接入费下，同时达到四小时参与和不参与价值所需的八小时价格。全部产品使用新的 300 种子确认账本，固定 10% 工作可参与、65% 工作供给利用率、参考期限和 16 h 开始间隔。年度核算与能源价格同图 6；不同产品承担相同费用，不意味着组合可靠性。')

def extra_tables():
    def table(head,rows):return '| '+' | '.join(head)+' |\n|'+'|'.join(['---']*len(head))+'|\n'+'\n'.join('| '+' | '.join(map(str,row))+' |' for row in rows)
    rows=[]
    def block(n,title,zh,data,note,znote):
        translated=data
        for en,cn in [('Miss allowance','漏期容忍度'),('Supply impossible','即时不足'),('Other infeasible','其他不可行'),('PI feasible','PI 可行'),('PI rescue','PI 补救'),('Baseline failures','基线失败'),('Request kW','请求 kW'),('Success 1%','1% 成功'),('Success zero','零损失成功'),('Confirm 1%','1% 确认'),('Confirm zero','零损失确认'),('Dev 1%','1% 开发'),('Dev zero','零损失开发'),('Selected','选中'),('Program','方案'),('Variant','配置'),('Cases','条件数'),('Shortage','即时不足'),('Weight','权重'),('Order','顺序'),('Mean waiting GPU-h×h/series','平均等待 GPU-h×h/序列'),('Mean excess missed GPU-h/series','平均额外漏期 GPU-h/序列'),('Annual q95 USD','年度 q95 美元'),('Model kW','模型 kW'),('USD/offered kW-year','美元/报价 kW·年'),('Both','两者'),('No','否'),('job_count','提交次数'),('resource_gpu_h','任务资源时间'),('chronological','原序'),('permuted','置乱')]:translated=translated.replace(en,cn)
        rows.extend([dict(id=f'S24_T{n}',en=f'### Supplementary Table {n} | {title}',zh=f'### 补充表 {n} | {zh}'),dict(id=f'S24_T{n}_data',en=data,zh=translated),dict(id=f'S24_T{n}_note',en=note,zh=znote)])
    dev=pd.read_csv(SOURCE/'refinement_development_summary.csv');conf=pd.read_csv(SOURCE/'refinement_confirmation_summary.csv');sel=pd.read_csv(SOURCE/'refinement_selected_confirmed.csv');tab=[]
    for (p,frac),g in dev.groupby(['program','fraction']):
        a=g.set_index('endpoint');c=conf[(conf.program==p)&(conf.fraction==frac)].set_index('endpoint')
        tab.append([p,f'{a.capacity_kw.iloc[0]:.4f}',f"{a.loc['success_1pct','successes']}/100",f"{a.loc['success_zero','successes']}/100",'—' if c.empty else f"{c.loc['success_1pct','successes']}/300",'—' if c.empty else f"{c.loc['success_zero','successes']}/300",'Both' if ((sel.program==p)&(sel.selected_fraction==frac)).any() else 'No'])
    block(18,'Local candidate refinement and independent confirmation','局部候选加密与独立确认',table(['Program','kW','Dev 1%','Dev zero','Confirm 1%','Confirm zero','Selected'],tab),
      'Each grid step is 0.294912159 kW. Both standards selected 5.603331 kW (H4P16) and 4.423682 kW (H8P16). Their confirmation lower bounds are 0.975244 for both four-hour scores, and 0.991062 / 0.970633 for the eight-hour 1% / zero scores. Unselected coarse comparators were prespecified; a dash means not tested on confirmation. The eight-hour upper grid point does not establish a continuous maximum. No confirmatory outcome was used to reselect. These fresh seeds are distinct from Table 14.',
      '每级网格为 0.294912159 kW。两种标准均选择四小时 H4P16 的 5.603331 kW 与八小时 H8P16 的 4.423682 kW。四小时两种评分的确认下界均为 0.975244，八小时 1% / 零评分分别为 0.991062 / 0.970633。未选中的粗网格对照为预先指定；横线表示未在确认集测试。八小时上端网格点不确定连续最大值，确认结果未用于重新选择。本次新种子与表 14 不同。')
    diag=pd.read_csv(SOURCE/'pi_diagnostic_resolved.csv');tab=[]
    for (v,frac,rate),g in diag.groupby(['variant','fraction','miss_rate']):
        counts=g.classification.value_counts();gap=((g.classification=='feasible_witness')&~g.causal_success).sum()
        display=v if v.startswith('u') else 'Week '+str(int(v.split('_')[0][1:])+1)
        tab.append([display,f'{frac*5.898243186:.4f}','0' if rate==0 else '1%',len(g),counts.get('instantaneous_supply_infeasible',0),counts.get('model_infeasible',0),counts.get('feasible_witness',0),gap])
    block(19,'Same-scenario exact-window feasibility diagnostics','同场景严格时间窗可行性诊断',table(['Variant','Request kW','Miss allowance','Cases','Supply impossible','Other infeasible','PI feasible','PI rescue'],tab),
      'Structural cases use seeds 985000–985002 and H8P16. Supply impossible is an analytical certificate; other infeasible is an infeasible HiGHS mixed-integer solve after passing the supply condition. PI rescue means the original causal outcome failed the same service standard while a verified exact-window schedule is feasible. The reference rescue occurs at seed 985002; halved deadlines at the same seed remain infeasible with either 10% or 20% GPU allocation. Five external rows are the first shortage in each affected week, not random samples. All 38 diagnoses are resolved; the first 90-s unresolved run is archived beside its 600-s extension. Exact constraints preserve individual release/deadline groups and the actual event-peak rebound denominator.',
      '结构条件使用种子 985000–985002 与 H8P16。供给不可能为解析证书；其他不可行为通过供给必要条件后，HiGHS 混合整数求解判不可行。PI 补救表示原因果结果未满足同一服务标准，而核验过的严格时间窗调度可行。参考补救发生在种子 985002；同种子期限减半后，10% 或 20% GPU 分配均不可行。五个外部行是各受影响周的首个短缺，并非随机样本。全部 38 项诊断均已解决；原 90 s 未解决运行与 600 s 延长记录共同存档。严格约束保留各释放—期限工作组及实际事件峰值反弹分母。')
    w=pd.read_csv(SOURCE/'weighted_week_summary.csv');tab=[]
    for (weight,order,frac),g in w.groupby(['weight','ordering','fraction']):tab.append([weight,order,f'{frac*5.898243186:.4f}',f'{g.successes_1pct.sum()}/80',f'{g.successes_zero.sum()}/80',g.instantaneous_shortage.sum(),g.baseline_failures.sum()])
    block(20,'Matched submission-count and task-resource-time transfer','提交次数与任务资源时间的配对适用检验',table(['Weight','Order','Request kW','Success 1%','Success zero','Shortage','Baseline failures'],tab),
      'Eight observed weeks × ten synthetic realisations per week; 80 is not a count of independent production weeks. All baseline variants had zero missed work. The eight-hour calls have 16-h start spacing. Weekly class totals, synthetic deadlines, community, phase and within-week permutation are matched across weights. Resource time is reconstructed from task resource allocations and launch/completion intervals, not job sojourn time. At 2.949122 kW under chronological resource-time weighting, weekly successes are 1, 6, 1, 0, 3, 0, 10 and 10. All 49 failures trigger immediate shortage; at 4.423682 kW all 80 do. The earlier 986000-series count test is separate: its 4.423682-kW request has 63/80 successes under either score, with weekly shortages 6, 2, 0, 2, 0, 3, 4 and 0. Full per-week cross-scores and every input are delivered.',
      '八个观察周，每周十次合成实现；80 并非独立生产周数。全部基线变体均为零漏期。八小时调用的开始间隔为 16 h。权重对照匹配类别周总量、合成期限、社区、事件相位及周内置乱。资源时间由任务资源分配与启动/完成区间重建，并非作业逗留时间。在 2.949122 kW 原序资源时间加权下，各周成功数为 1、6、1、0、3、0、10、10；49 次失败全部触发即时不足，4.423682 kW 下则全部 80 次均触发不足。早期 986000 系列次数测试独立保留：其 4.423682 kW 请求按两种评分均成功 63/80，各周不足数为 6、2、0、2、0、3、4、0。完整逐周交叉评分与每份输入均交付。')
    exp=pd.read_csv(SOURCE/'physical_operating_exposure.csv');cost=pd.read_csv(SOURCE/'refinement_cost_components.csv');tab=[]
    for p in ['H4P16','H8P16']:
        c=cost[(cost.program==p)&cost.offerable_zero].iloc[0];e=exp[(exp.program==p)&exp.offerable_zero].set_index('metric')
        tab.append([p,f'{c.capacity_kw:.4f}',f"{e.loc['delay_exposure_gpu_h_h','model_series_mean']:.2f}",f"{e.loc['incremental_missed_gpu_h','model_series_mean']:.4f}",f'{c.net_operating_annual_q95:.2f}',f'{c.net_operating_per_kw_q95:.2f}'])
    block(21,'Physical operating exposure and conditional refined-product costs','运行物理暴露与加密产品的条件性成本',table(['Program','Model kW','Mean waiting GPU-h×h/series','Mean excess missed GPU-h/series','Annual q95 USD','USD/offered kW-year'],tab),
      'Means retain all 300 complete confirmation series, including zero-standard failures. Small numerical missed-work residuals are not operational failures at the 1e−7 tolerance. Eight-hour mean excess missed work is 0.1996 GPU-h/series even though the request meets the probabilistic zero-loss qualification. Costs use waiting US$0.005/GPU-h/h, no missed-work charge, no fixed fee, twelve independently sampled four-call series/year and proportional 1-MW accounting. Separate CSVs give all physical percentiles, price combinations and component attribution. The refined equal-value boundary is P8 = (19/15)P4 + 97.931286 when participating; the opt-out floor is P8 = 330.112105 at these prices. Waiting-price changes require recomputing the total-cost quantile rather than adding marginal component quantiles.',
      '均值保留全部 300 个完整确认序列，包括零标准失败。1e−7 容差以内的微小数值漏期残差不视为运行失败。尽管八小时请求通过概率性的零损失资格，平均额外漏期仍为每序列 0.1996 GPU-h。费用采用等待价格每 GPU-h 每小时 0.005 美元、零漏期收费、零固定费、每年十二个独立抽取的四次调用序列，并按比例折算至 1 MW。独立 CSV 给出全部物理分位数、价格组合与成本归因。在这些价格下，参与产品间等值边界为 P8 = (19/15)P4 + 97.931286，不参与下界为 P8 = 330.112105。改变等待价格时重新计算总成本分位数，不能相加各项边际分位数。')
    return rows

def main():
    assert json.loads((HERE/'numerical_audit.json').read_text())['status']=='PASS'
    for after,new in list(IM.items()):
        for row in new:
            if row['id'].startswith('M024_'):IS.setdefault('S23_temporal_detail',[]).append(dict(id='S'+row['id'][1:],en=row['en'],zh=row['zh']))
    (READER/'sources').mkdir(parents=True,exist_ok=True);changes=[];report={}
    for stem,name,replacements,inserts in [('main','nature_communications_article.md',MAIN,IM),('supplement','supplementary_information.md',SI,IS)]:
        old=json.loads((HERE/'before'/f'{stem}_aligned_blocks.json').read_text());assert old['source_sha256']==h.sha(HERE/'before'/name)
        rows=[]
        def append_new(after):
            for new in inserts.get(after,[]):rows.append(dict(new));append_new(new['id'])
        for r0 in old['blocks']:
            if stem=='main' and r0['id'] in REMOVE:changes.append(dict(id=r0['id'],action='moved_context_to_SI',before=r0));continue
            row=dict(r0)
            if row['id'] in replacements:row['en'],row['zh']=replacements[row['id']]
            for lang in ['en','zh']:row[lang]=row[lang].replace('docs/figures/operating_tradeoffs_v1/artwork/','docs/figures/commitment_mechanisms_v1/artwork/')
            # Retained old PI numbers: change their mathematical status, not the data.
            if row['id'] not in replacements:
                row['en']=row['en'].replace('PI lower tolerance bounds','Relaxed PI tolerance statistics').replace('PI lower tolerance limits','Relaxed PI tolerance statistics').replace('PI lower bound','Relaxed PI statistic').replace('PI lower kW','Relaxed PI kW').replace('PI bounds','relaxed PI statistics').replace('PI bound','relaxed PI statistic').replace('four-hour planning lower bounds','four-hour relaxed planning statistics')
                row['zh']=row['zh'].replace('PI 下容忍界','放松 PI 容忍统计量').replace('PI 下容忍限','放松 PI 容忍统计量').replace('PI 容忍下界','放松 PI 容忍统计量').replace('PI 下界','放松 PI 统计量').replace('PI 边界','放松 PI 统计量').replace('四小时规划下界','四小时放松规划统计量')
            if row['id']=='M153':
                row['en']+=' The retained PI values use aggregate release/deadline relaxations; they are not guaranteed work-group-feasible capacities (Methods).'
                row['zh']+=' 保留的 PI 值采用累计释放/期限放松条件，不保证满足工作组时间窗的容量（见方法）。'
            if row['id']=='M099':
                row['en']+=' The focused extension adds 3,040 full replays, 656,640 hourly rows, 38 resolved exact-window feasibility diagnoses and task-level resource-time reconstruction records.'
                row['zh']+=' 集中补强另增加 3,040 次完整重放、656,640 行逐时数据、38 个已解决的严格时间窗可行性诊断，以及任务级资源时间重建记录。'
            if row['id']=='S23_T14_note':
                row['en']+=' These are the earlier coarse-grid selections. The reference four-hour/16-h and eight-hour/16-h products are subsequently refined with new seeds in Table 18.'
                row['zh']+=' 此处为早期粗网格选择。参考四小时/16 h 与八小时/16 h 产品随后用新种子加密，见表 18。'
            if row['id']=='S23_T17_note':
                row['en']+=' This table prices the earlier coarse-grid selections. Table 21 and Figs. 6 and S5 price the later refined products using their own new confirmation ledgers.'
                row['zh']+=' 本表定价早期粗网格选择；表 21、图 6 和补充图 5 使用较新加密产品自身的新确认账本定价。'
            if row!=r0:changes.append(dict(id=row['id'],before=r0,after=row))
            rows.append(row);append_new(row['id'])
        if stem=='supplement':rows.extend(extra_tables())
        assert len(rows)==len({x['id'] for x in rows})
        header=f'<!--\nWorking {stem}, version 0.24, 2026-09-10.\nLocal refinement, exact-window diagnosis and task-resource-time transfer.\nAuthor metadata remain pending.\n-->\n\n'
        doc=header+'\n\n'.join(x['en'] for x in rows)+'\n';target=ROOT/'manuscript'/name;target.write_text(doc);(READER/'sources'/f'{stem}_original.md').write_text(doc)
        note='本稿逐段对应正文与补充材料 v0.24（2026-09-10）。局部加密、严格工作时间窗诊断与真实任务资源时间对照均已同步。\n\n';cn=[];both=[]
        for row in rows:
            en,zh=h.reader_format(row['en']),h.reader_format(row['zh']);cn.append(zh);both.extend([zh] if en.startswith(('![','$$')) else [f'<!-- {row["id"]} -->\n{en}',zh])
        (READER/f'{stem}_zh.md').write_text(note+'\n\n'.join(cn)+'\n');(READER/f'{stem}_bilingual.md').write_text(note+'\n\n'.join(both)+'\n')
        (READER/f'{stem}_aligned_blocks.json').write_text(json.dumps(dict(source_sha256=h.sha(target),blocks=rows),ensure_ascii=False,indent=2)+'\n')
        wc=lambda text:len(re.findall(r"\b[\w]+(?:[-’'][\w]+)*\b",text))
        report[stem]=dict(blocks=len(rows),source_sha256=h.sha(target),words=wc(doc))
        if stem=='main':report[stem].update(abstract_words=wc(MAIN['M006'][0]),results_words=wc(doc.split('## Results\n')[1].split('## Discussion\n')[0]))
    (HERE/'text_changes.json').write_text(json.dumps(changes,ensure_ascii=False,indent=2)+'\n');(HERE/'revision_validation.json').write_text(json.dumps(report,indent=2)+'\n')
    (READER/'README.md').write_text('# 中文阅读稿 v18\n\n对应英文正文与补充材料 v0.24。\n\n- [正文中文](main_zh.md)\n- [补充材料中文](supplement_zh.md)\n- [正文中英对照](main_bilingual.md)\n- [补充中英对照](supplement_bilingual.md)\n')
    print(json.dumps(report,indent=2))

if __name__=='__main__':main()
