"""Evidence-grounded wording independent of unseen confirmation outcomes."""
from pathlib import Path
import json
HERE=Path(__file__).resolve().parent

def build():
    edits=json.loads((HERE/'method_edits.json').read_text())
    def e(key,en,zh):edits[key]=dict(en=en,zh=zh)
    e('M010',
      'The workload mix sets the first limit on that commitment. Online inference must respond to user requests, whereas some training and offline-inference work can wait within an agreed deadline. Production traces distinguish these classes and their scheduling priorities,<sup>29</sup> but priority is not permission to defer work for grid services. An assessment must therefore specify which jobs are eligible, rather than assigning a fixed flexible fraction to total electricity demand. Eligible jobs must still fit between release and deadline. After a call, postponed work competes with new arrivals; the additional processing obligation relative to operation without response is compute debt.<sup>5,12,18,19</sup> Hardware allocation and recovery rules determine whether that debt can be cleared before the next call.',
      '工作构成首先限制了这种承诺。在线推理需要及时回应用户请求，部分训练和离线推理则可在约定期限内等待。生产轨迹区分了这些类别及其调度优先级，<sup>29</sup> 但低优先级不等于获准为电网服务而延后。因此，评估必须明确哪些作业有资格，不能给总用电简单指定一个固定可调比例。获准作业仍须在释放与截止时间之间完成。调用之后，推迟的工作与新到达工作竞争；相对于无响应运行增加的未来处理义务称为计算债务。<sup>5,12,18,19</sup> 硬件分配和恢复规则决定这些债务能否在下次调用前清除。')
    e('M012',
      'Here we assess data-centre power commitments across declared workload compositions, following each configuration through service qualification, repeated dispatch, PV integration and participation costs. We audit the resource-time composition of a production execution summary and construct scenarios in which 5%, 10% or 20% of offered work may wait. Two higher-share comparisons, 40% and 60%, expose the additional permission and business-composition assumptions needed to obtain larger flexibility. AIDRBench combines these trace-informed job shapes with four-GPU power measurements and a modelled community electricity system. Full-information schedules quantify planning potential; independent causal-controller tests assess delivery. Separate controls distinguish the effects of GPU allocation and unmeasured rigid-load power. The analysis connects an explicit workload assumption to its downstream capacity, grid benefit and participation cost.',
      '本文在明确声明的工作构成下评估数据中心功率承诺，对每种配置贯通服务资格、重复调用、光伏配合与参与成本。我们审计生产执行摘要的资源时间构成，建立总投入工作中 5%、10% 或 20% 可以等待的情景；再用 40% 和 60% 两项高比例对照，展示更大灵活性所需的额外授权和业务构成假设。AIDRBench 将受轨迹启发的作业形状、四 GPU 功率测量与模拟社区电力系统结合。完整未来信息下的调度量化规划潜力，独立因果控制器测试评估交付；另设对照区分 GPU 分配和未测刚性功率的影响。这项分析把明确的工作负载假设连接到其下游容量、电网收益和参与成本。')
    e('M014','### Workload composition limits which computing can support a commitment','### 工作构成限制了哪些计算可以支持响应承诺')
    e('M015',
      'We first examined what fraction of computing could plausibly enter the deferrable pool. Across 40.52 million execution spans in the released Alibaba summary,<sup>29</sup> online inference accounted for 54.5% of requested GPU-hours, offline inference for 21.5% and training for 19.4% (Fig. 1a). Low-priority training and offline inference together accounted for 22.0%. These are descriptive resource-time shares, not measured energy shares or demand-response permissions. They provide a candidate pool from which an operator might authorise a smaller amount of work to wait.',
      '我们首先检查有多少计算可能进入可延后工作池。在 Alibaba 公开摘要的 4,052 万个执行区段中，<sup>29</sup> 在线推理占申请 GPU 小时的 54.5%，离线推理占 21.5%，训练占 19.4%（图 1a）。低优先级训练与离线推理合计占 22.0%。这些是资源时间的描述性占比，不是实测能耗占比或需求响应授权；它们提供候选范围，运营商可能从中允许较少部分工作等待。')
    e('M016',
      'The primary low-share scenarios allowed 5%, 10% or 20% of total offered work to be deferred, preserving the observed class mix and varying permission within low-priority batch work. The 40% comparison required almost all training and offline inference to opt in. Reaching 60% required a different business mix: 19.1 percentage points of total work were reassigned from online to offline inference before batch work was made eligible (Fig. 1b). Online jobs remained ineligible in every scenario. Thus, the two larger fractions describe additional operational assumptions, rather than evidence that a typical inference-led facility can defer most of its load.',
      '主体低比例情景允许总投入工作量的 5%、10% 或 20% 延后，保持观察到的类别构成，只改变低优先级批处理中的获准份额。40% 对照需要几乎全部训练和离线推理都同意参与。达到 60% 则需要不同业务构成：先将总工作量的 19.1 个百分点从在线推理改为离线推理，再赋予批处理延后资格（图 1b）。所有情景中的在线作业均无此资格。因此，两个高比例描述的是额外运行假设，不能证明典型的推理主导设施能够延后大部分负荷。')
    e('M017',
      'All five configurations retained 576 GPUs and 374.4 GPU-h of offered work per hour. We assigned the same approximate fraction of GPUs as work to the flexible pool, keeping mean utilisation near 65% in both pools. This declared allocation policy avoids interpreting a severely overloaded or largely idle pool as the reference operating condition. It also means that the five-way comparison changes eligibility together with its supporting allocation; controls at 10% eligibility isolate allocation separately (Fig. 5; Supplementary Table 8).',
      '五种配置均保留 576 张 GPU 和每小时 374.4 GPU 小时的投入工作量。灵活池 GPU 比例与其承接的工作比例大致相同，使两池平均利用率维持在约 65%。这一明确的分配规则避免将严重过载或大部分闲置的池当作参考运行条件。同时，五档比较改变的是资格及其配套分配；在 10% 资格下另设对照，单独识别分配的影响（图 5；补充表 8）。')
    e('M019',
      'Measured board power constrained the batch-work conversion: four-GPU training and offline inference averaged 259.08 and 300.02 W per GPU, with a held-out mean absolute prediction error of 3.80 W (Supplementary Fig. 2). Online and other rigid workloads required a separate engineering power proxy, tested in sensitivity controls. The measurements therefore supported the scheduling-to-power calculation without establishing the workload mix or the power of online serving.',
      '实测板卡功率约束了批处理工作量到用电的换算：四 GPU 训练与离线推理平均每 GPU 为 259.08 W 和 300.02 W，留出测试的平均绝对预测误差为 3.80 W（补充图 2）。在线及其他刚性工作需要另设工程功率代理，并通过对照检查。测量因此支持调度到功率的换算，但不能证明工作构成或在线服务功率。')
    for n,key in enumerate(['M020','M024','M028','M033','M038','M044'],1):
        path=f'../docs/figures/workload_composition_v1/artwork/AIDRBench_Figure_{n}.png'
        e(key,f'![Figure {n}]({path})',f'![图 {n}]({path})')
    e('M050',
      'For an operator, the assessment begins with an inventory of work that is contractually permitted to wait, together with the hardware and deadlines available to complete it. A capacity and call schedule can then be selected and independently tested before local grid benefits and participation costs are assessed. This is consistent with capacity assessment for other resources whose actions are coupled over time.<sup>25,26</sup> Changing the workload mix requires the downstream calculations to be repeated; a sensitivity curve for planning potential alone cannot establish the reliability or economics of a different operating configuration.',
      '对运营商而言，评估应先盘点合同允许等待的工作，以及完成它所需的硬件和截止时间。随后选择容量与调用安排，进行独立检验，再评估本地电网收益和参与成本。这与其他跨时段相互制约资源的容量评估相一致。<sup>25,26</sup> 工作构成改变之后，必须重做下游计算；单有规划潜力的敏感性曲线，不能证明另一种运行配置的可靠性或经济性。')
    e('M051',
      'These numerical results remain conditional model evidence. Requested GPU-hours from one production infrastructure are not energy measurements or an industry workload census. Deferral permission and deadlines were assumed; hourly divisible jobs, constant rigid demand and a small board-power calibration do not reproduce online latency, checkpoint overhead or facility response. The 40% and 60% cases add unverified participation and business-composition assumptions. The repeated tests cover two four-call schedules followed by a clearance tail, and annual costs sample independent episodes rather than a continuous year. Actual GPU procurement, ageing and contractual failure penalties require operator data. These limitations constrain numerical transfer while leaving the five-scenario comparisons reproducible.',
      '这些数值仍是有条件的模型证据。单个生产基础设施的申请 GPU 小时不是能耗测量或行业工作负载普查。延后授权和截止时间为假设；小时级可分割作业、恒定刚性需求及小规模板卡校准，不能复现在线延迟、检查点开销或设施响应。40% 和 60% 情景增加了未经验证的参与和业务构成假设。重复测试覆盖两种四调用安排及之后的清空尾段，年度成本抽样独立情景，未模拟连续全年。真实 GPU 采购、老化及合同违约罚金需要运营商数据。这些限制约束了数值外推，同时保留五档比较的可复现性。')
    edits['M054']['en']=edits['M054']['en'].replace('in the Supplementary Information','in the archived v0.19 Supplementary Information')
    edits['M054']['zh']=edits['M054']['zh'].replace('保存在补充材料中','保存在归档的 v0.19 补充材料中')
    edits['M081_r2']['en']=edits['M081_r2']['en'].replace('in the Supplementary Information','in the archived v0.19 Supplementary Information')
    edits['M081_r2']['zh']=edits['M081_r2']['zh'].replace('在补充材料中','在归档的 v0.19 补充材料中')
    edits['M095']['en']=edits['M095']['en'].replace('in the Supplementary Information','in the archived v0.19 Supplementary Information')
    edits['M095']['zh']=edits['M095']['zh'].replace('在补充材料中','在归档的 v0.19 补充材料中')
    for lang in ['en','zh']:
        edits['M062'][lang]=edits['M062'][lang].replace('f = Σ_c s_c a_c',r'\(f = \sum_c s_c a_c\)')
    e('M054','The primary comparison followed five declared workload-eligibility scenarios through perfect-information (PI) planning, independent causal-controller testing, repeated programmes, PV integration and participation costs. Eligibility was the share of offered GPU-hours permitted to wait. Capacity was evaluated against the same delivery and service criteria within each declared call programme.',
      '主体比较围绕五档声明的工作资格情景，依次评估完全信息（PI）规划、独立因果控制器检验、重复方案、光伏配合及参与成本。资格指投入 GPU 小时中获准等待的份额。每个声明的调用方案均按相同交付与服务标准评估容量。')
    e('M058','This extension was specified after the earlier benchmark. One hundred development seeds (930000–930099) selected offers, and 300 previously unexamined confirmation seeds (960000–960299) tested them without reselection. The delivered-power recovery guard and feasible-side action rounding were corrected on development data before this controller version was confirmed. Protocol, source, controller and scenario hashes identify the evidence; original locked certificates remain separate historical results.',
      '本扩展在此前基准之后制定。100 个开发种子（930000–930099）用于选承诺，300 个此前未查看的确认种子（960000–960299）在不重新选值的条件下检验。实际交付功率的恢复保护及可行侧动作舍入在开发数据上修正后，再对该控制器版本进行确认。协议、来源、控制器和情景哈希标识对应证据；原锁定证书作为独立历史结果保存。')
    e('M074',r'where \(\Delta B_{c,t}\) is controlled minus baseline backlog in GPU-h, board powers are in W and compute debt is in kWh. Recovery and rebound were evaluated over the declared post-event window, with the clearance tail used to assess terminal backlog. For requested reduction R, delivered power was \(\Delta P_t=\max(0,P^{\mathrm{baseline}}_t-P^{\mathrm{control}}_t)\). Mean event delivery, \(\sum_{t\in E}\min(\Delta P_t,R)/(R|E|)\), had to reach 0.95, and every event hour also had to satisfy',
      r'其中 \(\Delta B_{c,t}\) 为受控减基准积压，单位 GPU 小时；板卡功率单位为 W，计算债务单位为 kWh。在声明的事件后窗口评估恢复与反弹，清空尾段用于评估末期积压。对于请求削减 R，交付功率为 \(\Delta P_t=\max(0,P^{\mathrm{baseline}}_t-P^{\mathrm{control}}_t)\)。平均事件交付 \(\sum_{t\in E}\min(\Delta P_t,R)/(R|E|)\) 必须达到 0.95，且每个事件小时还须满足')
    e('M073',r'\['+'\n'+r'D^{\mathrm{comp}}_t=\frac{\mathrm{PUE}}{1000}\sum_c\Delta B_{c,t}\left(p^{\mathrm{active}}_c-p^{\mathrm{idle}}\right).'+ '\n'+r'\]',r'\['+'\n'+r'D^{\mathrm{comp}}_t=\frac{\mathrm{PUE}}{1000}\sum_c\Delta B_{c,t}\left(p^{\mathrm{active}}_c-p^{\mathrm{idle}}\right).'+ '\n'+r'\]')
    e('M081','Repeated programmes comprised four four-hour calls with eight-hour gaps, or four eight-hour calls with twelve-hour gaps, starting at hour 63. For each workload configuration, development tested 25%, 50%, 75% and 100% of its selected single-event offer. The rule selected the largest qualifying candidate, if any, for independent confirmation. Regardless of that selection outcome, the original single-event offer was prespecified as a repeated-programme comparator and independently tested. The two programmes do not exhaust possible dispatch schedules.',
      '重复方案由四次四小时调用、间隔八小时，或四次八小时调用、间隔十二小时组成，首次均从第 63 小时开始。各配置在开发阶段检验已选单次承诺的 25%、50%、75%、100%；若有候选通过，则选择最大者独立确认。无论该选值结果如何，原单次承诺均被预设为重复方案的对照并接受独立检验。这两个方案未穷尽所有调度安排。')
    e('M078','The PI programme maximised R separately for each scenario. We summarised these maxima using an exact-binomial nonparametric tolerance lower bound at reliability 0.95 and confidence 0.95.<sup>31</sup> With 100 scenarios, the second-smallest optimum supported this statement with achieved confidence 0.96292. The selected controller offers were independently tested using one-sided 95% Wilson probability lower bounds;<sup>32,33</sup> qualification required a lower bound of at least 0.95. This probability concerns all delivery and service criteria together.',
      'PI 程序分别最大化各情景的 R，再用可靠性 0.95、置信度 0.95 的精确二项非参数容忍下界汇总。<sup>31</sup> 在 100 个情景下，第二小的最优值以实际 0.96292 的置信度支持该陈述。所选控制器承诺采用单侧 95% Wilson 概率下界独立检验，<sup>32,33</sup> 资格要求下界至少 0.95。这项概率对应所有交付与服务标准同时满足。')
    edits['M086']['en']+=' Storage problems retained HiGHS 1.15.1 default relative MIP gap 10<sup>−4</sup> and absolute gap 10<sup>−6</sup>. The 10<sup>−5</sup>-kWh lexicographic lock is not the MIP optimality tolerance. Utilisation contrasts near the roughly 0.01-percentage-point scale associated with that relative gap are not interpreted as resolved storage benefits; paired sampling intervals exclude optimisation uncertainty.'
    edits['M086']['zh']+=' 储能问题保留 HiGHS 1.15.1 的默认相对 MIP 间隙 10<sup>−4</sup> 和绝对间隙 10<sup>−6</sup>。10<sup>−5</sup> kWh 的词典序锁定不等于 MIP 最优性容差。接近该相对间隙对应的约 0.01 个百分点尺度的利用率差异，不解释为已分辨的储能条件下收益；配对抽样区间不包含优化不确定性。'
    e('M099','Community demand was obtained from the NREL End-Use Load Profiles through the OEDI building-stock data lake.<sup>27,28</sup> Workload records came from the official Alibaba cluster-trace-gpu-v2026 release.<sup>29</sup> Retrieval locations, preprocessing records and original input hashes are listed in data/manifests/sources.yaml. Raw third-party releases are accessed from their original providers. The accompanying Source Data bundle contains the full class-composition audit, scenario and controller identities, development selection, all trial-level outcomes, complete development and confirmation trajectories and paired economic ledgers, renewable optimisation results, calibration inputs and ready-to-plot tables. CSV and Parquet files have data dictionaries and SHA-256 manifests. Earlier benchmark outputs are preserved in a separately labelled archive. Public archival deposition of this revised bundle remains pending at [ZENODO DOI TO BE ADDED].',
      '社区需求来自 NREL 通过 OEDI 建筑存量数据湖提供的终端用电曲线。<sup>27,28</sup> 工作记录来自 Alibaba 官方 cluster-trace-gpu-v2026 发布。<sup>29</sup> 检索位置、预处理记录与原始输入哈希列于 data/manifests/sources.yaml；第三方原始发布从原提供方获取。随附源数据包包含完整类别构成审计、情景及控制器标识、开发选值、所有试验级结果、完整开发与确认轨迹与配对经济账本、可再生能源优化结果、校准输入和可直接绘图的表格。CSV 与 Parquet 配有数据字典及 SHA-256 清单。此前基准输出保存在单独标明的归档中。本修订包的公开归档存储仍待完成：[ZENODO DOI TO BE ADDED]。')
    edits['M090']['en']+=' Connection benefits and checkpoint costs were unpriced; the reference missed-work price was zero. Existing-GPU depreciation was not inferred as an incremental response cost, and the reserve-capital scenario did not model wear or ageing.'
    edits['M090']['zh']+=' 接入收益与检查点成本未定价，参考未完成工作价格为零。没有将既有 GPU 折旧推断为增量响应成本，预留资本情景也不模拟磨损或老化。'
    e('M101','The AIDRBench project is hosted at https://github.com/daxiang415/AIDRBench. The accompanying revision bundle includes the exact study drivers, corrected-controller implementation, frozen protocols, analysis scripts and standalone Python redraw commands used here. Public archival release of the revised submission code and its software licence remain pending author confirmation; no new release DOI is claimed.',
      'AIDRBench 项目位于 https://github.com/daxiang415/AIDRBench。随附修订包提供本研究所用的精确运行程序、修正控制器实现、冻结协议、分析脚本和独立 Python 重绘命令。修订投稿代码的公开归档发布及软件许可证仍待作者确认，未声称已获得新的发布 DOI。')
    after={'M062':[dict(id='M062_pairing',en='A common job template was generated once per seed. Class-specific GPU-hours were scaled across configurations while release times, deadlines, community values and the event anchor were checked for equality. Arrivals covered seven days, followed by a 48-h clearance tail. Training deadlines were sampled at 2–6 times runtime and clipped to 6–48 h; offline-inference deadlines were 1.5–4 times runtime and clipped to 2–24 h. The sampling specification and all five baseline-service checks are recorded in Supplementary Methods 1–3. These synthetic deadlines do not establish production service permissions.',zh='每个种子只生成一次共同作业模板。各配置按类别缩放 GPU 小时，并检查释放时刻、截止时间、社区数值和事件锚点相同。到达工作覆盖七天，之后有 48 小时清空尾段。训练截止时间按运行时长的 2–6 倍抽样，并限制在 6–48 小时；离线推理为运行时长的 1.5–4 倍，限制在 2–24 小时。抽样规范和五档无响应服务检验见补充方法 1–3。这些合成截止时间不能证明生产环境授予了相应服务权限。')]}
    return dict(replace=edits,after=after,delete=['M018'])

if __name__=='__main__':
    (HERE/'static_edits.json').write_text(json.dumps(build(),ensure_ascii=False,indent=2)+'\n')
