"""Current SI: new study first; superseded numerical evidence stays archived."""
from pathlib import Path
import json
import pandas as pd
HERE=Path(__file__).resolve().parent
SOURCE=HERE.parents[2]/'manuscript/source_data/nature_workload_composition_v1'
CASES=['f05','f10','f20','f40','f60']

def build():
    rows=[]
    def p(en,zh):
        rows.append(dict(id=f'S20_{len(rows)+1:03d}',en=en,zh=zh))
    def table(enhead,zhhead,body,zhbody=None):
        def md(head,data):return '| '+' | '.join(head)+' |\n|'+ '|'.join(['---']*len(head))+'|\n'+'\n'.join('| '+' | '.join(map(str,r))+' |' for r in data)
        if zhbody is None:
            names={'Yes':'是','No':'否','None':'无合格开发候选','Not selected':'未选中',
                'Primary no-response gates':'主体无响应门槛','Single development':'单次开发','Single confirmation':'单次确认',
                'Repeated development':'重复方案开发','Repeated confirmation':'重复方案确认','Fixed-request controls':'固定请求对照',
                'PI optima, including controls':'PI 最优值（含对照）','Renewable comparisons, including controls':'可再生能源比较（含对照）',
                'Full controller hourly rows':'完整控制器小时记录','100 development + 300 confirmation':'100 个开发 + 300 个确认',
                '100 per partition and configuration':'每个分区和配置 100 个','Repeated rows are dependent':'同一种子的多行相互依赖',
                'Delay, US$/GPU-h/h':'延迟（美元/GPU 小时/小时）','Fixed site, US$/year':'站点固定费（美元/年）',
                'Displaced value, US$/deferred GPU-h':'挤占价值（美元/推迟 GPU 小时）','Missed work, US$/GPU-h':'未完成工作（美元/GPU 小时）',
                'Reserve economic life, years':'预留经济寿命（年）','Electricity, US$/kWh':'用电（美元/kWh）',
                'Delivered energy, US$/MWh':'交付电量（美元/MWh）','Independent annual draws':'独立年度抽样',
                'Held fixed':'固定','Common draws at each price':'各价格使用相同抽样'}
            zhbody=[[names.get(x,x) if isinstance(x,str) else x for x in row] for row in body]
        p(md(enhead,body),md(zhhead,body if zhbody is None else zhbody))
    def old(key):
        d=json.loads((HERE/'before/reader_v13/supplement_aligned_blocks.json').read_text())
        r=next(x for x in d['blocks'] if x['id']==key);p(r['en'],r['zh'])
    p('# Supplementary Information','# 补充材料')
    p('## Job constraints and participation costs define firm data-centre demand response','## 作业约束与参与成本界定数据中心可承诺的需求响应')
    p('[AUTHOR NAMES]','[作者姓名待定]')
    p('## Reader guide','## 阅读指南')
    p('The six notes follow the main results. Methods give the complete five-scenario design; nine tables provide its numerical evidence. Capacity, repeated-programme, renewable and cost results follow the same five workload configurations. Source Data retain all trial-level outcomes, complete hourly trajectories, planning solutions and paired ledgers, together with frozen input templates and code.',
      '六项说明对应正文结果，方法给出完整的五档设计，九张表列出数值证据。容量、重复方案、可再生能源与成本结果贯穿相同五档工作负载配置。源数据保留所有试验级结果、完整小时轨迹、规划解、配对账本，以及冻结输入模板和代码。')
    table(['Question','Methods','Displays'],['问题','方法','图表'],[
      ['Work composition','1–3','Fig. 1; Tables 1–3'],
      ['Single offers','4–5','Fig. 2; Table 4'],
      ['Repeated calls','6','Fig. 3; Supplementary Fig. 3; Table 5'],
      ['PV integration','7','Fig. 4; Table 6'],
      ['Allocation and power','8','Fig. 5; Supplementary Fig. 4; Table 8'],
      ['Participation costs','9','Fig. 6; Supplementary Fig. 5; Tables 7, 9']],
      [['工作构成','1–3','图 1；表 1–3'],['单次承诺','4–5','图 2；表 4'],['重复调用','6','图 3；补充图 3；表 5'],['光伏配合','7','图 4；表 6'],['分配与功率','8','图 5；补充图 4；表 8'],['参与成本','9','图 6；补充图 5；表 7、9']])
    p('## Supplementary Notes','## 补充说明')
    notes=[
      ('1. Eligibility is an operating permission', '1. 可延后资格是一项运行授权',
       'The source audit multiplies each released execution span\'s requested GPU-equivalents by its uncapped duration. It retains development, other and unknown work in the denominator. Counting records would assign 79.45% to offline inference, whereas requested resource time assigns 21.52%; these are different estimands. Low priority identifies a candidate class of work, not a production deadline or permission to postpone service. At 5–20% eligibility, the common permission multiplier preserves the relative contributions of low-priority training and offline inference. The 40% case expands permission beyond that pool, while 60% explicitly changes business composition. None is a measurement of deployed demand-response eligibility.',
       '源审计将每个公开执行区段申请的 GPU 等效数量乘以未截尾持续时间，分母保留开发、其他和未知工作。按记录数量统计，离线推理占 79.45%；按申请资源时间则为 21.52%，两者估计对象不同。低优先级只识别候选工作类别，不给出生产截止时间或推迟服务的权限。在 5%–20% 资格下，共同获准系数保留低优先级训练与离线推理的相对贡献。40% 将授权扩大至该候选池之外，60% 则显式改变业务构成。任何一档都不是已部署需求响应资格的测量值。'),
      ('2. Planning and qualification answer different questions','2. 规划与资格检验回答不同问题',
       'A PI optimisation finds the largest feasible request for one fully known scenario. With 100 scenarios, the second-smallest optimum is the exact-binomial lower tolerance bound for 95% reliability at at least 95% confidence (achieved confidence 0.96292). A controller offer is a different object: a candidate fixed on development data and tested on 300 independent scenario seeds. The one-sided 95% Wilson lower bound must reach 0.95. The offer and PI tolerance bound use different samples and statistical constructions, so their ordering in a plot is not an information advantage. Offers are selected from a finite grid and are not continuous maxima. Notice comparisons hold the request fixed and test paired binary outcomes.',
       'PI 优化寻找一个完整已知情景中的最大可行请求。在 100 个情景中，第二小的最优值构成可靠性 95%、置信度至少 95% 的精确二项容忍下界，实际达到的置信度为 0.96292。控制器承诺是另一对象：在开发数据上固定候选，再用 300 个独立情景种子检验，其单侧 95% Wilson 下界必须达到 0.95。承诺与 PI 容忍下界使用不同样本和统计构造，图中二者的高低不代表信息优势。承诺来自有限网格，并非连续最大值。通知比较固定请求，检验配对二元结果。'),
      ('3. A repeated programme is one dependent trial','3. 重复方案是一次内部相关的试验',
       'Four calls in one evolving queue are not four independent observations. The matched fresh comparison runs each call alone at the same clock time, then asks whether all four isolated calls passed. Both conditions therefore have the same all-four-success endpoint. Their difference estimates the consequence of call history within the specified model and schedule. A development-selected repeated candidate receives its own independent test. If no tested candidate qualifies, this is a search-grid outcome, not evidence that all positive capacities are impossible. Complete hourly series, including failures and clearance after the last call, are retained.',
       '同一个演化队列中的四次调用不是四个独立观测。配对的新事件比较在相同时刻分别单独运行每次调用，然后检查四次是否全部通过。因此两种条件使用相同的“四次全成功”终点，其差异估计指定模型与安排下的调用历史影响。开发选出的重复候选另外接受独立检验。若测试候选均不合格，这是搜索网格的结果，不能证明一切正容量都不可能。完整小时序列保留失败轨迹及最后调用后的清空过程。'),
      ('4. PV hosting and utilisation have different denominators','4. 光伏承载与利用率采用不同分母',
       'Hosting maximises PV nameplate at the unchanged GPU installation. The reported all-scenario boundary is the minimum of the 100 scenario capacities within each operating mode. Its gain is min(flexible) minus min(rigid), not the minimum or mean of paired differences. Fixed-PV utilisation instead divides locally used PV energy by available generation from a 500-kW installation. Its effect is reported in percentage points with paired bootstrap intervals. All current renewable programmes impose zero missed GPU-hours. They use full future information and a separately optimised dispatch; their benefit is not attributed to the causal demand-response controller.',
       '承载优化在 GPU 设施规模不变时最大化光伏额定容量。全情景边界为每种运行方式下 100 个情景容量的最小值，其增量是 min(灵活) 减 min(刚性)，不是配对差异的最小值或均值。固定光伏利用率则以 500 kW 装置的可发电量为分母、本地使用电量为分子，效应按百分点及配对自助区间报告。当前所有可再生能源优化均要求未按期完成 GPU 小时为零。这些优化采用完整未来信息及单独优化的调度，不能把收益归给因果需求响应控制器。'),
      ('5. Controls separate allocation from eligibility','5. 对照区分分配与资格',
       'The primary f-to-f GPU allocation rule maintains similar mean utilisation as eligibility changes. It does not make the five cases a pure one-factor experiment. At fixed 10% eligibility, the allocation controls move the flexible GPU fraction from 10% to 20% and 30%, retaining total work, hardware, releases and deadlines. The power controls retain the same allocation but change only unmeasured rigid-class active power to 150 or 225 W per GPU. Every control is tested at the original 10% configuration\'s selected requests; offers are not reselected after observing its results. The controls therefore compare planning potential and transfer of a fixed offer, not separately optimised controller capacities.',
       '主体采用工作比例与 GPU 分配比例相匹配的规则，使资格变化时平均利用率相近，但这不意味着五档是纯单因素实验。在固定 10% 资格下，分配对照将灵活 GPU 比例由 10% 调至 20% 和 30%，保持总工作量、硬件、释放与截止时间。功率对照保留相同分配，只将未测刚性类别的活动功率改为每 GPU 150 W 或 225 W。各对照均采用原 10% 配置选出的请求，观察结果后不重选承诺。因此它们比较规划潜力与固定承诺的迁移表现，而非各自单独优化的控制器容量。'),
      ('6. Cost thresholds are conditional participation screens','6. 成本门槛是有条件的参与筛选',
       'The physical ledger pairs each controlled trajectory with its own no-response baseline. Positive extra backlog accumulates waiting exposure; delayed work during events and permanently missed work remain separate quantities. Each hour is counted once across a repeated programme. Performance revenue credits only non-negative reduction capped at the request. Fixed annual site costs are applied once after proportional accounting at a 1-MW operating peak. A small offer can therefore have a high price per offered kilowatt even when its total delayed work is small. The 95th percentile of annual net cost is a risk-screening choice, not a confidence limit or observed tariff. Unqualified offers remain unqualified even if their conditional cost is low.',
       '物理账本把每条受控轨迹与自身无响应基准配对。正的额外积压累计等待暴露；事件期间推迟工作与永久未按期完成工作保持区分。重复方案中每小时只计一次。履约收入只计非负、且以上报请求封顶的削减量。在按运行峰值比例缩放到 1 MW 会计尺度之后，每年站点固定费用只计一次。因此，即使推迟工作总量较小，小容量承诺仍可能有较高的每承诺千瓦价格。年度净成本的第 95 百分位是一种风险筛选选择，不是置信限或观察到的电价。未通过资格检验的承诺不会因条件成本较低而变成合格承诺。')]
    for head,zhhead,en,zh in notes:p('### '+head,'### '+zhhead);p(en,zh)
    p('## Supplementary Methods','## 补充方法')
    p('### 1. Source audit and permissions','### 1. 来源审计与授权')
    p('The local jobs_summary.parquet contained 40,522,321 execution-span records. Streaming batches of one million rows were aggregated by workload class and priority, using requested GPU-equivalents times the original duration. The total was 254,980,926.33 requested GPU-h. The audit checked the stored raw work against this product and retained all classes. The source SHA-256 was `95c91a8035197e15f29e9c1d15a9147d07b2a6959b2bb08322cb9f033b029124`. The [production study](https://www.usenix.org/system/files/osdi26-li-suyi.pdf) and [official schema](https://github.com/alibaba/clusterdata/blob/master/cluster-trace-gpu-v2026/docs/schema.md) define the infrastructure scope and execution-span fields. The reported infrastructure excludes dedicated hyperscale foundation-model pretraining clusters.',
      '本地 jobs_summary.parquet 含 40,522,321 条执行区段记录。按每批 100 万行流式读取，以申请 GPU 等效数量乘原始持续时间，按工作类别和优先级聚合，总计 254,980,926.33 申请 GPU 小时。审计核对存储的原始工作量与该乘积一致，并保留所有类别。源 SHA-256 为 `95c91a8035197e15f29e9c1d15a9147d07b2a6959b2bb08322cb9f033b029124`。[生产研究](https://www.usenix.org/system/files/osdi26-li-suyi.pdf)和[官方字段说明](https://github.com/alibaba/clusterdata/blob/master/cluster-trace-gpu-v2026/docs/schema.md)界定基础设施范围及执行区段字段。该基础设施不包括专用的超大规模基础模型预训练集群。')
    p('Let s_c be the source resource-time share and l_c the low-priority batch share of class c, each relative to all offered work. For f ≤ L = Σl_c = 0.2202814, eligible work is l_c f/L. For L < f ≤ B = s_training + s_offline = 0.4094199, it is l_c + (s_c − l_c)(f − L)/(B − L). The 60% case transfers f − B = 0.1905801 from online to offline inference and makes all training and offline inference eligible. Other classes remain in the source denominator and are rigid. Full-precision shares are provided in case_definitions.json; rounding in Table 2 does not drive simulations.',
      '令 s_c 为类别 c 的源资源时间份额，l_c 为其低优先级批处理份额，二者分母均为全部投入工作。当 f ≤ L = Σl_c = 0.2202814 时，合格工作为 l_c f/L。当 L < f ≤ B = s_training + s_offline = 0.4094199 时，为 l_c + (s_c − l_c)(f − L)/(B − L)。60% 情景将 f − B = 0.1905801 从在线转为离线推理，并使全部训练和离线推理获得资格。其他类别保留在源分母中且为刚性。完整精度份额见 case_definitions.json，表 2 的舍入数不用于驱动模拟。')
    p('### 2. Paired scenarios and baseline gate','### 2. 配对情景与无响应门槛')
    p('Development used seeds 930000–930099 and confirmation used 960000–960299. Within each seed, a single 60%-case job template supplied the releases, deadlines and class records. Scaling only the class GPU-hours produced the remaining cases; record counts and timing were held identical. The template sampled existing low-priority training/offline job shapes, including for the explicitly hypothetical 40% and 60% cases. Total offered work was 374.4 GPU-h/h for 168 h, followed by 48 h without new arrivals. The flexible GPU count was round(576f), and rigid utilisation was 374.4(1 − f)/(576 − round(576f)). Every no-response scenario had to satisfy service and PCC limits before downstream analysis.',
      '开发种子为 930000–930099，确认种子为 960000–960299。每个种子使用一份 60% 情景的共同作业模板提供释放、截止时间和类别记录，仅缩放各类别 GPU 小时生成其余配置，记录数及时间完全一致。模板抽取既有低优先级训练/离线作业形状，40% 和 60% 这两项明确假设的情景也沿用这些形状。总投入工作为每小时 374.4 GPU 小时，持续 168 小时，之后 48 小时无新到达。灵活 GPU 数为 round(576f)，刚性利用率为 374.4(1 − f)/(576 − round(576f))。所有无响应情景均须先通过服务与 PCC 限制，才进入下游分析。')
    p('Training deadlines were 2–6 times runtime, clipped to 6–48 h; offline-inference deadlines were 1.5–4 times runtime, clipped to 2–24 h. These are synthetic service rules. Single events began at one of 24 hours between 63 and 140, sampled before testing; exact starts are stored with each scenario. Community demand used a 75:25 residential/office mixed-3A profile, scaled to an 800-kW peak. A common 1,100-kW import rating and no-export rule applied to all cases. Initial development baselines under a 1,000-kW rating exceeded it in three cases at seed 930096; the common rating was raised before PI optimisation or offer selection, and the initial gate results were preserved.',
      '训练截止时间为运行时长的 2–6 倍，限制在 6–48 小时；离线推理为 1.5–4 倍，限制在 2–24 小时。这些均为合成服务规则。单次事件在第 63 至 140 小时之间的 24 个候选时刻中抽样，测试前固定，各情景保存精确起点。社区需求采用住宅/办公 75:25 的混合 3A 曲线，缩放到 800 kW 峰值。所有情景采用共同的 1,100 kW 进口限制并禁止反送。在初始 1,000 kW 限制下，开发种子 930096 的三项配置无响应基准超限，因此在 PI 优化或选值前提高共同容量，并保存了初始门槛结果。')
    p('### 3. Power conversion, queues and observations','### 3. 功率换算、队列与观测')
    for k in ['S070','S072','S073','S074','S076']:old(k)
    p('Idle board power was 13.935625 W per GPU and node overhead was assumed to be 300 W. Online, development, other and unknown work used 300.022174 W per active rigid GPU as an engineering proxy, with 150- and 225-W controls. Rigid power was fixed at its class-weighted mean. Online latency was not separately simulated, so preserving batch deadlines is not a measured online-serving SLO test. The controller retained the existing 63-feature firm_v5 observation interface; its six-hour forecasts and queue features were causally masked. The stored compute_debt_kwh field describes the whole controlled queue. Exported excess_queue_energy_kwh explicitly subtracts the matched no-response value.',
      '每 GPU 空闲板卡功率为 13.935625 W，节点开销假定为 300 W。在线、开发、其他和未知工作采用每活动刚性 GPU 300.022174 W 的工程代理，另设 150 W 和 225 W 对照。刚性功率固定为类别加权均值，没有单独模拟在线延迟，因此保持批处理截止时间不等于实测在线服务 SLO 测试。控制器保留既有 63 维 firm_v5 观测接口，其六小时预测及队列特征按因果信息进行掩蔽。存储的 compute_debt_kwh 描述整个受控队列；导出的 excess_queue_energy_kwh 显式减去配对无响应值。')
    p('### 4. Success criteria and statistics','### 4. 成功标准与统计')
    for k in ['S082','S083','S084']:old(k)
    p('For 100 PI optima, binomial inversion selected the second order statistic at q = 0.95 and confidence 0.95. For controller testing, a one-sided 95% Wilson interval used z = 1.6448536. Development and confirmation applied the same lower-bound threshold of 0.95. Each condition contained 100 development or 300 confirmation seeds; extra notices and calls did not create additional independent seeds. Notice comparisons used exact paired McNemar tests with Holm correction across 20 contrasts. Repeated-minus-fresh differences used 10,000 paired bootstrap resamples of 300 seeds. Renewable mean differences used 10,000 paired resamples of 100 seeds. These intervals and qualifications are pointwise, apart from the declared notice-test correction.',
      '对 100 个 PI 最优值，二项分布反演在 q = 0.95、置信度 0.95 时选取第二顺序统计量。控制器检验的单侧 95% Wilson 区间使用 z = 1.6448536，开发与确认采用相同的 0.95 下界门槛。各条件含 100 个开发或 300 个确认种子；额外通知和调用不增加独立种子数。通知比较使用配对精确 McNemar 检验，对 20 项比较作 Holm 校正。重复减新事件的差异采用 300 个种子的 10,000 次配对自助重采样，可再生能源均值差异采用 100 个种子的 10,000 次配对重采样。除声明的通知检验校正外，区间与资格均为逐项结论。')
    p('### 5. Causal controller and development correction','### 5. 因果控制器与开发阶段修正')
    p('The six-hour robust MPC retained its historical-arrival uncertainty envelope, objective weights and release-only queue information. Development exposed a dimensional mismatch in the former recovery guard: it allowed an overshoot of 0.25R, whereas rebound was evaluated relative to actual peak delivery, which could be as low as 0.95R. The revised guard uses 0.25 × 0.95R, along with the existing event-and-window-relief envelopes. When float32 conversion would cross an electrical limit, actions are rounded towards zero. All success criteria remain unchanged. Regression checks cover the delivered-power rebound denominator, event-boundary rounding and unchanged actions outside event/recovery windows. This is a new controller version, not a reinterpretation of the original locked certificate.',
      '六小时鲁棒 MPC 保留其历史到达不确定性包络、目标权重和仅含已释放作业的队列信息。开发阶段发现原恢复保护中的换算不一致：允许反弹 0.25R，但评估以实际最大削减量为分母，而该值可能低至 0.95R。修正后的保护采用 0.25 × 0.95R，并保留事件及窗口峰值削减限制。当 float32 转换将越过电气边界时，动作向零舍入。所有成功标准不变。回归检查覆盖实际交付分母、事件边界舍入，以及事件/恢复窗口之外动作不变。这是新的控制器版本，不能重新解释为原锁定证书。')
    p('Each duration tested 50%, 75%, 90% and 100% of its development PI lower bound. The largest candidate meeting the development Wilson criterion was frozen before confirmation. After the final controller correction, 300 previously unexamined seeds were reserved for confirmation; earlier original-controller and intermediate development outputs were retained as diagnostics. No confirmation outcome was used to choose a smaller replacement offer.',
      '各时长检验开发 PI 下界的 50%、75%、90% 和 100%，将满足开发 Wilson 标准的最大候选在确认前冻结。最终控制器修正后，保留此前未查看的 300 个种子用于确认；更早原控制器和中间开发输出保存为诊断。不使用确认结果另选较小替代承诺。')
    p('### 6. Repeated programmes','### 6. 重复方案')
    p('Four event starts were 63 + j(H + G), j = 0, 1, 2, 3, for (H,G) = (4,8) or (8,12) hours. Development tested 25%, 50%, 75% and 100% of the selected single-event offer without assuming monotonic success. Confirmation tested the prespecified original single offer repeated, plus four single-call counterfactuals at matching clock times. The protocol additionally provided for testing a development-selected repeated offer if one qualified; none did. The no-response reference was the same full-capacity schedule in every paired comparison. The experiment covers two declared programmes, not every recovery gap or a continuous-year guarantee.',
      '四次事件起点为 63 + j(H + G)，j = 0、1、2、3，其中 (H,G) 为 (4,8) 或 (8,12) 小时。开发检验所选单次承诺的 25%、50%、75% 和 100%，不假定成功率单调。确认检验重复使用的预设原单次承诺，并配有四个相同时刻的单调用反事实。协议还规定，如开发选出重复候选则另外确认；实际没有候选通过开发门槛。每项配对比较都使用相同的全容量无响应参考调度。实验覆盖两种声明的方案，未穷尽所有恢复间隔，也不构成连续全年保证。')
    p('### 7. Renewable planning','### 7. 可再生能源规划')
    p('Each configuration used its actual power model at scale one. PV hosting maximised rated PV capacity with curtailment ≤5%, zero deadline misses, terminal backlog ≤2%, imports ≤1,100 kW and no exports. Fixed-PV operation used 500 kW and lexicographic objectives: service, local PV use, grid import, then battery throughput. PV-use tolerance was 10<sup>−5</sup> kWh. BESS had 100-kW charge/discharge power, 200-kWh energy, charge and discharge efficiency 0.95, and initial/terminal state of charge 50%. Binary exclusivity prohibited simultaneous charge and discharge. The first 100 confirmation seeds were paired across rigid/flexible operation and both BESS conditions. All feasibility statuses and missed work were retained; an all-scenario capacity is not reported from a filtered subset.',
      '每种配置均在尺度一使用自己的功率模型。光伏承载最大化额定容量，要求弃光 ≤5%、截止时间损失为零、末期积压 ≤2%、进口 ≤1,100 kW 且禁止反送。固定光伏运行使用 500 kW，按服务、本地光伏利用、电网进口、电池吞吐依次作词典序优化，光伏利用容差为 10<sup>−5</sup> kWh。储能充放电功率 100 kW、容量 200 kWh，充放电效率均为 0.95，初始/末期荷电状态 50%。二元互斥禁止同时充放电。前 100 个确认种子在刚性/灵活运行及两种储能条件之间配对。保留全部可行性状态与未完成工作，不从筛选后的子集报告全情景容量。')
    p('HiGHS 1.15.1 retained its default relative MIP gap 10<sup>−4</sup> and absolute gap 10<sup>−6</sup>; only solver thread count was changed. The lexicographic lock on PV use is distinct from the primary optimisation gap. Small signed BESS utilisation contrasts can lie within this numerical resolution (roughly 0.01 percentage points when most PV is used). They are retained rather than clipped to zero, but are not interpreted as a physical loss or a resolved benefit. Bootstrap intervals describe scenario sampling only. The numerical-precision audit records the solver version and options.',
      'HiGHS 1.15.1 保留默认相对 MIP 间隙 10<sup>−4</sup> 和绝对间隙 10<sup>−6</sup>，只改变求解线程数。光伏利用的词典序锁定与第一阶段优化间隙不同。储能利用率的微小正负差异可能落在这一数值分辨尺度内（当大部分光伏被使用时约为 0.01 个百分点）。数据保留这些差异，不将其裁为零，也不解释为物理损失或已分辨的收益。自助区间只描述情景抽样，数值精度审核记录求解器版本与选项。')
    p('### 8. Orthogonal sensitivity controls','### 8. 正交敏感性对照')
    p('Four controls around 10% eligibility were specified before their outcomes were examined: flexible GPU allocation 20% or 30%, and rigid-class active-power proxy 150 or 225 W. Other inputs, seed identities and event times were unchanged. Each control had 300 no-response gates, 100 PI scenarios at both durations, 300 fixed-offer tests at both durations, and 100 paired renewable scenarios. Its economic ledger used the same fixed requests. These selected controls and the five eligibility scenarios do not constitute a global sensitivity analysis over simultaneous variation in all model parameters.',
      '在查看结果前，围绕 10% 资格声明四个对照：灵活 GPU 分配 20% 或 30%，刚性类别活动功率代理 150 W 或 225 W。其余输入、种子和事件时刻不变。各对照含 300 项无响应门槛、两个时长各 100 个 PI 情景、两个时长各 300 个固定承诺测试，以及 100 个配对可再生能源情景。经济账本采用相同固定请求。这些选定对照与五档资格情景不构成所有模型参数同时变化的全局敏感性分析。')
    p('### 9. Complete ledgers and economic sensitivity','### 9. 完整账本与经济敏感性')
    p('From the first event through episode end, delay exposure was the sum of positive paired excess backlog times the one-hour interval. Incremental energy was the signed controlled-minus-baseline PCC energy. Deferred work summed positive execution shortfalls during event hours; it did not automatically imply lost work. Each repeated series contributed every hour once. The source tables retain incremental deadline misses and terminal backlog even when a programme fails.',
      '从首次事件到情景结束，延迟暴露为正的配对额外积压乘一小时时长后求和；增量能耗为有符号的受控减基准 PCC 电量。推迟工作为事件各小时正的执行短缺之和，并不自动代表工作损失。每个重复序列中每小时只计一次。源表保留增量截止时间损失与末期积压，即使方案失败也不剔除。')
    p('Single-event annual draws sampled 50 complete confirmation episodes; repeated draws sampled 12 complete four-call series. Two thousand common bootstrap draws were used at each price setting. Physical quantities and the offer were multiplied by 1000 divided by each configuration\'s own operating peak; the US$25,000 annual site charge was then added once. The required payment was max(0, the 95th percentile of net annual cost divided by offered accounting kW). Prices were US$0.10/kWh for electricity, US$50/MWh for capped delivered energy and US$0.005/GPU-h/h for waiting. All 300 trajectories were retained regardless of success.',
      '单次年度抽样选择 50 个完整确认情景；重复年度抽样选择 12 个完整四调用序列。各价格设置采用相同的 2,000 次自助抽样。物理量和承诺同乘以 1000 除以各配置自身运行峰值，然后仅添加一次每年 25,000 美元站点费。所需补偿为 max(0，年度净成本的第 95 百分位除以会计承诺千瓦)。电价为每 kWh 0.10 美元，封顶交付电量每 MWh 50 美元，等待每 GPU 小时每小时 0.005 美元。保留全部 300 条轨迹，不按成功筛选。')
    p('Reserve costs annualised 0.15 abstract reserved PCC-side kW per offered kW, at US$2,500 per reserved kW, 8% discount, four-year life, 10% salvage and 3% annual operation and maintenance. This is not a GPU procurement quotation or wear model. Separate assumed displaced-value exposures of US$0.25 and 0.50 per deferred GPU-h were evaluated; only the former is the main illustration. Sensitivity grids covered waiting prices 0, 0.001, 0.005 and 0.01; fixed site costs 10,000, 25,000 and 50,000; displaced values 0, 0.25, 0.5 and 1; missed-work prices 0, 0.25 and 1; and reserve lives 3–6 years. Contract-specific non-performance penalties were not priced. The original price-source register is retained in the archive; these inputs remain scenarios rather than observed operator accounts.',
      '预留成本按每承诺千瓦对应 0.15 个抽象 PCC 侧预留千瓦年化，每预留千瓦 2,500 美元、折现率 8%、寿命四年、残值 10%、年运维 3%。这不是 GPU 采购报价或磨损模型。另评估每推迟 GPU 小时 0.25 和 0.50 美元的假定挤占价值，正文只用前者作示例。敏感性网格包括等待价格 0、0.001、0.005、0.01，站点固定费 10,000、25,000、50,000，挤占价值 0、0.25、0.5、1，未完成工作价格 0、0.25、1，以及预留寿命 3–6 年。未给合同特定的不履约罚金定价。原价格来源登记表保存在归档中；这些输入仍是情景，不是观察到的运营商账目。')
    # Numerical tables and figure legends are appended after all analyses complete.
    return rows, p, table
