"""Build the current main text only from completed, audited new-study tables."""
from pathlib import Path
import json
import pandas as pd
from build_static_edits import build as static
from build_supplement import build as supplement
from supplement_tables import append
from figure_legends import MAIN
HERE=Path(__file__).resolve().parent;SOURCE=HERE.parents[2]/'manuscript/source_data/nature_workload_composition_v1'

def main():
    assert json.loads((HERE/'numerical_audit.json').read_text())['status']=='PASS'
    result=static();edits=result['replace']
    def e(key,en,zh):edits[key]=dict(en=en,zh=zh)
    def read(name):return pd.read_csv(SOURCE/name)
    def fmt(x,n=2):return f'{float(x):.{n}f}'
    pi=read('pi_boundaries.csv');ss=read('single_confirm_summary.csv');rep=read('repeat_paired_comparisons.csv')
    pv=read('renewable_paired_comparisons.csv');econ=read('economic_primary.csv');prices=read('economic_price_sensitivity.csv')
    def pvr(c,b,analysis):return pv[(pv.case==c)&(pv.bess_enabled==b)&(pv.analysis==analysis)].iloc[0]
    def cost(c,h,regime='slack',kind='single'):
        return econ[(econ.case==c)&(econ.duration_h==h)&(econ.regime==regime)&(econ.kind==kind)].iloc[0].risk_adjusted_capacity_payment_usd_kw_year
    low=['f05','f10','f20'];bounds=pi[(pi.role=='confirmation')&(pi.duration_h==4)&pi.case.isin(low)]
    assert len(ss)==30 and ss.qualified.all()
    assert read('notice_paired_comparisons.csv')[['lost_successes','gained_successes']].to_numpy().sum()==0
    selected_count=int(((rep.selected_repeat_kw>0)&(rep.selected_wilson_lower>=.95)).sum())
    # The final development grid selected no repeated candidate. Do not invent a
    # successful offer or reinterpret zero as a physical capacity estimate.
    assert (rep.selected_repeat_kw==0).all(), 'Revise repeated-selection prose if results differ.'
    assert rep[rep.duration_h==4].repeated_successes.eq(300).all()
    assert rep[rep.duration_h==8].repeated_lower.lt(.95).all()
    e('M006',
      'Artificial-intelligence data centres could support electricity grids by postponing computing, but online services limit how much work operators can allow to wait. Here we connect explicit workload permissions to response capacity, repeated delivery, photovoltaic integration and participation costs. An audit of production resource time identifies low-priority training and offline inference as a candidate pool, without treating priority as permission. In scenarios allowing 5–20% of total work to wait, independently tested four- and eight-hour offers are 2.95–11.80 kW for modelled operating peaks of 190–200 kW. Larger 40% and 60% comparisons require broader participation or a changed business mix. Reusing single-event offers passed the confirmation criterion for four-hour calls with eight-hour gaps, but failed for eight-hour calls with twelve-hour gaps; the separate development search selected no repeated candidate. Renewable benefits and compensation are recalculated for every configuration. Lower eligibility limits offered power and concentrates fixed participation costs on fewer kilowatts. Workload permission and call schedule must therefore accompany claims about data-centre flexibility.',
      '人工智能数据中心可通过推迟计算支持电网，但在线服务限制了运营商能够允许等待的工作量。本文将明确的工作授权与响应容量、重复交付、光伏配合及参与成本连接起来。对生产资源时间的审计将低优先级训练和离线推理识别为候选池，但不把低优先级当作延后权限。在允许总工作量 5%–20% 等待的情景中，对应模型运行峰值为 190–200 kW，经独立检验的四小时和八小时承诺为 2.95–11.80 kW。40% 和 60% 的更高比例需要扩大参与范围或改变业务构成。重复使用单次承诺，在四小时调用、八小时间隔下通过确认标准，在八小时调用、十二小时间隔下则未通过；另行开展的开发搜索未选出重复候选。每种配置均重新计算可再生能源收益与补偿。较低资格限制承诺功率，也使固定参与费用集中于更少千瓦。因此，数据中心灵活性陈述必须附带工作授权和调用安排。')
    e('M021','### Smaller eligible pools support smaller independently tested offers','### 较小的合格工作池支持较小的独立检验承诺')
    e('M022',
      'Limiting eligible work constrained the response. Under perfect information (PI), where the scheduler knows all future arrivals, four-hour planning lower bounds were 2.89, 5.78 and 11.56 kW at 5%, 10% and 20% eligibility. Development-selected offers of 2.95, 5.90 and 11.80 kW then qualified on 300 independent scenarios, corresponding to 1.6–5.9% of the configurations\' operating peaks (Fig. 2a; Supplementary Table 4). The 40% and 60% comparisons qualified at 22.19 and 34.00 kW under their additional assumptions. The proportional low-share response follows the shared job-template scaling and allocation policy; it is not an empirically established linear law for production facilities.',
      '限制获准工作量也限制了响应。在完全信息（PI，即调度器事先知道所有未来到达工作）条件下，5%、10%、20% 资格的四小时规划下界为 2.89、5.78、11.56 kW；开发选出的 2.95、5.90、11.80 kW 承诺随后在 300 个独立情景中通过资格检验，相当于各配置运行峰值的 1.6%–5.9%（图 2a；补充表 4）。40% 和 60% 对照在其额外假设下分别合格于 22.19 和 34.00 kW。低比例区间的比例关系来自共同作业模板缩放及分配规则，不是生产设施中经实证确认的线性规律。')
    e('M023',
      'The same selected power qualified at four and eight hours on this finite grid, but longer events reduced observed success from 295/300 to 292/300 in every configuration. The one-sided 95% probability lower bounds were 0.9662 and 0.9533, respectively. Zero-, two- and six-hour notice produced identical paired success outcomes (Fig. 2b). In this model, jobs cannot execute before release and the no-response reference already processes available work eagerly. Advance information therefore does not establish additional pre-executable work. The fixed-request result does not rule out notice benefits under another baseline schedule, workload release pattern or controller.',
      '在该有限网格内，相同承诺功率同时通过四小时和八小时检验，但较长事件使各配置的观察成功数从 295/300 降为 292/300，单侧 95% 概率下界分别为 0.9662 和 0.9533。提前零、二、六小时通知的配对成功结果完全一致（图 2b）。模型不允许作业在释放前执行，无响应参考也已尽早处理可用工作，因此提前获得信息并不自动增加可提前执行的工作。固定请求的结果不能排除其他基准调度、释放模式或控制器下的通知收益。')
    e('M025','### Repeated delivery depends on the call programme','### 重复交付取决于具体调用安排')
    r=rep[(rep.case=='f10')&(rep.duration_h==8)].iloc[0]
    e('M026',
      f'Call history reduced reliability for the longer service. At 10% eligibility and the same 5.90-kW request, four four-hour calls with eight-hour gaps succeeded in all 300 confirmation scenarios, matching four isolated calls at the same clock times. Four eight-hour calls with twelve-hour gaps instead succeeded in {int(r.repeated_successes)}/300 scenarios, compared with {int(r.fresh_joint_successes)}/300 for the isolated calls. The paired difference was {fmt(r.paired_success_difference_pp,1)} percentage points (95% interval, {fmt(r.paired_difference_ci_low_pp,1)} to {fmt(r.paired_difference_ci_high_pp,1)}). Both conditions required all four calls to pass; Fig. 3 and Supplementary Table 5 report every workload configuration.',
      f'调用历史降低了较长服务的可靠性。在 10% 资格、相同 5.90 kW 请求下，四次四小时调用、间隔八小时，在全部 300 个确认情景中成功，与相同时刻分别运行的四次独立调用一致。四次八小时调用、间隔十二小时，则只有 {int(r.repeated_successes)}/300 成功，独立调用为 {int(r.fresh_joint_successes)}/300。配对差异为 {fmt(r.paired_success_difference_pp,1)} 个百分点（95% 区间 {fmt(r.paired_difference_ci_low_pp,1)} 至 {fmt(r.paired_difference_ci_high_pp,1)}）。两种条件都要求四次调用全部通过；五档工作配置均见图 3 和补充表 5。')
    e('M027',
      'Across all five configurations, the prespecified original offers passed the four-hour repeated confirmation criterion (300/300; probability lower bound 0.9911), whereas eight-hour repeated success ranged from 241/300 to 268/300 and failed the criterion. Separately, the 100-scenario development search over 25%, 50%, 75% and 100% of each offer selected no repeated candidate: even its best observed success, 98/100, gave a lower bound of 0.9414. The successful four-hour confirmation is therefore evidence for the prespecified comparator, not a retrospectively selected candidate under the two-stage rule. Event-and-recovery peak-relief failures persisted at reduced requests; these electrical failures do not by themselves establish lost GPU work. The tests distinguish two schedules and do not imply zero repeated capacity.',
      '五档配置的预设原承诺均通过四小时重复方案的确认标准（300/300，概率下界 0.9911），而八小时重复成功数为 241/300 至 268/300，均未通过。另行在 100 个开发情景中搜索各承诺的 25%、50%、75%、100%，没有选出重复候选：即使最好的观察成功数 98/100，下界也只有 0.9414。因此，四小时确认成功支持的是预设对照，不能事后把它改称为按两阶段规则选出的候选。降低请求后仍出现事件及恢复窗口的峰值削减失败；这些电气失败本身不能证明 GPU 工作损失。检验区分了两种安排，不意味着重复容量为零。')
    e('M029','### Workload eligibility changes both PV hosting and local utilisation','### 工作资格改变光伏承载与本地利用')
    lo=[pvr(c,False,'pv_hosting').difference_of_all_scenario_minima for c in low]
    withb=pvr('f10',True,'pv_hosting').difference_of_all_scenario_minima
    e('M030',
      f'With the 576-GPU installation fixed, flexibility increased all-scenario PV hosting by {fmt(lo[0])}, {fmt(lo[1])} and {fmt(lo[2])} kW at 5%, 10% and 20% eligibility without BESS. At 10%, the gain with BESS was {fmt(withb)} kW (Fig. 4a; Supplementary Table 6). These capacities were feasible across all 100 paired confirmation scenarios under at most 5% curtailment and zero deadline misses. Each configuration used its own power model and the same 1,100-kW PCC rating, enabling paired comparisons at a fixed GPU installation.',
      f'固定 576 张 GPU 时，在无储能条件下，5%、10%、20% 资格的灵活性分别使全情景光伏承载增加 {fmt(lo[0])}、{fmt(lo[1])}、{fmt(lo[2])} kW。10% 资格配储能时增加 {fmt(withb)} kW（图 4a；补充表 6）。这些容量在全部 100 个配对确认情景中均满足弃光不超过 5% 且截止时间损失为零。各配置使用自身功率模型及共同的 1,100 kW PCC 限制，在固定 GPU 设施下进行配对比较。')
    u0=pvr('f10',False,'fixed_pv_operation');u1=pvr('f10',True,'fixed_pv_operation')
    assert abs(u1.mean_paired_gain)<0.0001
    e('M031',
      f'For a fixed 500-kW PV installation, the 10% case increased local utilisation by only {fmt(u0.mean_paired_gain,4)} percentage points without BESS (95% paired interval, {fmt(u0.gain_ci_low,4)}–{fmt(u0.gain_ci_high,4)}). With BESS, the reported difference was below 0.0001 percentage points and was not resolved at the configured mixed-integer optimisation precision (Fig. 4b). Small signed storage contrasts are retained in the data; sampling intervals do not include optimisation error. This energy-fraction metric answers a different question from additional installed kilowatts. Storage and flexible work therefore require evaluation within the same local model.',
      f'对于固定 500 kW 光伏装置，10% 资格在无储能时使本地利用率仅提高 {fmt(u0.mean_paired_gain,4)} 个百分点（95% 配对区间 {fmt(u0.gain_ci_low,4)}–{fmt(u0.gain_ci_high,4)}）。有储能时，报告差异小于 0.0001 个百分点，未达到当前混合整数求解精度下可分辨的水平（图 4b）。源数据保留有储能时的微小正负差异；抽样区间不包含优化误差。这一电量比例指标与新增安装千瓦回答不同问题，储能与灵活工作因此需要在同一本地模型中联合评估。')
    e('M032','These renewable results use full future information, zero missed-work allowance and separately optimised schedules. They establish conditional planning benefits, not a demonstration that the causal demand-response controller achieves the same PV outcomes. The larger eligibility comparisons retain their additional participation or business-composition assumptions throughout the renewable analysis.',
      '这些可再生能源结果采用完整未来信息、零未完成工作额度及单独优化的调度。它们给出有条件的规划收益，不能证明因果需求响应控制器达到了相同光伏结果。高资格对照在整个可再生能源分析中仍附带其额外参与或业务构成假设。')
    e('M034','### GPU allocation and rigid-load power affect different parts of the assessment','### GPU 分配与刚性功率影响评估的不同部分')
    e('M035','At fixed 10% eligibility, increasing the flexible GPU allocation from 10% to 20% or 30% left the four- and eight-hour PI bounds at 5.78 and 5.57 kW (Fig. 5a). The unchanged 5.90-kW controller offer also retained 295/300 and 292/300 successes. Extra processing headroom did not supply extra eligible arrivals at the call time. This isolates the allocation effect around the low-eligibility configuration and prevents the primary matching rule from being mistaken for a pure eligibility-only experiment.',
      '固定 10% 资格时，将灵活 GPU 分配由 10% 增至 20% 或 30%，四/八小时 PI 下界仍为 5.78 和 5.57 kW（图 5a）。不变的 5.90 kW 控制器承诺也保持 295/300 和 292/300 的成功数。额外处理余量没有增加调用时已释放的合格工作。这一对照在低资格配置附近单独识别分配影响，避免将主体匹配规则误认为纯资格单因素实验。')
    e('M036','Reducing the unmeasured rigid-class active-power proxy from 300 to 225 or 150 W per GPU also left these baseline-relative offers and success counts unchanged (Fig. 5b; Supplementary Fig. 4). The proxy instead changed the operating-peak coefficient from 193.44 to 173.53 or 153.63 kW. Constant rigid consumption cancels in the paired reduction, but it remains part of facility demand, PV integration and proportional economic accounting. An unchanged response estimate therefore does not make the rigid-power assumption irrelevant.',
      '将未测刚性类别的活动功率代理由每 GPU 300 W 降至 225 W 或 150 W，也没有改变这些相对基准的承诺及成功数（图 5b；补充图 4），但运行峰值系数从 193.44 kW 降至 173.53 或 153.63 kW。恒定刚性用电在配对削减量中相消，却仍影响设施需求、光伏配合及按比例经济核算。因此，响应估计不变并不意味着刚性功率假设无关。')
    allocation_pv=pvr('f10_g20',False,'pv_hosting').difference_of_all_scenario_minima
    e('M037',f'Allocation nevertheless changed local grid value: assigning 20% of GPUs to the flexible pool increased the no-BESS PV hosting gain from {fmt(lo[1])} to {fmt(allocation_pv)} kW at unchanged 10% work eligibility (Supplementary Fig. 4). Cost controls retained each configuration\'s complete ledger and its own operating peak (Fig. 5c,d; Supplementary Table 8). At the proportional 1-MW accounting scale, a changed peak also changes the number of reference modules represented; these cost contrasts do not measure GPU procurement. The selected controls do not cover simultaneous changes in arrival correlations, deadlines, online-serving dynamics and all prices.',
      f'分配仍改变了本地电网价值：工作资格维持 10%，将 20% GPU 分给灵活池，使无储能光伏承载增量由 {fmt(lo[1])} 增至 {fmt(allocation_pv)} kW（补充图 4）。成本对照保留各配置完整账本及自身运行峰值（图 5c、d；补充表 8）。在按比例换算的 1 MW 会计尺度下，峰值变化也改变所代表的参考模块数量；这些成本差异不测量 GPU 采购。选定对照未覆盖到达相关性、截止时间、在线服务动态与全部价格的同时变化。')
    e('M039','### Low eligibility concentrates fixed participation costs on fewer offered kilowatts','### 低资格使固定参与成本集中于更少承诺千瓦')
    e('M040','We next priced each independently qualified single-event offer using its own response and no-response trajectories through recovery. Annual compensation was the payment per offered kilowatt required to make the fifth percentile of net value non-negative under specified energy, waiting and participation costs. Natural slack, reserved headroom and assumed displaced-value exposure describe different costs of providing the same electrical offer (Fig. 6). They are scenarios for screening participation, not measured operator profits.',
      '随后用各自贯穿恢复期的响应与无响应轨迹，为每个独立合格的单次承诺核算价格。年度补偿为在指定能耗、等待和参与成本下，使净值第 5 百分位不为负所需的每承诺千瓦费用。自然空闲、预留容量与假定挤占价值暴露，描述同一电气承诺的不同供给成本（图 6）。它们用于参与筛选，不是实测运营商利润。')
    c5,c10,c20=cost('f05',4),cost('f10',4),cost('f20',4)
    e('M041',f'At a proportional 1-MW accounting scale, 50 independent four-hour calls per year and a US$25,000 annual site charge, slack-participation thresholds were US${fmt(c5)}, {fmt(c10)} and {fmt(c20)} per offered kW-year at 5%, 10% and 20% eligibility. For 10%, reserved headroom raised the threshold to US${fmt(cost("f10",4,"reserved_headroom"))}, and assumed displaced value raised it to US${fmt(cost("f10",4,"displacement_0.25"))} (Fig. 6a; Supplementary Table 7). The 1-MW conversion scales the paired ledger and offered power; it does not certify a 1-MW installation.',
      f'在按比例换算的 1 MW 会计尺度、每年 50 个独立四小时调用及 25,000 美元站点年费下，5%、10%、20% 资格的自然空闲参与门槛分别为每承诺 kW 每年 {fmt(c5)}、{fmt(c10)}、{fmt(c20)} 美元。10% 资格下，预留容量使门槛升至 {fmt(cost("f10",4,"reserved_headroom"))} 美元，假定挤占价值使其升至 {fmt(cost("f10",4,"displacement_0.25"))} 美元（图 6a；补充表 7）。1 MW 换算按比例缩放配对账本与承诺功率，不认证 1 MW 设施。')
    e('M042',f'The low-share cases deliver less total power while sharing the same site charge. This fixed-cost denominator explains why a smaller eligible pool can require a higher payment per offered kilowatt even though less work is postponed. At 10%, extending calls from four to eight hours changed the slack threshold from US${fmt(c10)} to US${fmt(cost("f10",8))} per kW-year at the same selected power (Fig. 6b). Duration therefore changes the cost of the service even when the finite candidate grid selects the same capacity.',
      f'低比例情景提供的总功率较少，却承担相同站点费用。这一固定成本分母解释了为何合格池较小时，即使推迟工作较少，每承诺千瓦仍可能需要更高补偿。10% 资格下，承诺功率不变，将调用从四小时延长到八小时，使自然空闲门槛从每 kW 每年 {fmt(c10)} 变为 {fmt(cost("f10",8))} 美元（图 6b）。因此，即使有限网格选出相同容量，时长仍会改变服务成本。')
    g=prices[(prices.kind=='single')&(prices.case=='f10')&(prices.duration_h==4)&(prices.fixed_site_cost==25000)&(prices.effective_displaced_value_usd_gpu_h==0)&(prices.missed_work_price==0)]
    e('M043',f'At 10% eligibility, changing the waiting price from zero to twice its reference value moved the four-hour slack threshold from US${fmt(g[g.delay_price==0].iloc[0].risk_adjusted_capacity_payment_usd_kw_year)} to US${fmt(g[g.delay_price==.01].iloc[0].risk_adjusted_capacity_payment_usd_kw_year)} per kW-year. Fixed site charges, assumed displaced values, missed-work prices and reserve life were also varied (Supplementary Fig. 5; Supplementary Table 9). The reserve-life calculation is an accounting sensitivity, not a measurement of GPU ageing or a substitute for procurement data.',
      f'10% 资格下，将等待价格从零调至参考值的两倍，四小时自然空闲门槛由每 kW 每年 {fmt(g[g.delay_price==0].iloc[0].risk_adjusted_capacity_payment_usd_kw_year)} 美元变为 {fmt(g[g.delay_price==.01].iloc[0].risk_adjusted_capacity_payment_usd_kw_year)} 美元。另改变站点固定费、假定挤占价值、未完成工作价格与预留寿命（补充图 5；补充表 9）。预留寿命计算属于会计敏感性，不是 GPU 老化测量，也不能替代采购数据。')
    e('M043_series','Repeated-programme ledgers retained every hour once across all four calls and the clearance tail, including failed trajectories. Their conditional prices are shown for all five configurations at twelve independent series per year (Fig. 6c). Filled markers identify original offers passing the four-hour confirmation criterion; crosses identify the eight-hour failures. Neither price changes the separate finding that the development rule selected no repeated candidate. Non-performance penalties are unpriced, and independent series do not represent a continuously operating year.',
      '重复方案账本将四次调用及清空尾段中的每小时仅计一次，并保留失败轨迹。五档均给出每年十二个独立序列下的条件价格（图 6c）。实心标记表示通过四小时确认标准的原承诺，叉号表示八小时未通过。两种价格都不改变开发规则没有选出重复候选这一独立结果。不履约罚金未定价，独立序列也不代表连续全年运行。')
    e('M046','The main implication is that a workload assumption must travel with its downstream conclusions. Explicitly limiting permission to 5–20% of offered work produced single-event offers of only 2.95–11.80 kW in this model. Larger values required broader batch participation or a changed business mix. This connects production workload characterisation<sup>29</sup> to the commitment question raised by field demonstrations<sup>2</sup> and scheduling studies,<sup>4–17</sup> without treating a candidate low-priority pool as an observed demand-response resource.',
      '主要启示是，工作负载假设必须与下游结论始终对应。将获准份额明确限制在总投入工作的 5%–20%，本模型的单次承诺仅为 2.95–11.80 kW。更大数值需要扩大批处理参与或改变业务构成。这将生产工作负载刻画<sup>29</sup>与现场示范<sup>2</sup>及调度研究<sup>4–17</sup>提出的承诺问题连接起来，同时避免将低优先级候选池当作已观察到的需求响应资源。')
    e('M047','Repeated operation exposed the limits of transferring a single-event certificate. The four-hour programme passed independent confirmation at the original offer, whereas the eight-hour programme did not. The development grid nevertheless selected no repeated candidate, demonstrating that the prespecified selection outcome and a successful independent comparator test must be reported separately. Peak relief over event-and-recovery windows remained a limiting electrical condition even at reduced requests. These failures do not justify attributing every unsuccessful programme to lost computing work or inferring a universal derating factor. A different controller, finer capacity search or revised schedule would require a new independent test.',
      '重复运行暴露了单次证书迁移的限制。四小时方案在原承诺下通过独立确认，八小时方案则未通过；开发网格仍未选出重复候选，说明必须分别报告预设选值规则的结果与独立对照检验成功。即使请求降低，事件及恢复窗口峰值削减仍是限制性的电气条件。这些失败不能支持把所有未成功方案归因于计算工作损失，也不能据此推断通用降额系数。不同控制器、更细容量搜索或改变安排，都需要新的独立检验。')
    e('M048','Workload permission also changed the local planning and accounting context. Hosting additional PV and increasing the use of an installed system require different calculations, and battery storage changes both opportunities. Their values cannot be added independently.<sup>20–24</sup> Likewise, a constant rigid-power term can cancel in baseline-relative response while still affecting the facility peak, grid integration and economic scaling.',
      '工作授权也改变本地规划和会计背景。新增光伏承载与提高已安装系统的利用需要不同计算，电池储能会改变两种机会，不能将它们的价值独立相加。<sup>20–24</sup> 同样，恒定刚性功率项可在相对基准的响应中相消，却仍影响设施峰值、电网配合及经济缩放。')
    e('M049','Lower eligibility concentrates fixed site costs on a smaller offer. Reserved headroom and hypothetical displaced value can add further charges, while longer calls increase waiting exposure. The complete ledgers make these mechanisms recalculable at other prices. They do not establish actual GPU wear, operator revenue loss or profitability, and a low conditional price cannot compensate for an unqualified repeated programme. Technical qualification remains a prerequisite for interpreting a participation threshold as an offerable option.',
      '较低资格使固定站点成本集中于更小承诺。预留容量和假定挤占价值可增加收费，较长调用则增加等待暴露。完整账本使这些机制可在其他价格下重新计算，但不能证明真实 GPU 磨损、运营商收入损失或盈利；较低条件价格也不能弥补重复方案不合格。将参与门槛解释为可报价选项之前，技术资格仍是前提。')
    result['delete'].extend(['M027_boundary','M037_timing'])
    for n,(en,zh,caption,zhcaption) in enumerate(MAIN,1):
        e(f'M{148+2*n:03d}',f'### Figure {n} | {en}',f'### 图 {n} | {zh}')
        e(f'M{149+2*n:03d}',caption,zhcaption)
    si,p,t=supplement();result['new_blocks']={'supplement':append(si,p,t)}
    (HERE/'edits.json').write_text(json.dumps(result,ensure_ascii=False,indent=2)+'\n')
    print('Current main edits and complete nine-table SI written')

if __name__=='__main__':main()
