"""Point readers to the completed v0.20 manuscript, v14 reader and v9 handoff."""
import json
from pathlib import Path
from figure_legends import MAIN,SUPPLEMENT

HERE=Path(__file__).resolve().parent;ROOT=HERE.parents[2]
REV='manuscript/revisions/workload_composition_2026-09-09'
ZIP='results/exports/AIDRBench_All_Figures_2026-09-09_v9.zip'
ART='docs/figures/workload_composition_v1/artwork'


def replace_file(name,text):
    path=ROOT/name;before=HERE/'before/site_indices'/name
    if path.exists() and not before.exists():
        before.parent.mkdir(parents=True,exist_ok=True);before.write_bytes(path.read_bytes())
    path.write_text(text)


def main():
    assert all(x['status']=='PASS' for x in json.loads((HERE/'text_audit.json').read_text()).values())
    assert all(x['status']=='PASS' for x in json.loads((HERE/'pdf_validation.json').read_text()).values())
    original=(ROOT/'MAINLINE_FILES.md').read_text()
    historical=original.split('## Formal scientific assets',1)[1]
    replace_file('MAINLINE_FILES.md',f'''# AIDRBench formal mainline

## Current revision v0.20, 2026-09-09

The current manuscript follows 5%, 10%, 20%, 40% and 60% workload eligibility through its own single-event, repeated-programme, renewable and economic calculations. The 40% and 60% cases require additional permission or changed business composition; online work is never deferred. Historical 75% outputs are preserved separately and do not supply current numerical claims.

- English: `manuscript/nature_communications_article.md` and `manuscript/supplementary_information.md`.
- Chinese: `docs/chinese_reader/v14/`; current main and SI PDFs are v0.20 in `manuscript/exports/`.
- Data: `manuscript/source_data/nature_workload_composition_v1/`, including all 34,400 replays, 7,430,400 hourly rows and complete recovery inputs.
- Current figures: `{ART}/`, six main and five supplementary figures, each PDF/SVG/PNG/TIFF.
- Full handoff: `{ZIP}`; original v8 remains in its historical archive.
- Rationale and checks: `{REV}/README.md`, `RESULTS_AND_REASONS_ZH.md`, numerical/text/figure/PDF/package receipts.

## Authority order

For v0.20, use the frozen `protocol_final.json`, `secondary_protocol_final.json` and `repeat_duration_protocol_v2.json` in `{REV}/`, followed by hash-bound results and current Source Data, then current manuscript text and this index. The original `data/manifests/nature_mainline_protocol_v1.yaml` continues to govern its unchanged historical locked-ID/OOD evidence.

Valid repeated results are only in `results/nature_mainline/workload_composition_v4/repeat_duration_corrected_v2/`. The parent directory's old one-hour repeated diagnostics are excluded. Do not use the legacy repeat stages or `init` in `run_study_final.py` for this completed revision; the delivered frozen protocols and corrected repeated driver specify the final study. Original single-event and renewable stages remain valid.

## Current collaboration preference

The user superseded the automatic three-reviewer workflow. Do not start sub-agents or delegated reviews unless the user explicitly requests them. Existing review reports record past work only. Author names, affiliations, funding, licence and release DOI remain pending author confirmation.

## Current figure-generation authorisation

The user authorised local plotting on 2026-09-08. All current figures are generated by the two standalone Python plotters in `{REV}/`; the redraw package uses their supplied CSV/JSON tables. Historical Web-GPT contracts do not impose a current web-only route.

## Current verification

`audit_results.py` checks source/protocol hashes, scenario splits, selection, every formal event's actual duration and criteria, paired ledgers, all 7,200 renewable results and complete hourly finite values. `audit_text.py`, `check_figures.py` and `check_pdf.py` verify the bilingual manuscript and all eleven figures. Package validation verifies checksums and redraws the figures from the delivered data. Repository project/protocol checks, typing and tests are recorded separately; frozen historical script style findings are not scientific pass claims.

## Archived baseline documentation: v0.19 and earlier

The sections below preserve earlier provenance, layouts, protocols and development notes. References to “current” within this archive describe that historical version. The current paths and scientific scope are specified above.

### Formal scientific assets
'''+historical)
    old=(ROOT/'README.md').read_text();body=old.split('\n---\n',1)[1]
    replace_file('README.md',f'''# AIDRBench：工作资格、可靠需求响应与参与成本

当前正文与补充材料为 **v0.20**，中文阅读稿为 **v14**。5%、10%、20%、40%、60% 五档均重新计算后续容量、重复调用、光伏/储能与经济性；40% 和 60% 的额外假设在正文及图注中明确说明。

- [正文中文全文](docs/chinese_reader/v14/main_zh.md) · [补充材料中文](docs/chinese_reader/v14/supplement_zh.md)
- [正文 PDF](manuscript/exports/AIDRBench_Nature_Communications_v0.20_content_revision.pdf) · [补充材料 PDF](manuscript/exports/AIDRBench_Nature_Communications_v0.20_Supplementary_Information_content_revision.pdf)
- [六幅主图预览](docs/nature-mainline-figure-preview.md) · [五幅补充图预览](docs/nature-supplementary-figure-preview.md)
- [全部图与完整数据包 v9]({ZIP}) · [结果与理由]({REV}/RESULTS_AND_REASONS_ZH.md)
- [权威文件和恢复入口](MAINLINE_FILES.md) · [绘图与打包说明](docs/paper-packaging.md)

全部图由本地 Python 数据脚本重绘，包内有可编辑 PDF/SVG、PNG/TIFF、现成面板表、全部逐小时数据及输入恢复文件。本轮没有启动子智能体；作者信息和软件许可证仍待确认。

## 历史研究设计与开发记录（v0.19 及以前）

下文保留此前研究脉络。旧 75% 配置、201-kW 模块、旧 locked 证书与历史敏感性各有原适用范围，不代替本版五档的新结果。当前结果以文首 v0.20 文稿及源数据为准。
'''+body)
    replace_file('docs/chinese_reader/README.md',f'''# 中文阅读稿

当前为 [v14](v14/README.md)，逐段对应英文正文及补充材料 v0.20。

- [正文中文全文](v14/main_zh.md)
- [补充材料中文全文](v14/supplement_zh.md)
- [正文中英对照](v14/main_bilingual.md)
- [补充材料中英对照](v14/supplement_bilingual.md)

五档工作资格的结果、方法、图注和九张补充表均已同步。六幅主图、五幅补充图全部使用本版数据。[完整绘图包 v9](../../{ZIP}) 包含直接重绘表格及全部小时结果。v1–v13 为历史阅读稿。
''')
    replace_file('docs/paper-packaging.md',f'''# 当前论文 v0.20 与绘图包 v9

当前英文正文、补充材料、中文稿 v14 和全部 11 图使用五档工作资格的新结果。完整包为 [`{Path(ZIP).name}`](../{ZIP})，保留原 v8.zip 作为历史归档。

## 一次重画全部图

解压后运行 `python RUN_ALL_FIGURES.py`。首次自动建立绘图环境并安装依赖；已有环境可用 `--use-current-python`。绘图只读取 `03_data/` 的现成 CSV/JSON，不重跑模型。修改主图脚本 `04_code/plot_results.py` 或补充图脚本 `04_code/plot_supplement.py` 后再运行即可。

包内 `hourly_full/` 与 `hourly_plot_csv/` 保留全部开发及确认轨迹；`ready_hourly_curves.csv` 已算好均值与分位数。400 份共同模板、3,200 套配置/基准和精确乘数用于恢复输入，`restore_scenario.py` 验证原始文件哈希。`04_code/aidrbench_project/` 保存当前模拟器源代码。

## 在本项目重建文稿

```bash
python {REV}/plot_results.py --data manuscript/source_data/nature_workload_composition_v1 --output {ART}
python {REV}/plot_supplement.py --data manuscript/source_data/nature_workload_composition_v1 --output {ART}
python scripts/render_review_tex.py --current-figures {ART}
python scripts/render_supplementary_tex.py --current-figures {ART}
tectonic --keep-logs manuscript/exports/AIDRBench_Nature_Communications_v0.20_content_revision.tex
tectonic --keep-logs manuscript/exports/AIDRBench_Nature_Communications_v0.20_Supplementary_Information_content_revision.tex
```

文本与中文同步由 `{REV}/build_content.py`、`integrate_content.py` 管理；前者要求完整数值审核通过。正文 PDF 含六图，补充 PDF 含五图及九张编号表。源文件哈希、字典、画图输入/输出哈希与 PDF 检查均保留。本次数据更新不改变原 locked 证书。

作者信息、许可证和公开归档 DOI 仍待作者确认。旧绘图合约仅说明旧图来源，本版已获授权采用本地 Python。
''')
    for file,items,prefix,kind in [('docs/nature-mainline-figure-preview.md',MAIN,'AIDRBench_Figure_','Figure'),('docs/nature-supplementary-figure-preview.md',SUPPLEMENT,'AIDRBench_Supplementary_Figure_','Supplementary Figure')]:
        paragraphs=['# Current v0.20 scientific figures','All figures use the five declared workload configurations. The 40% and 60% cases retain additional participation or business-composition assumptions. Editable artwork and complete data are in the v9 handoff.']
        for n,(title,zh,caption,zhcaption) in enumerate(items,1):
            paragraphs.extend([f'## {kind} {n} | {title}',f'![{kind} {n}](figures/workload_composition_v1/artwork/{prefix}{n}.png)',caption])
        replace_file(file,'\n\n'.join(paragraphs)+'\n')
    old=(ROOT/'docs/all_figure_handoff/README_FIRST.md').read_text()
    replace_file('docs/all_figure_handoff/README_FIRST.md',f'# 当前完整交付 v9\n\n本轮 11 图、全文及全部绘图数据见 [v9 完整包](../../{ZIP})。一键重绘使用包根目录 RUN_ALL_FIGURES.py。当前数据是五档工作资格贯通重算；以下说明保留为此前交付记录。\n\n---\n\n'+old)
    old=(ROOT/'manuscript/results-evidence-allocation.md').read_text()
    rows=['# Current Results evidence allocation v0.20','The current six result sections use the same five workload configurations. Historical grids and the 75% benchmark remain in the v0.19 archive.','| Main section / figure | Evidence | Supplement |','|---|---|---|','| 1. Workload composition | Complete resource-time audit and declared permissions | Notes 1; Tables 1–3 |','| 2. Single commitments | PI limits, development selection, 300-seed confirmation and paired notices | Note 2; Table 4 |','| 3. Repeated programmes | Original-offer confirmation, all-four fresh comparison and separate development search | Note 3; Table 5; Fig. S3 |','| 4. PV integration | 100 paired scenarios per mode, zero missed work | Note 4; Table 6 |','| 5. Allocation and rigid power | Fixed-request controls, their own PV and economic ledgers | Note 5; Table 8; Fig. S4 |','| 6. Participation costs | All 300 paired ledgers, single/repeated annual draws and price grids | Note 6; Tables 7, 9; Fig. S5 |']
    text='\n\n'.join(rows[:2])+'\n\n'+'\n'.join(rows[2:])+'\n\nFour-hour original repeated offers pass confirmation, but no candidate passes the separate development selection rule. Both findings are reported; neither zero physical capacity nor universal repeated failure is inferred.\n\n## Historical allocation record\n\n'+old
    replace_file('manuscript/results-evidence-allocation.md',text)
    old=(ROOT/'manuscript/terminology-ledger.md').read_text()
    old=old.replace('f in the post-hoc share sweep','f in the declared workload scenarios').replace('perfect-information feasible-set result under the headline 1% missed-GPU-hour allowance, qualified by a zero-miss sensitivity','perfect-information feasible-set result with zero missed GPU-hours in v0.20; historical 1% programmes remain separate')
    old+='''
## v0.20 statistical and workload scope

- Primary low shares are 5%, 10% and 20% of total offered GPU-hours. The 40% all-batch permission and 60% changed-composition comparisons are additional assumptions, not observed deferral permissions.
- GPU allocation matches eligibility in the primary policy; 10% eligibility controls isolate allocation and unmeasured rigid-power effects.
- Confirmation uses 300 previously unexamined seeds after development-based correction and selection. The economic `qualified` flag refers only to its pointwise confirmation Wilson criterion.
- All original four-hour repeated offers passed confirmation. None of the repeat-grid candidates passed the separate development selection rule. Report those outcomes separately; never reinterpret no selection as measured zero capacity.
- Full hourly exports preserve raw `compute_debt_kwh` and explicitly baseline-subtracted `excess_queue_energy_kwh` as different fields.
'''
    replace_file('manuscript/terminology-ledger.md',old)
    print('Current manuscript, reader, source and redraw indices updated')


if __name__=='__main__':main()
