"""Integrate audited results, supporting tables and exactly aligned Chinese prose."""
import importlib.util
import json
import re
from pathlib import Path
import pandas as pd
HERE=Path(__file__).resolve().parent;ROOT=HERE.parents[2];SOURCE=ROOT/'manuscript/source_data/nature_operating_tradeoffs_v1';READER=ROOT/'docs/chinese_reader/v17'
spec=importlib.util.spec_from_file_location('text_helpers',HERE.parent/'workload_composition_2026-09-09/integrate_content.py')
h=importlib.util.module_from_spec(spec);spec.loader.exec_module(h);h.HERE=HERE
MAIN={};SI={};INSERT_MAIN={};INSERT_SI={};REMOVE={'M027_choices','M032','M043_series','M058_recovery','M081_r2','M081_mechanism','M097_recovery'}
def m(i,en,zh):MAIN[i]=(en,zh)
def s(i,en,zh):SI[i]=(en,zh)
def add(dest,after,i,en,zh):dest.setdefault(after,[]).append(dict(id=i,en=en,zh=zh))

m('M006',
'Artificial-intelligence data centres could support electricity grids by postponing computing, but operators must choose commitments that preserve service through repeated calls. Here we link workload permissions to independently tested response offers and their participation costs. A production resource-time audit informs scenarios with 5–20% of work eligible, which support single-event offers of 2.95–11.80 kW for modelled operating peaks of 190–200 kW. Using a controller that enforces every recovery obligation, we then vary offered utilisation, deadlines and call schedules. At 10% eligibility, requiring zero deadline loss instead of a 1% allowance reduces the selected eight-hour repeated offer from 4.42 to 2.95 kW in the reference comparison. With submission timing from eight production weeks, these requests succeed in 63/80 and 80/80 synthetic realisations, respectively. Increasing flexible GPU allocation does not restore the larger request. Fixed site fees explain about 95% of the original four-hour participation threshold, yet removing them leaves distinct operating costs for qualified duration products. The resulting evidence supports choosing a service standard and call commitment together, then pricing that specific offer; neither workload eligibility nor a low access cost is sufficient.',
'人工智能数据中心可以通过推迟计算为电网提供支持，但运营者必须选择能够在重复调用中维持任务服务的响应承诺。本文将工作参与许可与独立检验的响应报价及其参与成本连接起来。生产资源时间审计为 5–20% 工作可延后的情景提供依据；这些情景在约 190–200 kW 的模型运行峰值下，支持 2.95–11.80 kW 的单次响应报价。随后，我们使用执行全部恢复义务的控制器，改变工作供给利用率、期限和调用安排。在 10% 工作可延后的参考比较中，将期限违约容忍度从 1% 收紧到零，使选出的八小时重复响应承诺由 4.42 降至 2.95 kW。采用八个生产周的提交时序后，两档请求分别在 63/80 和 80/80 次合成实现中成功；增加灵活工作池的 GPU 分配未能恢复较大请求的表现。固定场站费用解释了原四小时参与门槛的约 95%，但取消这一费用后，合格时长产品的运行成本仍然不同。因此，应共同选择任务服务标准和调用承诺，再为该具体报价定价；仅有工作参与许可或较低接入费用都不足以确定可行的参与方案。')
m('M012',
'Here we assess which computing commitments an operator can support, and at what conditional cost. A production execution audit informs scenarios with 5%, 10% or 20% of work permitted to wait; 40% and 60% comparisons expose the additional participation and business-composition assumptions needed for larger flexibility. AIDRBench combines trace-informed jobs, four-GPU power measurements and a modelled community electricity system. We distinguish full-information planning from independent causal-controller tests, then examine corrected recovery control under changed utilisation, deadlines and call histories. A separate timing test preserves the order of submissions from eight production weeks.<sup>32</sup> Finally, complete operating ledgers separate the costs of service delivery from fixed access fees and compare compensation for qualified duration products. These steps turn a workload permission into a testable choice of service standard, capacity and call arrangement.',
'本文研究运营者能够支持哪些计算负荷响应承诺，以及这些承诺在给定假设下需要多少补偿。生产执行记录审计为 5%、10% 或 20% 工作获准等待的情景提供依据；40% 和 60% 对照则揭示更大灵活性需要额外的参与和业务结构假设。AIDRBench 将轨迹启发的作业、四 GPU 功率测量与社区电力模型结合起来。我们区分完整未来信息下的规划与因果控制器的独立检验，再用修正后的恢复控制，研究利用率、期限和调用历史变化。另一个时序检验保留了八个生产周的提交顺序。<sup>32</sup> 最后，完整运行账本将服务交付成本与固定接入费用分开，比较合格时长产品需要的补偿。这些步骤将工作参与许可转化为可以检验的服务标准、容量和调用安排选择。')
m('M025','### Service requirements and workload timing change the repeated commitment','### 任务服务要求与工作时序改变可重复调用的承诺')
m('M026',
'We next tested repeated commitments after correcting the controller to enforce every overlapping recovery window. The earlier repair also benefited a greedy policy, so it established an implementation requirement rather than an MPC-specific advantage (Supplementary Fig. 3a; Supplementary Tables 10–12). The new comparison held eligibility at 10% and varied offered utilisation from 50% to 80%, with reference or halved deadline slack and selected GPU-allocation controls. Four eight-hour calls were tested at 16- or 24-h start spacing. Anchoring the final call at the same randomly chosen hour allowed a matched single-call check while retaining different preceding call histories.',
'接下来，我们在控制器已经能够执行全部重叠恢复窗口约束的前提下，检验重复响应承诺。此前的修复同样改善了贪心策略，因而说明的是实现必须满足的要求，不能证明 MPC 独有的优势（补充图 3a；补充表 10–12）。新比较固定 10% 的工作可延后，将工作供给利用率设为 50–80%，采用参考期限或减半的期限余量，并加入指定的 GPU 分配对照。四次八小时调用的开始间隔为 16 或 24 h。将最后一次调用固定在相同的随机时刻，可以在保留不同先前调用历史的同时，与单独调用进行配对核对。')
m('M027',
'The supported offer depended on the task-service requirement. At 65% offered utilisation and reference deadlines, the development-selected request for 16-h start spacing was 4.42 kW with at most 1% missed work, but 2.95 kW with zero missed work; independent confirmation yielded 299/300 and 300/300 successes, respectively (Fig. 3a). Across the full structural grid, all 26 positive endpoint-specific selections passed confirmation; eight combinations selected no candidate (Supplementary Table 14). Retrospective zero-miss scoring left the earlier 30 selected offers’ success counts unchanged, but reduced the unselected full eight-hour comparison at 10% eligibility from 294/300 to 288/300, below the probability-bound qualification rule (Supplementary Table 13). Zero loss therefore changes some operating choices, rather than imposing a universal derating.',
'可支持的报价取决于任务服务要求。在 65% 工作供给利用率和参考期限下，开始间隔 16 h 的方案若允许最多 1% 的工作期限违约，开发集选出的请求为 4.42 kW；若要求零期限违约，则为 2.95 kW。两者在独立确认中分别成功 299/300 和 300/300 次（图 3a）。在完整结构网格中，按不同服务终点选出的 26 个正容量候选全部通过确认，另外八个组合没有选出候选（补充表 14）。对原有结果进行零违约重评分时，先前 30 个已选报价的成功计数没有改变；但 10% 情景中未被选中的全额八小时对照由 294/300 降至 288/300，未达到概率下界判定规则（补充表 13）。因此，零损失要求会改变部分运营选择，并不对应统一的容量折减比例。')
add(INSERT_MAIN,'M027','M023_limits',
'At the unchanged 5.90-kW request, immediate reducible power was insufficient in 203/300 low-utilisation programmes with 16-h spacing, versus 2/300 at 80% utilisation. Halving deadline slack instead caused more than 1% of work to miss its deadline in all 300 programmes at each utilisation (Fig. 3b). Doubling flexible GPU allocation from 10% to 20% did not restore that full request. Yet the final call’s electrical outcome was identical to its same-clock isolated counterpart in every structural comparison (Supplementary Fig. 3b). These results distinguish a necessary instantaneous supply limit from episode-wide service pressure; they do not show that accumulated work inevitably degrades the next electrical response. Nor did longer spacing consistently improve the selected offer, because preceding calls also moved to different hours.',
'在不变的 5.90 kW 请求下，16 h 开始间隔的低利用率方案有 203/300 次因当前可削减功率不足而受限，而 80% 利用率下仅为 2/300 次。将期限余量减半后，每档利用率的全部 300 次方案都出现了超过 1% 的工作期限违约（图 3b）。把灵活工作池的 GPU 分配从 10% 加倍到 20%，未能恢复该全额请求。然而，所有结构对照中，最后一次调用的电力侧结果都与相同时刻的孤立调用完全相同（补充图 3b）。这些结果区分了瞬时可供功率这一必要限制与整个运行阶段的任务服务压力，不能证明积累的工作必然削弱下一次电力响应。更长的开始间隔也未持续提高选出的报价，因为先前调用同时移动到了不同小时。')
add(INSERT_MAIN,'M027','M023_timing',
'The larger offer was also sensitive to temporal structure. Applying the frozen 4.42-kW request to chronologically ordered submissions from eight production weeks gave 63/80 successful synthetic realisations, compared with 76/80 after permuting whole hourly blocks within each week. The 2.95-kW zero-miss request succeeded in all 80 realisations under either ordering (Fig. 3c). Doubling GPU allocation retained 63/80 at the larger chronological request. Permutation was not uniformly beneficial at other tested requests (Supplementary Table 16). These eight-week comparisons preserve observed submission timing while retaining synthetic work sizes and deadlines; they test transfer under a changed structure, not production service-level compliance.',
'较大报价还对时间结构敏感。将冻结的 4.42 kW 请求应用于八个生产周按原序排列的提交时序，在 80 次合成实现中成功 63 次；将各周内的完整小时块置乱后，成功 76 次。2.95 kW 的零违约请求在两种顺序下均为 80/80 成功（图 3c）。GPU 分配加倍后，较大请求在原序下仍为 63/80。对于其他测试请求，置乱并非总能改善结果（补充表 16）。这一八周比较保留真实提交时序，但工作量和期限仍由合成规则给定；它检验的是结构改变后的适用性，不是生产服务等级协议的履约证明。')
m('M029','### PV hosting gains need not imply substantial utilisation gains','### 光伏接纳容量增加不等于利用率显著提高')
m('M030',
'At the fixed 576-GPU installation, flexibility increased all-scenario PV hosting by 2.82, 5.40 and 10.36 kW at 5%, 10% and 20% eligibility without BESS (Fig. 4a; Supplementary Table 6). In the 10% case, however, a fixed 500-kW PV installation gained only 0.0057 percentage points of local utilisation (95% paired interval, 0.0019–0.0106; Fig. 4b). Additional installed capacity and improved use of an existing installation are therefore distinct benefits.',
'在固定 576 个 GPU 的安装规模下，无电池储能时，5%、10% 和 20% 工作可延后分别使全情景光伏接纳边界增加 2.82、5.40 和 10.36 kW（图 4a；补充表 6）。但在 10% 情景中，对固定 500 kW 光伏装机的本地利用率，增益仅为 0.0057 个百分点（95% 配对区间为 0.0019–0.0106；图 4b）。因此，增加可安装容量与提高既有装机利用程度是不同的收益。')
m('M031',
'With BESS, the 10% hosting gain was 5.22 kW and the utilisation contrast was unresolved at the configured mixed-integer optimisation precision. Small signed storage contrasts remain in Source Data; sampling intervals exclude optimisation error. All renewable results used full future information, zero missed work and separately optimised schedules. They establish conditional planning benefits rather than outcomes demonstrated by the causal response controller.',
'有电池储能时，10% 情景的接纳容量增益为 5.22 kW，而利用率差异在所设混合整数优化精度下无法辨明。源数据保留了这些很小的有符号储能差值；抽样区间不包含优化误差。全部可再生能源结果均采用完整未来信息、零工作期限违约和单独优化的调度。因此，它们体现条件性的规划收益，尚不是因果响应控制器已实现的效果。')
m('M039','### Access fees and operating costs affect different participation decisions','### 接入费用与运行成本影响不同的参与决策')
m('M040',
'We priced each qualified offer from its complete response and recovery ledger. The payment threshold makes the fifth percentile of annual net value non-negative at stated prices and a proportional 1-MW accounting scale. In the original 10% eligibility, four-hour single-event case, US$819.90 of the US$863.26 per offered kW-year threshold came from the assumed US$25,000 annual site fee: about 95% (Fig. 6a). The strong low-eligibility penalty was therefore primarily fixed-cost allocation. Removing that fee left US$43.36 per kW-year in net operating exposure; reserve and displaced-value assumptions remain separate sensitivities (Supplementary Tables 7 and 9).',
'我们根据每个合格报价的完整响应及恢复账本定价。参与门槛是在指定价格与按比例折算的 1 MW 核算规模下，使年度净值第五百分位不低于零的补偿。在原有 10% 工作可延后、四小时单次响应情景中，每报价千瓦每年 863.26 美元的门槛里，有 819.90 美元来自假设的每年 25,000 美元固定场站费用，占约 95%（图 6a）。因此，低参与比例下较高的单位门槛主要来自固定成本分摊。取消这一费用后，净运行成本门槛为每千瓦每年 43.36 美元；备用容量与假定被挤占业务价值另作敏感性分析（补充表 7、9）。')
m('M041',
'Zero or shared fees did not eliminate the operating distinction between the new qualified products. At reference utilisation and deadlines, the zero-miss four-hour programme offered 4.42 kW, whereas both eight-hour programmes offered 2.95 kW. With no fixed fee, their thresholds were US$174.54, 321.09 and 401.72 per offered accounting kW-year for four-hour/16-h, eight-hour/16-h and eight-hour/24-h duration/start-spacing combinations, respectively (Fig. 6b,c; Supplementary Table 17). All used twelve independent four-call series per year. These differences reflect complete-series operating exposure and selected capacity, rather than a site charge divided by a smaller offer.',
'零固定费用或共享费用并未消除新合格产品之间的运行差异。在参考利用率和期限下，零违约四小时方案报价为 4.42 kW，两种八小时方案均为 2.95 kW。取消固定费用后，对于“时长/开始间隔”为四小时/16 h、八小时/16 h 和八小时/24 h 的三个组合，门槛依次为每核算报价千瓦每年 174.54、321.09 和 401.72 美元（图 6b,c；补充表 17）。三者均按每年十二组相互独立的四次调用核算。这些差异来自完整调用组的运行负担与选定容量，而非固定场站费用除以较小报价。')
m('M042',
'A common site fee changes whether to enter, but cancels when comparing the annual net values of two participating options. At an illustrative equal capacity price of US$250 per kW-year and no site fee, the reference zero-miss four-hour programme had a fifth-percentile annual net value of US$1,726; the eight-hour programme at the same 16-h spacing had −US$1,084 (Supplementary Fig. 5c). For the latter to match the former conditional on participation, its capacity price must equal 1.5 times the four-hour price plus US$59.28 per kW-year. The additional requirement to outperform opting out defines the full price boundary (Fig. 6d). Sharing the original site fee among five or ten resources lowers access costs, but does not establish portfolio reliability or remove this operating tradeoff.',
'共同的场站费用会改变是否进入市场，但在比较两个参与方案的年度净值时会相互抵消。示例中，若两种产品的容量价格均为每千瓦每年 250 美元且无固定场站费用，参考零违约四小时方案的年度净值第五百分位为 1,726 美元；同为 16 h 开始间隔的八小时方案则为 −1,084 美元（补充图 5c）。在选择参与的条件下，后者要达到前者的净值，其容量价格必须等于四小时价格的 1.5 倍，再加每千瓦每年 59.28 美元；同时优于不参与的要求构成完整价格边界（图 6d）。将原场站费用分摊给五个或十个资源会降低接入成本，但并不证明组合可靠性，也不会消除这一运行取舍。')
m('M043',
'These are conditional participation screens. All confirmation trajectories, including failures, enter the accounts; waiting and missed-work prices are varied separately from access fees (Supplementary Fig. 5). Contract-specific non-performance penalties, checkpoint costs and actual hardware ageing remain unpriced. Independent annual series do not reproduce a continuously operating year, and lower calculated cost cannot make an unqualified request an offerable product.',
'这些结果是条件性参与筛选。核算保留全部确认轨迹，包括失败轨迹；等待与期限违约工作的价格分别于接入费用之外进行变化（补充图 5）。合同规定的不履约罚款、检查点成本与真实硬件老化尚未定价。年度核算中的独立调用组不等于连续运行的一年，较低的计算成本也不能使未通过资格检验的请求成为可报价产品。')
m('M047',
'The additional operating insight concerns which obligation should change when a request fails. Under corrected recovery control, low offered utilisation can leave insufficient immediate reducible power, while tight deadlines can make task completion the binding service condition. Extra GPU allocation alone did not restore the full request in those deadline controls. Requiring zero deadline loss changed the selected reference eight-hour offer and improved its descriptive transfer to observed production timing. This complements prior distinctions between eligible and dependable workload power<sup>19</sup> by testing the service standard attached to a repeated offer. It does not establish a new optimal controller or a universal physical capacity law.',
'新增的运营认识在于：请求失败时，应该调整哪一项义务。在修正后的恢复控制下，较低工作供给利用率可能意味着当前可削减功率不足，而紧期限可能使任务完成成为约束服务的主要条件。仅增加 GPU 分配未能在这些期限对照中恢复全额请求。要求零期限违约改变了参考八小时方案选出的报价，并改善了它在真实生产时序下的描述性迁移表现。这通过检验重复报价所附带的服务标准，补充了既有研究对可参与工作功率与可靠减负的区分。<sup>19</sup> 它并不确立新的最优控制器或普适的物理容量规律。')
m('M049',
'The economic distinction is equally consequential. Fixed access fees largely explained the original unit-cost penalty at low eligibility, so that penalty should not be presented as a new operational mechanism. Once access is free or shared, complete-ledger costs still distinguish duration products and their required tariffs. Operators should therefore compare qualified annual net values, including the option not to participate, rather than rank services solely by a threshold per offered kilowatt. Waiting prices and loss valuations remain assumptions; the calculation identifies what compensation would be required under them, not whether a real operator will accept it.',
'经济上的区分同样影响决策。固定接入费用解释了原分析中低参与比例的多数单位成本惩罚，因此不应把这种分摊关系写成新的运行机制。接入免费或共享后，完整账本的成本仍能区分时长产品及其所需价格。运营者应比较经过资格检验的年度净值，并纳入不参与的选项，而不能仅按每报价千瓦的门槛给服务排序。等待价格与损失估值仍是假设；计算识别的是在这些假设下需要何种补偿，而不是真实运营者一定会接受。')
m('M050',
'For planning, the useful output is a conditional commitment: eligible jobs, deadline standard, installed allocation, capacity and call arrangement, accompanied by delivery evidence and a recalculable cost ledger. This is consistent with capacity assessment for other resources whose actions are coupled over time.<sup>28,29</sup> The matched last-call check also shows why programme failure should not automatically be attributed to cumulative recovery damage. Changes in job timing and service obligations need direct tests, and a candidate should be reduced or withheld when those tests do not support it.',
'对规划而言，有用的产出是一份附带条件的承诺：允许参与的作业、期限标准、已有硬件分配、容量与调用安排，并同时提供交付证据及可重新计价的账本。这与其他行动跨时段耦合资源的容量评估相一致。<sup>28,29</sup> 最后一次调用的配对核对也说明，不能自动将整组调用失败归因于恢复造成的累积损害。工作时序与服务义务变化需要直接检验；检验不支持时，应降低或暂不采用该候选承诺。')
m('M051',
'The evidence remains conditional on hourly divisible jobs, synthetic deadlines and permissions, a constant rigid-load proxy and a small board-power calibration. The five eligibility scenarios share template scaling; the structural controls and eight observed timing weeks broaden this evidence without making it an industry workload census. The timing transfer preserves submission counts, not actual runtimes, job dependencies or production service agreements. No application pause–checkpoint–restart sequence was measured. Selection and confirmation were separated, but all probability bounds are pointwise and all capacities belong to finite candidate grids. Four-call episodes and independent annual draws do not establish continuous-year performance. These boundaries limit numerical transfer and any claim of universal superiority over existing approaches.',
'证据仍以按小时划分的可分工作、合成期限和参与许可、恒定刚性负荷代理及小规模板卡功率校准为条件。五档参与比例情景共用模板缩放；结构对照和八个真实时序周拓宽了证据，但不使其成为行业工作负荷普查。时序迁移保留提交计数，不保留真实运行时长、作业依赖或生产服务协议。我们没有测量应用的暂停—检查点—恢复过程。候选选择与确认虽然分离，但所有概率界均为逐点界，所有容量均来自有限候选网格。四次调用阶段与独立年度抽样不能证明全年连续表现。这些边界限制了数值外推，也限制了相对现有方法普遍占优的主张。')
m('M080','### Repeated commitments and structural controls','### 重复承诺与结构对照')
m('M081',
'All new structural tests used the corrected MPC wrapper, which retains a separate ceiling for each observed event-and-recovery window and clips the proposal to the strictest live ceiling. It uses elapsed baseline peaks and current observations, without future jobs or unannounced calls. Earlier comparisons with the original implementation and guarded greedy policy are retained in Supplementary Methods 6. New candidates were 25%, 50%, 75% and 100% of the fixed 5.898243186-kW reference request. Selection was separate for the 1% and zero-miss endpoints and preceded independent confirmation; successful unselected comparators were not promoted.',
'全部新增结构检验使用修正后的 MPC 包装器：为每个已观测的事件及恢复窗口保留独立上限，并按当前最严格的上限截断建议动作。它仅使用已发生的基线峰值与当前观测，不读取未来作业或未通知的调用。原实现及加入相同保护的贪心策略比较保留在补充方法 6。新候选为固定参考请求 5.898243186 kW 的 25%、50%、75% 和 100%。1% 与零违约终点分别选择候选，随后独立确认；未被选中的对照即使确认成功，也不追认为已选报价。')
add(INSERT_MAIN,'M081','M023_structural_methods',
'At fixed 10% work eligibility and 576 GPUs, offered utilisation was total work divided by installed GPU-hours, set to 50%, 65% or 80%. Deadline slack was unchanged or halved with a one-hour floor; flexible GPU allocation was 10%, with 20% controls at 65% and 80% utilisation under tight deadlines. The final event started at hour 111 plus a seeded uniform integer from 0 to 23; preceding starts were spaced backwards by 16 or 24 h. All eight variants tested eight-hour calls, and the reference also tested four-hour calls at 16-h spacing. A fresh eight-hour final call at the same time removed the preceding calls. All recovery windows ended during 168 h of arrivals, followed by a 48-h clearance tail. Development seeds 984000–984099 and confirmation seeds 985000–985299 supplied 7,600 and 13,200 complete replays, respectively. Two pilot seeds were excluded.',
'固定 10% 工作可参与和 576 个 GPU 后，将工作供给利用率定义为总工作量除以已安装 GPU 小时数，设为 50%、65% 或 80%。期限余量保持参考值或减半，下限为一小时；灵活 GPU 分配为 10%，并在 65% 和 80% 利用率的紧期限情景中增加 20% 分配对照。最后一次事件从第 111 小时加一个由种子确定、在 0–23 间均匀抽取的整数开始；此前事件依次向前相隔 16 或 24 h。八个变体均检验八小时调用，参考条件还检验 16 h 开始间隔的四小时调用。相同时刻的孤立八小时末次调用移除前三次事件。所有恢复窗口均在 168 h 到达阶段内结束，随后有 48 h 清空尾段。开发种子 984000–984099 与确认种子 985000–985299 分别产生 7,600 和 13,200 次完整重放；两个试运行种子不纳入分析。')
add(INSERT_MAIN,'M081','M023_temporal_methods',
'For the external timing stress test, hourly submission counts from the Alibaba 2020 GPU trace<sup>32</sup> supplied eight consecutive 168-h blocks. Counts set the hourly weights of synthetic class-specific work, preserving each class total and reference deadlines. The paired alternative permuted complete hourly blocks within the same week. Ten synthetic realisations per week crossed both orderings and 10%/20% GPU allocations with five frozen programme–request combinations, giving 1,600 replays without retuning. Results are reported by observed week and descriptively across 80 realisations per condition; they are not 80 independent production weeks.',
'外部时序压力检验采用 Alibaba 2020 GPU 轨迹的每小时提交计数，<sup>32</sup> 提供连续八个 168 h 区块。计数决定各类别合成工作的逐小时权重，同时保留各类总工作量与参考期限。配对替代条件在同一周内置乱完整小时块。每周十次合成实现，交叉两种顺序、10%/20% GPU 分配与五个冻结的“方案—请求”组合，共 1,600 次重放，不重新调参。结果按真实周报告，并对每条件 80 次实现作描述性汇总；它们不等于 80 个独立生产周。')
add(INSERT_MAIN,'M076','M023_zero_methods',
'The structural study additionally required zero total missed eligible work, allowing only 10<sup>−7</sup> GPU-h for numerical round-off. Both response and no-response trajectories had to satisfy that zero criterion; all electrical and terminal-backlog thresholds were unchanged. The 0.1% allowance was a secondary reported endpoint without offer selection. Baseline failures remained failures rather than exclusions. Earlier selected offers were also rescored at zero loss, explicitly as a retrospective check.',
'结构研究还检验了全部可参与工作的总期限违约量为零的要求，仅允许 10<sup>−7</sup> GPU-h 的数值舍入容差。响应与无响应轨迹都必须满足该零违约标准；电力与期末积压门槛保持不变。0.1% 容忍度作为次要报告终点，不用于选择报价。基线不合格计为失败，不予剔除。此前选出的报价也进行了零损失重评分，并明确标为回顾性核对。')
add(INSERT_MAIN,'M093_series_method','M023_cost_method',
'The fee decomposition used common annual draws and the same linear-interpolation weights at the total net-cost 95th percentile for every component; it did not add marginal component quantiles. Additional screens crossed site fees US$0, 1,000, 2,500, 5,000, 10,000 and 25,000, waiting prices US$0, 0.005 and 0.01 per GPU-h/h, and missed-work prices US$0 and 1 per GPU-h. Sharing a US$25,000 fee among ten or five resources gave US$2,500 or 5,000 without a diversification benefit. For qualified product j with accounting capacity K_j and annual net operating cost O_j at its 95th percentile, the fifth-percentile net value was P_j K_j − O_j − F. Duration-price boundaries compared these values and the zero value of not participating. They are algebraic consequences of the stated ledgers and prices, not estimated market tariffs.',
'费用分解采用共同年度抽样，对每一成本项使用总净成本第 95 百分位对应的相同线性插值权重，不能相加各项自身的边际分位数。新增筛选交叉场站费用 0、1,000、2,500、5,000、10,000 和 25,000 美元，等待价格每 GPU-h 每小时 0、0.005 和 0.01 美元，以及每 GPU-h 期限违约工作价格 0 和 1 美元。25,000 美元由十个或五个资源分摊，分别为 2,500 或 5,000 美元，不附加分散风险收益。对合格产品 j，若核算容量为 K_j、年度净运行成本第 95 百分位为 O_j，其净值第五百分位为 P_j K_j − O_j − F。时长价格边界比较这些净值及不参与的零净值。它们是指定账本与价格的代数结果，不是估计的市场价格。')
add(INSERT_MAIN,'M097','M023_stats',
'Structural contrasts resampled 300 complete paired scenario seeds 5,000 times. Exact McNemar tests were Holm-adjusted over the 36 binary structural contrasts; the 16 additional matched-target electrical contrasts formed a separate family. The zero-loss and 1% offer tests each retained the pointwise one-sided 95% Wilson lower-bound criterion of 0.95. Multiple successful selections do not create a simultaneous confidence guarantee. Submission-order comparisons retained the observed week as the external sampling unit and were not assigned binomial certificates from pooled synthetic realisations.',
'结构对照对 300 个完整配对情景种子进行 5,000 次重抽样。精确 McNemar 检验在 36 个二元结构对照之间使用 Holm 校正；额外 16 个末次调用电力对照构成单独的检验族。零损失与 1% 报价检验均保留逐点单侧 95% Wilson 概率下界不低于 0.95 的规则。多个选择成功不构成同时置信保证。提交顺序比较保留真实周作为外部抽样单位，不把合并的合成实现赋予二项资格证明。')
m('M154','### Figure 3 | Service standards, operating limits and timing transfer','### 图 3 | 服务标准、运行限制与时序迁移')
m('M155',
'**a,** Development-selected, independently confirmed eight-hour offers at 16-h start spacing, under 1% or zero total missed work. Utilisation denotes offered GPU-hours divided by installed capacity; tight deadlines halve reference slack. NS means no candidate selected, not zero physical capacity. **b,** At the prespecified 5.90-kW request, non-exclusive counts of scenarios with insufficient instantaneous eligible power to satisfy 95% interval delivery, or more than 1% missed work. This supply test is necessary, not sufficient. Panels a,b use 300 independent confirmation scenarios per condition and corrected recovery control. **c,** Success counts within each of eight observed production weeks, with ten synthetic realisations per week, chronological or permuted hourly submission weights and 10% GPU allocation. The 4.42-kW request uses the 1% service endpoint; 2.95 kW uses zero loss. Aggregate counts are descriptive, not binomial certification of production reliability. All panels retain 10% work eligibility and four calls; eight-hour/16-h means eight-hour gaps. Full selections, bounds and timing controls are in Supplementary Tables 14–16.',
'**a，** 开始间隔 16 h 的八小时报价，在总期限违约工作不超过 1% 或为零的要求下，由开发集选择并独立确认。利用率指供给的 GPU 小时数除以安装容量；紧期限将参考余量减半。NS 表示没有选出候选，不表示物理容量为零。**b，** 对预先指定的 5.90 kW 请求，报告无法满足 95% 逐时交付所需瞬时可参与功率的情景计数，以及期限违约工作超过 1% 的计数；两类可重叠。该功率检验是必要条件，不是充分条件。a、b 每条件使用 300 个独立确认情景及修正后的恢复控制。**c，** 八个真实生产周各有十次合成实现，采用原序或置乱的逐小时提交权重，GPU 分配为 10%。4.42 kW 请求采用 1% 服务终点，2.95 kW 采用零损失。总计数仅作描述，不构成生产可靠性的二项资格证明。全部面板保持 10% 工作可参与与四次调用；八小时/16 h 对应八小时间隙。完整选择、概率界及时序对照见补充表 14–16。')
m('M160','### Figure 6 | Separate access costs from the value of qualified services','### 图 6 | 将接入成本与合格服务的价值分开')
m('M161',
'**a,** Original four-hour single-event participation thresholds decomposed into fixed site fees and net operating exposure, with 50 independent calls per year. Component attribution uses the total-cost quantile, not separate marginal quantiles. **b,** Site-fee sensitivity for the new reference zero-miss selected products: 4.42 kW for four-hour/16-h spacing, and 2.95 kW for eight-hour/16-h or eight-hour/24-h spacing. **c,** Their payment thresholds with no fixed fee. **d,** Minimum eight-hour price that outperforms both the qualified four-hour product and non-participation, at 16-h spacing and zero site fee. Labels give eight-hour versus four-hour model capacities; 1% and zero-loss selections are separate. Panels b–d use 10% eligibility, 65% offered utilisation, reference deadlines, corrected MPC and twelve independent four-call series per year. All costs use proportional 1-MW accounting, US$0.005/GPU-h/h waiting, US$0.10/kWh electricity, US$50/MWh delivered-energy revenue and 2,000 annual draws including failed trajectories. Forty and sixty per cent eligibility retain additional batch-participation and business-composition assumptions. These are conditional payment screens, not profits or continuous-year market simulations.',
'**a，** 原四小时单次事件参与门槛分为固定场站费用与净运行成本，每年五十次独立调用。成本归因使用总成本分位数，不使用各项独立的边际分位数。**b，** 新参考零违约合格产品的场站费用敏感性：四小时/16 h 开始间隔报价 4.42 kW，八小时/16 h 和八小时/24 h 报价 2.95 kW。**c，** 三者无固定费用时的补偿门槛。**d，** 在 16 h 开始间隔、零场站费用下，八小时产品同时优于合格四小时产品与不参与所需的最低价格。图例给出八小时与四小时的模型容量；1% 和零损失分别选值。b–d 使用 10% 工作可参与、65% 工作供给利用率、参考期限、修正后的 MPC，以及每年十二组独立的四次调用。全部成本均按比例折算至 1 MW，等待价格为每 GPU-h 每小时 0.005 美元，电价为每 kWh 0.10 美元，交付电量收入为每 MWh 50 美元；2,000 次年度抽样包括失败轨迹。40% 与 60% 工作可参与仍依赖额外的批任务参与与业务结构假设。这些是条件性补偿筛选，不是利润或全年连续市场模拟。')

s('S20_005',
'The six notes follow the main results. Methods retain the five workload configurations and the controller-correction comparison, then describe the new structural and timing tests. Seventeen numbered tables distinguish these evidence stages: Tables 5 and 7 retain the original controller, Tables 10–12 the recovery repair, and Tables 13–17 the zero-loss checks, independently confirmed structural choices, production timing and cost decomposition. Source Data preserve all successes and failures, frozen inputs, full hourly fields, ready plotting tables and recovery code.',
'六则说明对应正文结果。方法保留五档工作配置与控制器修复比较，再说明新增结构及时序检验。十七张编号表区分证据阶段：表 5、7 保留原控制器，表 10–12 对应恢复修复，表 13–17 对应零损失核对、独立确认的结构选择、生产时序与费用分解。源数据保留全部成功与失败、冻结输入、完整逐时字段、直接绘图表和恢复代码。')
s('S20_012','### 3. Service standards and call history must be tested together','### 3. 服务标准与调用历史必须共同检验')
add(INSERT_SI,'S21_note3','S23_note3',
'The new structural test begins after that repair. Tightened deadlines and low instantaneous eligible power are separate failure mechanisms; a scenario may fail both. Zero total missed work is a stricter endpoint than a 1% allowance and receives its own development selection. In every new same-clock final-call contrast, the electrical outcome was identical with or without preceding calls. This prevents attributing all programme failure to damaged recovery. Chronological and permuted production submissions change temporal structure without changing class totals; neither ordering is asserted to be universally harder.',
'新结构检验从修复完成后开始。紧期限与瞬时可参与功率不足是不同的失败机制，同一情景可以同时出现。总期限违约工作为零比 1% 容忍度更严格，需要单独在开发集选择。所有新增相同时刻末次调用对照中，有无先前调用的电力结果均相同，因此不能把全部方案失败归因于恢复受损。生产提交的原序与置乱改变时间结构而不改变类别总量；不能宣称其中一种顺序普遍更难。')
add(INSERT_SI,'S20_019','S23_note6',
'The new decomposition confirms that approximately 95% of the reference single-event threshold is a fixed-site allocation. Operating components are attributed at the rank of total net cost so that they add back exactly. A shared fee changes the value relative to opting out, but a common fee cancels between two participating products. Product choice must compare annual net values at stated duration-specific prices, with only independently qualified choices eligible. The figures retain zero/low fees and operating costs separately to expose these different decisions.',
'新增分解确认，参考单次事件门槛约 95% 是固定场站分摊。运行项在总净成本的排序位置上归因，确保相加后准确还原总数。共享费用改变相对不参与的价值，而两个参与产品共同承担的费用在相互比较时抵消。产品选择必须在指定的分时长价格下比较年度净值，并只允许独立合格的选择参与。图中分别保留零/低费用与运行成本，以区分这些决策。')
for after,i in [('S20_037','M023_zero_methods'),('S21_recovery_stats','M023_structural_methods'),('S21_recovery_stats','M023_temporal_methods'),('S21_recovery_stats','M023_stats'),('S21_economics','M023_cost_method')]:
    row=next(r for group in INSERT_MAIN.values() for r in group if r['id']==i)
    add(INSERT_SI,after,'S'+i[1:],row['en'],row['zh'])
add(INSERT_SI,'S21_recovery_stats','S23_supply_method',
'A necessary supply diagnostic compared each active hour’s matched baseline PCC power minus community load and idle-plus-rigid data-centre power with 0.95 times the request. If the former was smaller, even zero flexible execution could not meet the interval requirement. This lower-envelope test identifies immediate shortage but does not prove feasibility when passed. Deadline and terminal criteria were scored over the whole 216-h episode. Last-call electrical scoring excluded those global service quantities, matched the final clock exactly and used the fresh run’s reindexed event 0. All 16 paired differences were zero. Programme-wide criteria were not substituted for local electrical outcomes.',
'必要供给诊断逐一比较事件小时中“匹配基线 PCC 功率减去社区负荷及数据中心空闲加刚性功率”与请求的 0.95 倍。前者较小时，即使灵活工作执行量为零，也无法满足逐时交付要求。该下包络检验识别即时不足，通过时并不证明可行。期限及期末标准按完整 216 h 运行阶段评分。末次调用的电力评分排除这些全局服务量，严格对齐末次时刻，并使用孤立运行重新编号后的事件 0。全部 16 个配对差值均为零，不能用整个方案的判定替代局部电力结果。')
add(INSERT_SI,'S21_recovery_stats','S23_temporal_detail',
'The timing input was the processed Alibaba 2020 job-submission table (714,903 GPU jobs), using trace hours 168–1511 inclusive. The eight 168-h weeks supplied hourly counts; each week’s class-specific synthetic total was normalised to the unchanged offered work. A whole-hour permutation preserved the marginal hourly volumes and the exact class–deadline totals. Seeds 986000 + 100w + r, for week w = 0,…,7 and realisation r = 0,…,9, generated paired inputs. Frozen tests used request fractions 0.5, 0.75 and 1 at eight-hour/16-h spacing, and 0.5 and 1 at eight-hour/24-h spacing. No external result selected a new fraction. Submission counts preserve one observed temporal feature; they do not supply real GPU-hour volumes, deadlines or job dependencies. All 320 timing input variants passed the baseline service gate.',
'时序输入为处理后的 Alibaba 2020 作业提交表，共 714,903 个 GPU 作业，使用轨迹第 168–1511 小时（含端点）。八个 168 h 周提供逐小时计数，各周各类合成总量归一至不变的供给工作量。完整小时置乱保留小时量的边际分布及精确的“类别—期限”总量。种子为 986000 + 100w + r，其中周 w = 0,…,7、实现 r = 0,…,9，生成配对输入。冻结检验在八小时/16 h 开始间隔采用请求比例 0.5、0.75、1，在八小时/24 h 采用 0.5、1。没有根据外部结果选择新比例。提交计数保留了一种真实时间特征，不提供真实 GPU 小时量、期限或作业依赖。全部 320 个时序输入变体通过基线服务门槛。')
s('S20_060','### Supplementary Figure 3 | Controller provenance and complete structural choices','### 补充图 3 | 控制器证据来源与完整结构选择')
s('S20_062',
'**a,** Earlier full-request eight-hour/twelve-hour-gap comparison across eligibility scenarios, on seeds 970000–970299. Points show original MPC, corrected MPC and the 10% guarded-greedy diagnostic; whiskers are one-sided 95% Wilson lower bounds. **b,** New same-clock final-call electrical outcomes under fresh or four-call histories, at the full request and 16-h start spacing; points coincide. The 24-h and extra-GPU controls also coincide. **c,** All eight new structural variants, two eight-hour start spacings and both service standards. Each positive development selection passed independent confirmation on 300 new seeds. Empty selections denote a finite-grid result. The reference four-hour/16-h choice is 4.42 kW with 300/300 successes under either standard. Tight deadlines halve reference slack; all new variants have 10% eligible work. These panels retain implementation repair as provenance rather than evidence of a physical limit.',
'**a，** 原有全额八小时调用、十二小时间隙比较，覆盖各参与比例，使用种子 970000–970299。点为原 MPC、修正 MPC 及 10% 情景的保护贪心诊断；须线为单侧 95% Wilson 下界。**b，** 新检验中，相同时刻末次调用在孤立或四次调用历史下的电力结果，采用全额请求与 16 h 开始间隔；两组点重合。24 h 与增加 GPU 对照也重合。**c，** 八个新结构变体、两种八小时开始间隔及两种服务标准。每个正容量开发选择均在 300 个新种子上通过独立确认。无选择表示有限网格结果。参考四小时/16 h 方案在两种标准下均为 4.42 kW、300/300 成功。紧期限将参考余量减半，全部新变体为 10% 工作可参与。这些面板将实现修复保留为证据来源，不把它当作物理限制证据。')
s('S20_066','### Supplementary Figure 5 | Operating prices, shared fees and non-participation','### 补充图 5 | 运行价格、共享费用与不参与选项')
s('S20_068',
'**a,** Waiting-price sensitivity for the new reference zero-miss selected products with no site fee. **b,** Missed-work valuation at eight-hour/16-h spacing; the full 5.90-kW request is an unqualified diagnostic, not an offerable option. **c,** Fifth-percentile annual net values at an illustrative common US$250 per offered accounting kW-year capacity price. Sharing changes the comparison with zero net value, while a common fee preserves the ranking between participating options. **d,** Eight-hour price required to beat both the zero-miss four-hour choice and opting out, with zero, shared US$2,500 or full US$25,000 annual fees. All panels use 10% eligibility, 65% offered utilisation, reference deadlines and twelve independent four-call series per year at proportional 1-MW accounting. The original reserve-life and displaced-value analyses remain in Supplementary Table 9 and the delivered data; no wear or market participation is measured.',
'**a，** 新参考零违约合格产品在无场站费用下的等待价格敏感性。**b，** 八小时/16 h 开始间隔下对期限违约工作估值；全额 5.90 kW 请求是未合格诊断，不能作为可报价选项。**c，** 示例中共同容量价格为每核算报价千瓦每年 250 美元时，年度净值第五百分位。费用共享改变相对零净值的比较，共同费用则保留参与选项之间的排序。**d，** 在零、共享 2,500 美元或全额 25,000 美元年费下，八小时产品同时优于零违约四小时产品和不参与所需的价格。全部面板采用 10% 工作可参与、65% 工作供给利用率、参考期限，每年十二组独立四次调用，并按比例折算至 1 MW。原备用寿命与业务挤占价值分析保留在补充表 9 和交付数据中；没有测量磨损或真实市场参与。')

def table(headers,rows):return '| '+' | '.join(headers)+' |\n|'+'|'.join(['---']*len(headers))+'|\n'+'\n'.join('| '+' | '.join(str(v) for v in row)+' |' for row in rows)
def tables():
    result=[]
    def put(i,title,zh_title,heads,zh_heads,rows,note,zh_note):
        result.extend([dict(id=f'S23_T{i}',en=f'### Supplementary Table {i} | {title}',zh=f'### 补充表 {i} | {zh_title}'),dict(id=f'S23_T{i}_data',en=table(heads,rows),zh=table(zh_heads,rows)),dict(id=f'S23_T{i}_note',en=note,zh=zh_note)])
    old=pd.read_csv(SOURCE/'inherited_zero_deadline_check.csv');rows=[]
    for r in old.itertuples():rows.append([r.kind,r.case,r.program,f'{r.fraction:g}','Yes' if r.selected_in_original_development else 'No',f'{r.successes_1pct}/{r.trials}',f'{r.successes_zero}/{r.trials}',f'{r.zero_wilson_lower:.4f}'])
    put(13,'Retrospective zero-deadline-loss check','回顾性零期限损失核对',['Study','Case','Programme','Fraction','Selected','1% success','Zero success','Zero lower'],['研究','情景','方案','比例','已选','1% 成功','零损失成功','零损失下界'],rows,
      'These are unchanged historical ledgers rescored at total missed work ≤1e−7 GPU-h, without reselection or new reliability samples. All 30 originally selected offers retain their success counts. The five unselected full H8G12 comparators remain comparators; the 10% case falls to 288/300 with lower bound 0.9369. Programme G denotes the gap after the event, unlike P (start spacing) in the new study. Yes/No identifies prior development selection.',
      '这些是原有账本按总期限违约工作 ≤1e−7 GPU-h 重评分，没有重新选值或新增可靠性样本。原 30 个已选报价的成功计数均不变。五个未选的全额 H8G12 请求仍为对照；10% 情景降至 288/300，下界 0.9369。G 指事件结束后的间隙，区别于新研究中表示开始间隔的 P。Yes/No 表示此前开发是否选中。')
    d=pd.read_csv(SOURCE/'selected_offers_confirmed.csv');rows=[]
    for r in d.itertuples():rows.append([r.variant,r.program,'zero' if r.endpoint=='success_zero' else '1%', 'NS' if pd.isna(r.selected_capacity_kw) else f'{r.selected_capacity_kw:.2f}', '—' if pd.isna(r.development_successes) else f'{int(r.development_successes)}/100','—' if pd.isna(r.confirmation_successes) else f'{int(r.confirmation_successes)}/300','—' if pd.isna(r.confirmation_lower) else f'{r.confirmation_lower:.4f}'])
    put(14,'Frozen structural selections and independent confirmation','冻结的结构选择与独立确认',['Variant','Programme','Loss rule','kW','Development','Confirmation','Lower'],['变体','方案','损失规则','kW','开发','确认','下界'],rows,
      'u is offered utilisation in percent; d100 is reference deadline slack and d50 is halved slack with a one-hour minimum; g is flexible GPU allocation in percent. Eligibility remains 10% and installed hardware remains 576 GPUs. H is duration and P is start spacing, so H8P16 has an 8-h gap. Fractions 0.25, 0.5, 0.75 and 1 multiply the fixed 5.898243186-kW request. All 26 positive endpoint-specific selections passed pointwise confirmation; eight decisions selected no candidate (NS), not zero physical capacity. Bounds are one-sided 95% Wilson limits from 300 new complete scenarios. All 3,200 development/confirmation input variants passed the no-response zero-service gate. The 1% and zero selections are separate and can coincide.',
      'u 为工作供给利用率百分数；d100 为参考期限余量，d50 为减半且至少一小时；g 为灵活 GPU 分配百分数。工作可参与比例固定 10%，安装硬件固定 576 个 GPU。H 为时长，P 为开始间隔，因此 H8P16 的间隙为 8 h。0.25、0.5、0.75、1 乘以固定 5.898243186 kW 请求。26 个按终点选择的正容量候选全部通过逐点确认，八个决策没有选出候选（NS），不表示物理容量为零。概率界为 300 个新完整情景的单侧 95% Wilson 下界。全部 3,200 个开发/确认输入变体通过无响应零违约服务门槛。1% 与零损失分别选择，可以相同。')
    d=pd.read_csv(SOURCE/'confirmation_summary.csv');d=d[(d.kind=='repeated')&(d.fraction==1)&(d.endpoint=='success_1pct')];rows=[]
    for r in d.itertuples():rows.append([r.variant,r.program,f'{r.successes}/300',r.instantaneous_supply_limited_trials,r.failed_deadline_miss,f'{r.total_missed_gpu_h_mean:.2f}'])
    put(15,'Full-request structural diagnostics','全额请求的结构诊断',['Variant','Programme','Success','Supply shortage','Deadline >1%','Mean missed GPU-h'],['变体','方案','成功','供给不足','期限违约 >1%','平均违约 GPU-h'],rows,
      'Every row uses the prespecified 5.90-kW comparator, independently of selection. Failure counts are non-exclusive and use 300 complete programmes. Supply shortage means at least one event hour fails the necessary zero-flexible-execution envelope; passing it does not guarantee feasibility. Mean missed work uses the entire episode. The corresponding same-clock final-call electrical outcomes coincide with the fresh-call outcomes in all 16 eight-hour comparisons. Full trial and event tables retain all failure combinations, including 0.1% and zero-loss secondary scores.',
      '每行均为预先指定的 5.90 kW 对照，与是否被选中无关。失败计数可重叠，单位为 300 个完整方案。供给不足指至少一个事件小时不满足灵活工作执行为零时的必要功率包络；通过不保证可行。平均期限违约量按整个运行阶段计。全部 16 个八小时比较中，相同末次时刻的电力结果均与孤立调用一致。完整试验及事件表保留所有失败组合，也保留 0.1% 与零损失评分。')
    d=pd.read_csv(SOURCE/'temporal_aggregate.csv');rows=[]
    for r in d.itertuples():rows.append([r.ordering,r.gpu_allocation_pct,r.program,f'{r.fraction*5.89824318624:.2f}',f'{r.successes_1pct}/80',f'{r.successes_zero}/80'])
    put(16,'Observed-order and permuted-hour timing stress','原序与小时置乱时序压力',['Order','GPU %','Programme','kW','1% success','Zero success'],['顺序','GPU %','方案','kW','1% 成功','零损失成功'],rows,
      'Chronological preserves hourly submission counts in eight observed weeks; permuted shuffles whole hours within each week. Each aggregate comprises ten synthetic realisations per week, not 80 independent production weeks. All observed-week results are supplied in temporal_week_summary.csv and Fig. 3c displays the primary pair. Work sizes, class allocation and deadlines remain synthetic. No external result retunes a request or establishes a new probability certificate; the direction of permutation effects varies with the request.',
      'Chronological 保留八个真实周的逐小时提交计数，permuted 在每周内置乱完整小时。每个汇总由每周十次合成实现组成，不是 80 个独立生产周。逐周结果完整提供于 temporal_week_summary.csv，图 3c 展示主要配对。工作量、类别分配和期限仍为合成。没有根据外部结果调整请求或建立新的概率资格证明；置乱的影响方向随请求变化。')
    d=pd.read_csv(SOURCE/'structural_cost_components.csv');d=d[(d.variant=='u65d100g10')&(d.offerable_success_1pct|d.offerable_success_zero)];rows=[]
    for r in d.itertuples():
        rule='1% + zero' if r.offerable_success_1pct and r.offerable_success_zero else '1%' if r.offerable_success_1pct else 'zero'
        rows.append([r.program,rule,f'{r.capacity_kw:.2f}',f'{r.accounting_offered_kw:.3f}',f'{r.net_operating_annual_q95:.2f}',f'{r.net_operating_per_kw_q95:.2f}',f'{r.net_operating_per_kw_q95+2500/r.accounting_offered_kw:.2f}',f'{r.net_operating_per_kw_q95+25000/r.accounting_offered_kw:.2f}'])
    put(17,'Qualified reference products and access-fee decomposition','合格参考产品与接入费用分解',['Programme','Selected rule','Model kW','Accounting kW','Operating US$/yr','No fee','Shared 2,500','Full 25,000'],['方案','所选规则','模型 kW','核算 kW','运行美元/年','无费用','共享 2,500','全额 25,000'],rows,
      'New reference workload: 10% eligibility, 65% offered utilisation, reference deadlines and corrected MPC. Twelve complete four-call series/year, 2,000 common annual draws, waiting US$0.005/GPU-h/h and missed-work price zero. The last three columns are US$ per offered accounting kW-year at a proportional 1-MW operating peak. Shared fees do not imply risk pooling. In the earlier single-event f10/H4 ledger, net operating exposure 43.3554 plus fixed allocation 819.9008 reproduces 863.2562 exactly; the fixed share is 94.9777%. All 30 earlier thresholds reconcile within 1e−9. Full component attribution, price grids, annual choices and duration-price boundaries are delivered as ready CSV tables; failed unselected comparators retain diagnostic costs only.',
      '新参考工作条件为 10% 可参与、65% 工作供给利用率、参考期限与修正 MPC。每年十二组完整四次调用，2,000 次共同年度抽样，等待价格每 GPU-h 每小时 0.005 美元，期限违约工作价格为零。末三列单位为按比例折算至 1 MW 运行峰值后的每报价千瓦每年美元。共享费用不表示风险组合。此前单次 f10/H4 账本中，净运行项 43.3554 加固定分摊 819.9008 准确还原 863.2562，固定项占 94.9777%；此前 30 个门槛的对账误差均小于 1e−9。完整成本分解、价格网格、年度选择及分时长价格边界以直接使用的 CSV 交付；未合格未选对照仅保留诊断成本。')
    return result

def main():
    assert json.loads((HERE/'numerical_audit.json').read_text())['status']=='PASS'
    (READER/'sources').mkdir(parents=True,exist_ok=True);changes=[];reports={}
    for stem,name,replacements,inserts in [('main','nature_communications_article.md',MAIN,INSERT_MAIN),('supplement','supplementary_information.md',SI,INSERT_SI)]:
        old=json.loads((HERE/'before'/f'{stem}_aligned_blocks.json').read_text());assert old['source_sha256']==h.sha(HERE/'before'/name)
        rows=[]
        for r0 in old['blocks']:
            r=dict(r0)
            if stem=='main' and r['id'] in REMOVE:
                changes.append(dict(id=r['id'],action='removed_from_main; scientific provenance retained in SI/archive',before=r));continue
            if r['id'] in replacements:r['en'],r['zh']=replacements[r['id']]
            for lang in ['en','zh']:r[lang]=r[lang].replace('docs/figures/repeat_mechanism_v1/artwork/','docs/figures/operating_tradeoffs_v1/artwork/')
            if r['id']=='M099':
                r['en']=r['en'].replace('release.<sup>20</sup>','release,<sup>20</sup> with the 2020 GPU trace supplying the separate chronological submission test.<sup>32</sup>')
                r['en']+=' Submission counts, processed submission-time records, frozen scenarios and all 22,400 new replays accompany the structural Source Data.'
                r['zh']+=' 新增独立时序检验采用 Alibaba 2020 GPU 轨迹的提交记录；其计数、处理后时间记录、冻结场景与全部 22,400 次新增重放均随源数据保存。<sup>32</sup>'
            if r['id']=='M027':
                r['en']=r['en'].replace('at most 1% missed work','at most 1% missed eligible work')
                r['zh']=r['zh'].replace('最多 1% 的工作期限违约','最多 1% 的可参与工作期限违约')
            if r['id']=='M076':
                r['en']=r['en'].replace('a deadline-miss fraction no greater','a deadline-miss fraction of eligible work no greater')
                r['zh']+=' 期限违约率的分母为到达的可参与工作 GPU 小时量。'
            if r['id']=='S20_036':
                r['en']=r['en'].replace('expired GPU-hour work divided by offered work','expired eligible GPU-hour work divided by total arriving eligible work').replace('divided by total arrivals','divided by total eligible arrivals')
                r['zh']+='\n\n期限违约与期末积压比例的分母均为全部到达的可参与工作 GPU 小时量。'
            if r['id']=='S20_006':
                r['en']=r['en'].replace('Supplementary Fig. 3; Table 5','Supplementary Fig. 3; Tables 5, 10–11, 13–16').replace('Tables 7, 9','Tables 7, 9, 12, 17')
                r['zh']=r['zh'].replace('补充图 3；表 5','补充图 3；表 5、10–11、13–16').replace('表 7、9','表 7、9、12、17')
            if r['id']=='S20_094':
                r['en']=r['en'].replace('10,000; 25,000; 50,000','0; 1,000; 2,500; 5,000; 10,000; 25,000; 50,000')
                r['zh']=r['zh'].replace('10,000；25,000；50,000','0；1,000；2,500；5,000；10,000；25,000；50,000').replace('10,000; 25,000; 50,000','0; 1,000; 2,500; 5,000; 10,000; 25,000; 50,000')
            if r!=r0:changes.append(dict(id=r['id'],action='replace',before=r0,after=r))
            rows.append(r)
            for new in inserts.get(r['id'],[]):rows.append(dict(new));changes.append(dict(id=new['id'],action='add',after=new))
        if stem=='supplement':
            rows.extend(tables())
            mapping=json.loads((HERE/'reference_number_map.json').read_text())
            for row in rows:
                if row['id']=='S023_temporal_methods':
                    for lang in ['en','zh']:row[lang]=row[lang].replace('<sup>32</sup>',f'<sup>{mapping["32"]}</sup>')
        else:rows=h.renumber_references(rows)
        header=f'<!--\nWorking {"manuscript" if stem=="main" else "Supplementary Information"}, version 0.23, 2026-09-10.\nAudited structural service tests, independent timing transfer and separated operating/access costs.\nAuthor metadata remain pending.\n-->\n\n'
        document=header+'\n\n'.join(r['en'] for r in rows)+'\n';path=ROOT/'manuscript'/name;path.write_text(document);(READER/'sources'/f'{stem}_original.md').write_text(document)
        note='本稿逐段对应正文与补充材料 v0.23（2026-09-10）。新增零违约与结构检验、八周生产提交时序对照、费用分解和时长产品选择；保留原有证据的适用范围。\n\n'
        cn=[];both=[]
        for r in rows:
            en,zh=h.reader_format(r['en']),h.reader_format(r['zh']);cn.append(zh);both.extend([zh] if en.startswith(('![','$$')) else [f'<!-- {r["id"]} -->\n{en}',zh])
        (READER/f'{stem}_zh.md').write_text(note+'\n\n'.join(cn)+'\n');(READER/f'{stem}_bilingual.md').write_text(note+'\n\n'.join(both)+'\n')
        (READER/f'{stem}_aligned_blocks.json').write_text(json.dumps(dict(source_sha256=h.sha(path),blocks=rows),ensure_ascii=False,indent=2)+'\n')
        def wc(t):return len(re.findall(r"\b[\w]+(?:[-’'][\w]+)*\b",t))
        reports[stem]=dict(status='PASS',blocks=len(rows),source_sha256=h.sha(path),old_words=wc((HERE/'before'/name).read_text()),new_words=wc(document))
        if stem=='main':
            reports[stem]['abstract_words']=wc(next(r['en'] for r in rows if r['id']=='M006'))
            reports[stem]['results_words']=wc(document.split('## Results\n')[1].split('## Discussion\n')[0])
    (HERE/'text_changes.json').write_text(json.dumps(changes,ensure_ascii=False,indent=2)+'\n');(HERE/'revision_validation.json').write_text(json.dumps(reports,indent=2)+'\n')
    (READER/'README.md').write_text('# 中文阅读稿 v17\n\n对应正文与补充材料 v0.23，包含新的结构与零期限违约检验、八周生产时序对照和费用拆分。\n\n- [正文中文全文](main_zh.md)\n- [补充材料中文全文](supplement_zh.md)\n- [正文中英对照](main_bilingual.md)\n- [补充材料中英对照](supplement_bilingual.md)\n')
    print(json.dumps(reports,indent=2))

if __name__=='__main__':main()
